-- Match Your Colors: the measured appearance of every helmet and armor (matcher v12), read from
-- src/appearance_data.lua (generated by research/make_appearance.py from the appearance study on the Armory front
-- view). For a measured kit: which LUT rows and patterns show and how many screen pixels each covers; for a seen
-- LUT row: how its paint looks there, perceived = s + g x mean albedo per channel (display-linear, per unit matte
-- lighting). Parsed on demand and kept for the session; nothing here runs per frame.
local Appearance = {}

-- Appearance.new(data) -> {row(lut, r), kit(id), hoods(id)}. data: the table src/appearance_data.lua returns.
-- row(lut hash, row index) -> {gr, gg, gb, sr, sg, sb} or nil (not measured).
-- kit(kit id, 8 hex digits) -> {luts = {hash -> true}, rows = {['lut:row'] -> {px, light}}, patterns = {hash -> {px,
-- gain}}} or nil; light: the row's pixels x mean screen luminance; gain {r, g, b} or nil (pattern seen too little to
-- measure its color).
-- hoods(kit id) -> {['lut:row'] -> true}: a hooded helmet's hood rows (the Recolor Hoods option), or nil.
-- kit_for(luts) -> kit, id: the one measured kit whose LUTs are exactly luts ({hash -> true}), or nil (none, or several:
-- a native look worn on another kit record, as a transmog's carrier, keeps its own measurement).
function Appearance.new(data)
    local self = {}
    local index = {}
    for i, lut in ipairs(data.luts) do index[lut] = i end
    local parsed_rows, parsed_kits, parsed_hoods = {}, {}, {}

    local function numbers(text)
        local out = {}
        for x in text:gmatch('%S+') do out[#out + 1] = tonumber(x) end
        return out
    end

    function self.row(lut, r)
        local i = index[lut]
        if not i or not data.rows[i] then return nil end
        local rows = parsed_rows[i]
        if not rows then
            rows = {}
            for entry in data.rows[i]:gmatch('[^|]+') do
                local v = numbers(entry)
                rows[v[1]] = {v[2], v[3], v[4], v[5], v[6], v[7]}
            end
            parsed_rows[i] = rows
        end
        return rows[r]
    end

    local function parse_kit(text)
        local luts_part, rows_part, patterns_part = text:match('^([^;]*);([^;]*);(.*)$')
        local kit = {luts = {}, rows = {}, patterns = {}}
        for i in luts_part:gmatch('%d+') do kit.luts[data.luts[tonumber(i)]] = true end
        for i, r, px, light in rows_part:gmatch('(%d+)%.(%d+)=(%d+),(%d+)') do
            kit.rows[data.luts[tonumber(i)] .. ':' .. r] = {tonumber(px), tonumber(light)}
        end
        for name, rest in patterns_part:gmatch('(%x+)=([%d%.,%-]+)') do
            local v = {}
            for x in rest:gmatch('[^,]+') do v[#v + 1] = tonumber(x) end
            kit.patterns[name] = {px = v[1], gain = v[4] and {v[2], v[3], v[4]} or nil}
        end
        return kit
    end

    function self.kit(id)
        local text = data.kits[id]
        if not text then return nil end
        if not parsed_kits[id] then parsed_kits[id] = parse_kit(text) end
        return parsed_kits[id]
    end

    local by_luts -- sorted LUT list -> kit id, or false when two kits share it
    function self.kit_for(luts)
        if not by_luts then
            by_luts = {}
            for id, text in pairs(data.kits) do
                local names = {}
                for i in text:match('^([^;]*)'):gmatch('%d+') do names[#names + 1] = data.luts[tonumber(i)] end
                table.sort(names)
                local key = table.concat(names, ',')
                by_luts[key] = by_luts[key] == nil and id or false
            end
        end
        local names = {}
        for name in pairs(luts) do names[#names + 1] = name end
        table.sort(names)
        local id = by_luts[table.concat(names, ',')]
        if not id then return nil end
        return self.kit(id), id
    end

    function self.hoods(id)
        local text = data.hoods and data.hoods[id]
        if not text then return nil end
        if not parsed_hoods[id] then
            local keys = {}
            for i, r in text:gmatch('(%d+)%.(%d+)') do keys[data.luts[tonumber(i)] .. ':' .. r] = true end
            parsed_hoods[id] = keys
        end
        return parsed_hoods[id]
    end
    return self
end

-- Runs once per kit or LUT: interpreted (it must not add traces to the LuaJIT code cache every mod shares).
if type(jit) == 'table' and type(jit.off) == 'function' then jit.off(Appearance.new, true) end

return Appearance
