-- Match Your Colors: capes (the Recolor Cape option): which rows of a cape's material LUT show, how much, and how
-- much of each its tint covers.
--
-- A cape kit is one piece (slot 1, type 0, body any, no unit of its own) on the armor's cape-mount unit; the game
-- binds its material LUT to the mount material's LUT slot like an armor piece's, so the recolor path is the
-- armor's. The cape shader (base material dafef1303e987a57, disassembled 2026-10-07: KB match-your-colors-cape-tint)
-- picks the LUT row per texel from the kit's decal scalar fields: the outside takes the first of R, G, B at least
-- 0.496 (byte SET) as row 1, 2 or 3, else row 0; the inside takes row 1 where R is set, else row 4. A is the cape's
-- opacity; the cloth only shows inside one outline the capes share (OUTLINE, from the 17 capes whose A covers 47-50%
-- of the texture; tattered capes lie inside it).
-- The kit's cape LUT (16 x H, one row per material row; rows past H read zeros) tints each row: its base color goes
-- toward column 3's RGB by t = |w| x saturate(c6.w x (g' - c6.z)) (w: column 3 w; c6: column 6; g': the gradient's
-- R at the texel, 1 - it when w < 0). United in Equality's purple is such a tint. A tinted row is two colors: its
-- base and its tint row (key '<cape LUT>:<row>', the material row with column 0 the tint; src/recolor.lua refits
-- column 3 of a copy of the cape LUT). Its other columns place the emblem-sheet layers (their colors are the sheet's).
--
-- The areas come from a GRID x GRID sample of the fields and of the gradient (the nearest texel of the smallest mip
-- with both sides at least GRID; RGBA8, RGBA16F, BC7, BC3 or BC4): a cell counts when it is inside the outline and its
-- A is set; the outside weighs W_OUT and the inside W_IN (the back shows the whole outside, the front part of the
-- inside), split between the row's base (1 - t) and its tint (t, in 1 / TINT_STEPS steps: integer sums). Area =
-- weight / the weight of every counted cell of a row the LUT has. research/capes.py is the reference
-- (tests/fixtures/capes.lua). Nothing here runs per frame: Capes.analyse runs inside a recolor job.
local ffi = require('ffi')
local bit = require('bit')
local band, rshift = bit.band, bit.rshift

local Capes = {}

Capes.GRID, Capes.THRESHOLD, Capes.W_OUT, Capes.W_IN = 128, 128, 13, 7
Capes.SET, Capes.TINT_STEPS = 127, 4096 -- a row's channel set from 0.496 (127 / 255 = 0.498); tint weight steps
Capes.ZONE_BINS = 8 -- a zone's border cells by the tint weight there, in eighths (src/matcher.lua cape_zones)

-- The outline: GRID rows of GRID bits, most significant bit first (generated by research/capes.py write-lua from
-- research/cape_outline.json).
-- outline begin
Capes.OUTLINE = {
    '00000000000000000000000000000000', '00000000000000000000000000000000', '00000000000000000000000000000000',
    '00000000000000000000000000000000', '00000000000000000000000000000000', '00000000000000000000000000000000',
    '00000000000000000000000000000000', '00000000000020000004000000000000', '000000000001f000001f800000000000',
    '000000000001fc00003f800000000000', '000000000001fe00007f800000000000', '000000000001ff0000ff800000000000',
    '000000000003ffc003ffc00000000000', '000000000003ffe007ffc00000000000', '000000000003fff00fffc00000000000',
    '000000000003fffc3fffc00000000000', '000000000003ffffffffc00000000000', '000000000003ffffffffc00000000000',
    '000000000003ffffffffc00000000000', '000000000003ffffffffc00000000000', '000000000003ffffffffc00000000000',
    '000000000003ffffffffc00000000000', '000000000003ffffffffc00000000000', '000000000003ffffffffc00000000000',
    '000000000003ffffffffc00000000000', '000000000003ffffffffc00000000000', '000000000007ffffffffe00000000000',
    '000000000007ffffffffe00000000000', '000000000007ffffffffe00000000000', '00000000000ffffffffff00000000000',
    '00000000000ffffffffff00000000000', '00000000001ffffffffff80000000000', '00000000001ffffffffff80000000000',
    '00000000003ffffffffffc0000000000', '00000000007ffffffffffc0000000000', '00000000007ffffffffffe0000000000',
    '0000000000fffffffffffe0000000000', '0000000000ffffffffffff0000000000', '0000000001ffffffffffff8000000000',
    '0000000001ffffffffffff8000000000', '0000000003ffffffffffffc000000000', '0000000003ffffffffffffc000000000',
    '0000000007ffffffffffffe000000000', '0000000007ffffffffffffe000000000', '000000000ffffffffffffff000000000',
    '000000000ffffffffffffff000000000', '000000001ffffffffffffff800000000', '000000001ffffffffffffff800000000',
    '000000003ffffffffffffffc00000000', '000000003ffffffffffffffc00000000', '000000007ffffffffffffffe00000000',
    '000000007ffffffffffffffe00000000', '00000000ffffffffffffffff00000000', '00000000ffffffffffffffff00000000',
    '00000001ffffffffffffffff80000000', '00000001ffffffffffffffff80000000', '00000003ffffffffffffffffc0000000',
    '00000003ffffffffffffffffc0000000', '00000007ffffffffffffffffe0000000', '00000007ffffffffffffffffe0000000',
    '0000000ffffffffffffffffff0000000', '0000001ffffffffffffffffff8000000', '0000001ffffffffffffffffff8000000',
    '0000003ffffffffffffffffffc000000', '0000003ffffffffffffffffffc000000', '0000007ffffffffffffffffffe000000',
    '0000007ffffffffffffffffffe000000', '000000ffffffffffffffffffff000000', '000001ffffffffffffffffffff800000',
    '000001ffffffffffffffffffff800000', '000003ffffffffffffffffffffc00000', '000003ffffffffffffffffffffc00000',
    '000007ffffffffffffffffffffe00000', '000007ffffffffffffffffffffe00000', '00000ffffffffffffffffffffff00000',
    '00001ffffffffffffffffffffff80000', '00001ffffffffffffffffffffff80000', '00003ffffffffffffffffffffffc0000',
    '00003ffffffffffffffffffffffc0000', '00007ffffffffffffffffffffffe0000', '0000ffffffffffffffffffffffff0000',
    '0000ffffffffffffffffffffffff0000', '0001ffffffffffffffffffffffff8000', '0001ffffffffffffffffffffffff8000',
    '0003ffffffffffffffffffffffffc000', '0007ffffffffffffffffffffffffe000', '0007ffffffffffffffffffffffffe000',
    '000ffffffffffffffffffffffffff000', '000ffffffffffffffffffffffffff000', '001ffffffffffffffffffffffffff800',
    '003ffffffffffffffffffffffffffc00', '003ffffffffffffffffffffffffffc00', '007ffffffffffffffffffffffffffe00',
    '007ffffffffffffffffffffffffffe00', '00ffffffffffffffffffffffffffff00', '01ffffffffffffffffffffffffffff80',
    '01ffffffffffffffffffffffffffff80', '03ffffffffffffffffffffffffffffc0', '03ffffffffffffffffffffffffffffc0',
    '07ffffffffffffffffffffffffffffe0', '07ffffffffffffffffffffffffffffe0', '0ffffffffffffffffffffffffffffff0',
    '1ffffffffffffffffffffffffffffff8', '1ffffffffffffffffffffffffffffff8', '3ffffffffffffffffffffffffffffffc',
    '3ffffffffffffffffffffffffffffffc', '1ffffffffffffffffffffffffffffff8', '1ffffffffffffffffffffffffffffff8',
    '3ffffffffffffffffffffffffffffffc', '3ffffffffffffffffffffffffffffffc', '0ffffffffffffffffffffffffffffff0',
    '03ffffffffffffffffffffffffffffc0', '007ffffffffffffffffffffffffffe00', '001ffffffffffffffffffffffffff800',
    '0003ffffffffffffffffffffffffc000', '0000ffffffffffffffffffffffff0000', '00001ffffffffffffffffffffff80000',
    '000007ffffffffffffffffffffe00000', '000000ffffffffffffffffffff000000', '0000001ffffffffffffffffff8000000',
    '00000003ffffffffffffffffc0000000', '000000003ffffffffffffffc00000000', '0000000000ffffffffffff0000000000',
    '000000000007ffffffffe00000000000', '00000000000003ffffc0000000000000', '00000000000000000000000000000000',
    '00000000000000000000000000000000', '00000000000000000000000000000000',
}
-- outline end

local outline_cells
-- The outline as a GRID x GRID byte array (1: inside), decoded once.
function Capes.outline()
    if outline_cells then return outline_cells end
    local g = Capes.GRID
    local cells = ffi.new('uint8_t[?]', g * g)
    for y, row in ipairs(Capes.OUTLINE) do
        for d = 1, #row do
            local nibble = tonumber(row:sub(d, d), 16)
            for k = 0, 3 do
                cells[(y - 1) * g + (d - 1) * 4 + k] = band(rshift(nibble, 3 - k), 1)
            end
        end
    end
    outline_cells = cells
    return cells
end

-- RGB565 to 8-bit channels, as Pillow expands them.
local function expand565(c)
    local r, g, b = rshift(band(c, 0xF800), 8), rshift(band(c, 0x07E0), 3), band(c, 0x001F) * 8
    return bit.bor(r, rshift(r, 5)), bit.bor(g, rshift(g, 6)), bit.bor(b, rshift(b, 5))
end

-- The alpha table and the four colors of the BC3 block being decoded, refilled per block (no allocation per block).
local ALPHA, PALETTE = {}, {[0] = {}, {}, {}, {}}

-- The eight values of a BC3 alpha block (also a BC4 block) with endpoints a0, a1, into ALPHA, with Pillow's integer
-- arithmetic (the parity reference decodes BC3 with Pillow, BC4 with the same arithmetic: research/capes.py).
local function alpha_palette(a0, a1)
    local a = ALPHA
    a[0], a[1] = a0, a1
    if a0 > a1 then
        for k = 1, 6 do a[k + 1] = math.floor(((7 - k) * a0 + k * a1) / 7) end
    else
        for k = 1, 4 do a[k + 1] = math.floor(((5 - k) * a0 + k * a1) / 5) end
        a[6], a[7] = 0, 255
    end
    return a
end

-- One 8-byte BC4 block (from block[offset], offset 0 by default) into 16 RGBA texels (out: 64 bytes, row major):
-- R the block's value, G and B 0, A 255 (capes' gradients: only R is read).
function Capes.bc4_block(block, out, offset)
    local o = offset or 0
    local a = alpha_palette(block[o], block[o + 1])
    local lut1 = block[o + 2] + block[o + 3] * 256 + block[o + 4] * 65536
    local lut2 = block[o + 5] + block[o + 6] * 256 + block[o + 7] * 65536
    for n = 0, 15 do
        local index = n < 8 and band(rshift(lut1, 3 * n), 7) or band(rshift(lut2, 3 * (n - 8)), 7)
        out[n * 4], out[n * 4 + 1], out[n * 4 + 2], out[n * 4 + 3] = a[index], 0, 0, 255
    end
end

-- One 16-byte BC3 (DXT5) block (from block[offset], offset 0 by default) into 16 RGBA texels (out: 64 bytes, row
-- major), with Pillow's integer arithmetic (the parity reference decodes with Pillow).
function Capes.bc3_block(block, out, offset)
    local o = offset or 0
    local a = alpha_palette(block[o], block[o + 1])
    local lut1 = block[o + 2] + block[o + 3] * 256 + block[o + 4] * 65536
    local lut2 = block[o + 5] + block[o + 6] * 256 + block[o + 7] * 65536
    local r0, g0, b0 = expand565(block[o + 8] + block[o + 9] * 256)
    local r1, g1, b1 = expand565(block[o + 10] + block[o + 11] * 256)
    local p = PALETTE
    p[0][1], p[0][2], p[0][3] = r0, g0, b0
    p[1][1], p[1][2], p[1][3] = r1, g1, b1
    p[2][1], p[2][2], p[2][3] = math.floor((2 * r0 + r1) / 3), math.floor((2 * g0 + g1) / 3), math.floor((2 * b0 + b1) / 3)
    p[3][1], p[3][2], p[3][3] = math.floor((r0 + 2 * r1) / 3), math.floor((g0 + 2 * g1) / 3), math.floor((b0 + 2 * b1) / 3)
    local indices = block[o + 12] + block[o + 13] * 256 + block[o + 14] * 65536 + block[o + 15] * 16777216
    for n = 0, 15 do
        local c = p[band(rshift(indices, 2 * n), 3)]
        local alpha = n < 8 and band(rshift(lut1, 3 * n), 7) or band(rshift(lut2, 3 * (n - 8)), 7)
        out[n * 4], out[n * 4 + 1], out[n * 4 + 2], out[n * 4 + 3] = c[1], c[2], c[3], a[alpha]
    end
end

-- The smallest mip with both sides at least GRID (mip 0 when the texture is smaller).
local function choose_mip(info)
    local m = 0
    while m + 1 < info.mips and rshift(info.width, m + 1) >= Capes.GRID and rshift(info.height, m + 1) >= Capes.GRID do
        m = m + 1
    end
    return m
end

-- Sampling state, reused by every analysis (nothing allocated per block or cell): the texel column and row of each
-- grid cell, the block row each block column holds in `decoded` (64 bytes per block), and one decoded block.
local XS, YS, HELD = {}, {}, {}
local decoded, decoded_size = nil, 0
local one_block = ffi.new('uint8_t[64]')

-- Cell i from texel (x, y) of an uncompressed mip w texels wide: RGBA8 as is, RGBA16F clamped and rounded to bytes.
local function plain_cell(half16, raw, w, x, y, out, i)
    if half16 then
        local s = (y * w + x) * 8
        for c = 0, 3 do
            local v = half16(raw[s + 2 * c], raw[s + 2 * c + 1])
            if v ~= v or v < 0 then v = 0 elseif v > 1 then v = 1 end
            out[i * 4 + c] = math.floor(v * 255 + 0.5)
        end
    else
        local s = (y * w + x) * 4
        out[i * 4], out[i * 4 + 1], out[i * 4 + 2], out[i * 4 + 3] = raw[s], raw[s + 1], raw[s + 2], raw[s + 3]
    end
end

-- Bytes per block of each block decoder (Texture.bc7_block's is set when read_mip picks it).
local BLOCK_BYTES = {[Capes.bc3_block] = 16, [Capes.bc4_block] = 8}

-- Cell i from texel (x, y) of a block-compressed mip `wide` blocks wide (decode: Texture.bc7_block,
-- Capes.bc3_block or Capes.bc4_block): each block is decoded once, when the first cell inside the outline needs it.
local function block_cell(decode, raw, wide, x, y, out, i)
    local bx, by = rshift(x, 2), rshift(y, 2)
    local base = bx * 64
    if HELD[bx] ~= by then
        decode(raw, one_block, (by * wide + bx) * BLOCK_BYTES[decode])
        for k = 0, 63 do decoded[base + k] = one_block[k] end
        HELD[bx] = by
    end
    local s = base + (band(y, 3) * 4 + band(x, 3)) * 4
    out[i * 4], out[i * 4 + 1], out[i * 4 + 2], out[i * 4 + 3] = decoded[s], decoded[s + 1], decoded[s + 2], decoded[s + 3]
end

-- The mip's bytes and the cell function for its format: the raw bytes, the width, and the decoder or half reader.
local function read_mip(Texture, pixels, info, m, scratch)
    local size = info.mip_offsets[m + 1] and info.mip_offsets[m + 1] - info.mip_offsets[m]
        or info.layer_bytes - info.mip_offsets[m]
    local raw = scratch(size)
    pixels(info.mip_offsets[m], size, raw, 0)
    local f = info.format
    if f == Texture.FORMAT_RGBA8 or f == Texture.FORMAT_RGBA8_SRGB then return raw, plain_cell, false end
    if f == Texture.FORMAT_RGBA16F then return raw, plain_cell, Texture.half end
    if f == Texture.FORMAT_BC7 then
        BLOCK_BYTES[Texture.bc7_block] = 16
        return raw, block_cell, Texture.bc7_block
    end
    if f == Texture.FORMAT_BC3 then return raw, block_cell, Capes.bc3_block end
    if f == Texture.FORMAT_BC4 then return raw, block_cell, Capes.bc4_block end
    error('cape texture format ' .. f, 0)
end

-- The fields sampled on the grid (the nearest texel of the chosen mip) into `out` (GRID x GRID x 4 bytes): only the
-- cells inside the outline are written (the others never count), and a block-compressed mip has only the blocks
-- those cells need decoded. yield() is called after every grid row.
-- The texel column and row of every grid cell in a mip w x h (the nearest texel to the cell's center), into XS, YS.
local function grid_positions(w, h)
    local g = Capes.GRID
    for k = 0, g - 1 do
        XS[k], YS[k] = math.floor((2 * k + 1) * w / (2 * g)), math.floor((2 * k + 1) * h / (2 * g))
    end
end

-- The block cache made ready for a mip `wide` blocks wide: room for one block row, nothing decoded yet.
local function reset_blocks(wide)
    if wide * 64 > decoded_size then decoded, decoded_size = ffi.new('uint8_t[?]', wide * 64), wide * 64 end
    for k = 0, wide - 1 do HELD[k] = -1 end
end

function Capes.cells(Texture, pixels, info, scratch, out, yield)
    local m = choose_mip(info)
    local w, h = math.max(1, rshift(info.width, m)), math.max(1, rshift(info.height, m))
    local raw, cell, codec = read_mip(Texture, pixels, info, m, scratch)
    grid_positions(w, h)
    local width = w -- in texels, or in blocks for a block-compressed mip
    if cell == block_cell then
        width = math.max(1, rshift(w + 3, 2))
        reset_blocks(width)
    end
    local g, shape = Capes.GRID, Capes.outline()
    for gy = 0, g - 1 do
        local y = YS[gy]
        for gx = 0, g - 1 do
            local i = gy * g + gx
            if shape[i] == 1 then cell(codec, raw, width, XS[gx], y, out, i) end
        end
        if yield then yield() end
    end
    return out
end

-- A cell's tint weight in TINT_STEPS steps for material row `row`, the gradient byte g and the cape LUT tint
-- ({values, width, height}, or nil): floor(TINT_STEPS x min(|w| x saturate(c6.w x (g' - c6.z)), 1) + 0.5); 0 past
-- the cape LUT's height (the shader reads zeros there).
local function tint_steps(tint, row, g)
    if not tint or row >= tint.height then return 0 end
    local v, o = tint.values, row * tint.width * 4
    local w = v[o + 15] -- column 3 w: strength, and the gradient inverted when negative
    local gp = g / 255
    if w < 0 then gp = 1 - gp end
    local x = v[o + 27] * (gp - v[o + 26]) -- column 6 w (sharpness) x (g' - column 6 z (offset))
    if x < 0 then x = 0 elseif x > 1 then x = 1 end
    local t = math.abs(w) * x
    if t > 1 then t = 1 end
    return math.floor(t * Capes.TINT_STEPS + 0.5)
end

-- Cell i's outside row (the first of R, G, B set: 1-3, else 0) and inside row (1 for R, else 4).
local function cell_rows(cells, i)
    local s = Capes.SET
    local r, g, b = cells[i * 4] >= s, cells[i * 4 + 1] >= s, cells[i * 4 + 2] >= s
    return r and 1 or (g and 2 or (b and 3 or 0)), r and 1 or 4
end

-- One side's row of a counted cell into acc ({height, tint, grad, base, tinted, total}): its weight x TINT_STEPS,
-- split between the row's base and its tint at gradient byte `level`, when the row is below the height.
local function add_side(acc, row, weight, level)
    if row >= acc.height then return end
    local steps = tint_steps(acc.tint, row, level)
    acc.base[row] = acc.base[row] + weight * (Capes.TINT_STEPS - steps)
    acc.tinted[row] = acc.tinted[row] + weight * steps
    acc.total = acc.total + weight * Capes.TINT_STEPS
end

-- Cell i (inside the outline), when its A is set: its outside and inside rows into acc (add_side).
local function count_cell(cells, i, acc)
    if cells[i * 4 + 3] < Capes.THRESHOLD then return end
    local outside, inside = cell_rows(cells, i)
    local level = acc.grad and acc.grad[i * 4] or 0
    add_side(acc, outside, Capes.W_OUT, level)
    add_side(acc, inside, Capes.W_IN, level)
end

-- Per row (0-4) the weight of its base and of its tint over the cells inside the outline, and their total, by the
-- model above (tint: the cape LUT or nil, grad: the gradient's cells); yield (optional) after every 2 grid rows (a
-- counted cell weighs both its sides' tints).
local function count_rows(cells, height, tint, grad, yield)
    local shape, band_cells = Capes.outline(), 2 * Capes.GRID
    local acc = {height = height, tint = tint, grad = grad, base = {}, tinted = {}, total = 0}
    for r = 0, 4 do acc.base[r], acc.tinted[r] = 0, 0 end
    for i = 0, Capes.GRID * Capes.GRID - 1 do
        if shape[i] == 1 then count_cell(cells, i, acc) end
        if yield and (i + 1) % band_cells == 0 then yield() end
    end
    return acc.base, acc.tinted, acc.total
end

-- ({row -> area} of the rows' base colors, {row -> area} of their tints) for a material LUT of `height` rows from
-- the fields' cells, by the model above; tint: the cape LUT ({values, width, height}) and grad: the gradient's cells
-- (both, or no tint); yield (optional) as count_rows.
function Capes.areas(cells, height, yield, tint, grad)
    local base, tinted, total = count_rows(cells, height, grad and tint or nil, tint and grad or nil, yield)
    local rows, tints = {}, {}
    if total == 0 then return rows, tints end
    for r = 0, math.min(height, 5) - 1 do
        if base[r] > 0 then rows[r] = base[r] / total end
        if tinted[r] > 0 then tints[r] = tinted[r] / total end
    end
    return rows, tints
end

-- The outside row of every grid cell that counts (0-3), -1 for the others; reused by every analysis.
local ROWS = ffi.new('int8_t[?]', Capes.GRID * Capes.GRID)

-- ROWS: the outside row of every grid cell that counts (inside the outline, A set), -1 for the others; yield
-- (optional) after every 2 grid rows (about 0.5 ms of interpreted work outside the game).
local function outside_rows(cells, yield)
    local shape, band_cells = Capes.outline(), 2 * Capes.GRID
    for i = 0, Capes.GRID * Capes.GRID - 1 do
        ROWS[i] = (shape[i] == 1 and cells[i * 4 + 3] >= Capes.THRESHOLD) and (cell_rows(cells, i)) or -1
        if yield and (i + 1) % band_cells == 0 then yield() end
    end
end

-- A zone's per-bin cell counts, all 0.
local function zero_bins()
    local counts = {}
    for k = 0, Capes.ZONE_BINS - 1 do counts[k] = 0 end
    return counts
end

-- Neighbour cell j of a zone cell: counted in out[zone][q] by the tint bin there when it shows another outside row q
-- below the height (ctx: {height, tint, grad, width (tint steps per bin)}).
local function border_cell(out, zone, j, ctx)
    local q = ROWS[j]
    if q < 0 or q == zone or q >= ctx.height then return end
    local steps = tint_steps(ctx.tint, q, ctx.grad and ctx.grad[j * 4] or 0)
    local bin = math.min(math.floor(steps / ctx.width), Capes.ZONE_BINS - 1)
    local by_row = out[zone] or {}
    out[zone] = by_row
    local counts = by_row[q] or zero_bins()
    by_row[q] = counts
    counts[bin] = counts[bin] + 1
end

-- The 8 neighbours inside the grid of a zone cell at (x, y) (border_cell).
local function count_border(out, zone, x, y, ctx)
    local g = Capes.GRID
    for dy = -1, 1 do
        local yy = y + dy
        if yy >= 0 and yy < g then
            for dx = -1, 1 do
                local xx = x + dx
                if (dy ~= 0 or dx ~= 0) and xx >= 0 and xx < g then border_cell(out, zone, yy * g + xx, ctx) end
            end
        end
    end
end

-- The zone cells of grid row y (rows 1 to the height) with their borders into out (count_border).
local function zone_row(out, y, ctx)
    local g = Capes.GRID
    for x = 0, g - 1 do
        local zone = ROWS[y * g + x]
        if zone > 0 and zone < ctx.height then count_border(out, zone, x, y, ctx) end
    end
end

-- The outside design zones (rows 1-3 below `height`: emblems, marks, sashes) and the cloth bordering them, as
-- research/capes.py zones: {[zone] = {[row] = {[bin] = cells}}} over each zone cell's 8 neighbours that count and show
-- another outside row; nil when no zone borders anything. yield (optional) after every grid row (a row of zone cells
-- checks up to 1,024 neighbours).
function Capes.zones(cells, height, tint, grad, yield)
    outside_rows(cells, yield)
    local ctx = {height = height, tint = grad and tint or nil, grad = tint and grad or nil,
                 width = Capes.TINT_STEPS / Capes.ZONE_BINS}
    local out = {}
    for y = 0, Capes.GRID - 1 do
        zone_row(out, y, ctx)
        if yield then yield() end
    end
    return next(out) and out or nil
end

-- Emblem-sheet layers (cape LUT columns 4-6, 7-9, 10-12, 13-15 of a row; KB match-your-colors-cape-tint, round 2): a
-- layer whose strength |column 6, 9, 12 or 15 y| exceeds LAYER_ON draws, on the outside cells of its row, the decal
-- sheet over the cloth: albedo = lerp(albedo, sheet RGB, strength x sheet A), at the sheet UV the shader computes from
-- the placement (column 4: center, size), the sheet offset, rotation and scale (column 5) and the mirror (sign of
-- column 6 y). Its colors are the sheet's; src/recolor.lua recolors its sheet cell when it would no longer read.
Capes.LAYER_ON, Capes.EMBLEM_MIN, Capes.SHEET_MIP = 0.001, 0.5, 3
Capes.RECT_SAMPLES, Capes.RECT_MARGIN = 64, 2

-- Layer k (0-3) of cape LUT row r ({values, width}): its placement, sheet mapping and strength, or nil when off.
local function layer_of(tint, r, k)
    local v, o = tint.values, r * tint.width * 4
    local c4, c5, c6 = o + (4 + 3 * k) * 4, o + (5 + 3 * k) * 4, o + (6 + 3 * k) * 4
    local y6 = v[c6 + 1]
    if math.abs(y6) <= Capes.LAYER_ON then return nil end
    local sx0, sy0 = v[c4 + 2], v[c4 + 3]
    return {row = r, layer = k, cx = v[c4], cy = v[c4 + 1], sx0 = sx0, sy0 = sy0, sx = math.max(sx0, 1e-4),
            sy = math.max(sy0, 1e-4), sn = math.sin(v[c5 + 2]), cs = math.cos(v[c5 + 2]), ox = v[c5], oy = v[c5 + 1],
            swap = v[c5 + 3] < 0, scale = math.max(math.abs(v[c5 + 3]), 1e-4), mirror = y6 < 0,
            strength = math.abs(y6)}
end

-- The sheet UV layer l samples at cape uv2 (u, v), as the shader computes it (research/capes.py layer_point, the same
-- order of operations): su, sv, inside (within the placement rectangle and the sheet).
local function layer_point(l, u, v)
    local lx, ly = (u - (l.cx - 0.5 * l.sx0)) / l.sx, (v - (l.cy - 0.5 * l.sy0)) / l.sy
    local dx, dy = l.sx0 * (lx - 0.5), l.sy0 * (ly - 0.5)
    if not (math.abs((dx * l.cs + dy * l.sn) / l.sx) < 0.5 and math.abs((-dx * l.sn + dy * l.cs) / l.sy) < 0.5) then
        return 0, 0, false
    end
    local qx, qy = l.sx0 * (2.0 * lx - 1.0), l.sy0 * (2.0 * ly - 1.0)
    local p1, p2 = qx * l.cs + qy * l.sn, -qx * l.sn + qy * l.cs
    if l.swap then p1, p2 = -p2, p1 end
    p1, p2 = p1 / l.scale, p2 / l.scale
    if l.mirror then p1 = -p1 end
    local wx, wy = l.ox + p1, l.oy + p2
    if not (math.abs(0.5 * wx) < 0.5 and math.abs(0.5 * wy) < 0.5) then return 0, 0, false end
    return 0.5 * wx + 0.5, 0.5 * wy + 0.5, true
end

-- The mip-0 texels of a w x h sheet layer l samples, {x0, y0, x1, y1} (half-open, clamped, RECT_MARGIN around), from
-- RECT_SAMPLES x RECT_SAMPLES points over its placement rectangle; nil when it samples none.
local function sheet_rect(l, w, h)
    local n = Capes.RECT_SAMPLES
    local lo_u, hi_u, lo_v, hi_v = math.huge, -math.huge, math.huge, -math.huge
    for j = 0, n - 1 do
        local v = l.cy + l.sy0 * ((j + 0.5) / n - 0.5)
        for i = 0, n - 1 do
            local su, sv, inside = layer_point(l, l.cx + l.sx0 * ((i + 0.5) / n - 0.5), v)
            if inside then
                lo_u, hi_u, lo_v, hi_v = math.min(lo_u, su), math.max(hi_u, su), math.min(lo_v, sv), math.max(hi_v, sv)
            end
        end
    end
    if lo_u == math.huge then return nil end
    local m = Capes.RECT_MARGIN
    return {math.max(math.floor(lo_u * w) - m, 0), math.max(math.floor(lo_v * h) - m, 0),
            math.min(math.floor(hi_u * w) + 1 + m, w), math.min(math.floor(hi_v * h) + 1 + m, h)}
end

-- A texture's archive, record and description (Texture.describe), or nil when it is not in the searched archives.
local function texture_info(name, deps)
    local Kits = deps.Kits
    if not name or name == Kits.NO_LUT then return nil end
    local archive, record = deps.find(name, Kits.TYPE_TEXTURE)
    if not archive then return nil end
    local size = deps.slim.part_size(record, 'main')
    local main = deps.scratch(size)
    deps.slim.part(archive, record, 'main', 0, size, main, 0)
    return archive, record, deps.Texture.describe(main, size)
end

-- A decal sheet's mip SHEET_MIP (or its last) as {raw, w, h, wide (blocks per row), decode, format} with the sheet's
-- full size, or nil when it is not in the searched archives or not a format read here.
local function sheet_mip(name, deps)
    local Texture = deps.Texture
    local archive, record, info = texture_info(name, deps)
    if not archive then return nil end
    local m = math.min(Capes.SHEET_MIP, info.mips - 1)
    local raw, cell, codec = read_mip(Texture, Texture.pixels(deps.slim, archive, record, info), info, m,
                                      deps.big_scratch)
    local w, h = math.max(1, rshift(info.width, m)), math.max(1, rshift(info.height, m))
    local wide = cell == block_cell and math.max(1, rshift(w + 3, 2)) or w
    return {raw = raw, w = w, h = h, cell = cell, codec = codec, wide = wide, width = info.width, height = info.height,
            format = info.format, mips = info.mips}
end

-- Texel (x, y) of the sheet mip into one_texel (RGBA bytes), decoding its block when the format is compressed.
local one_texel = ffi.new('uint8_t[4]')
local function sheet_texel(s, x, y)
    if s.cell == block_cell then
        s.codec(s.raw, one_block, (rshift(y, 2) * s.wide + rshift(x, 2)) * BLOCK_BYTES[s.codec])
        local o = (band(y, 3) * 4 + band(x, 3)) * 4
        one_texel[0], one_texel[1], one_texel[2], one_texel[3] = one_block[o], one_block[o + 1], one_block[o + 2],
            one_block[o + 3]
    else
        s.cell(s.codec, s.raw, s.wide, x, y, one_texel, 0)
    end
    return one_texel
end

-- One layer over the grid (ROWS: the outside rows, Capes.zones's): its emblem {row, layer, L, a, b (its own color:
-- the blend-weighted mean of its sheet texels, display-linear), around ({[row] = bins}: the cloth under its cells,
-- blend >= EMBLEM_MIN, by tint bin), cells}, or nil when it shows on none. ctx: {sheet, tint, grad, colour}. The sums
-- go in grid order (research/capes.py emblem_analysis).
-- Grid cell i (column x, its row's center v) under layer l into acc ({tr, tg, tb, weight, cells, counts}): its sheet
-- texel's color by its blend, and the cloth's tint bin when the blend reaches EMBLEM_MIN.
local function emblem_cell(l, ctx, acc, x, i, v)
    local su, sv, inside = layer_point(l, (x + 0.5) / Capes.GRID, v)
    if not inside then return end
    local s, lin = ctx.sheet, ctx.colour.srgb_to_linear
    local tx = math.min(math.max(math.floor(su * s.w), 0), s.w - 1)
    local ty = math.min(math.max(math.floor(sv * s.h), 0), s.h - 1)
    local t = sheet_texel(s, tx, ty)
    local blend = l.strength * t[3] / 255.0
    if blend <= 0.0 then return end
    acc.tr = acc.tr + blend * lin(t[0] / 255)
    acc.tg = acc.tg + blend * lin(t[1] / 255)
    acc.tb = acc.tb + blend * lin(t[2] / 255)
    acc.weight = acc.weight + blend
    if blend < Capes.EMBLEM_MIN then return end
    acc.cells = acc.cells + 1
    local steps = (ctx.tint and ctx.grad) and tint_steps(ctx.tint, l.row, ctx.grad[i * 4]) or 0
    local bin = math.min(math.floor(steps / (Capes.TINT_STEPS / Capes.ZONE_BINS)), Capes.ZONE_BINS - 1)
    acc.counts[bin] = acc.counts[bin] + 1
end

local function emblem_of(l, ctx)
    local g = Capes.GRID
    local acc = {tr = 0.0, tg = 0.0, tb = 0.0, weight = 0.0, cells = 0, counts = zero_bins()}
    for y = 0, g - 1 do
        local v = (y + 0.5) / g
        for x = 0, g - 1 do
            local i = y * g + x
            if ROWS[i] == l.row then emblem_cell(l, ctx, acc, x, i, v) end
        end
        if ctx.yield then ctx.yield() end
    end
    if acc.cells == 0 then return nil end
    local L, a, b = ctx.colour.linear_to_lab(acc.tr / acc.weight, acc.tg / acc.weight, acc.tb / acc.weight)
    return {row = l.row, layer = l.layer, L = L, a = a, b = b, around = {[l.row] = acc.counts}, cells = acc.cells,
            rect = sheet_rect(l, ctx.sheet.width, ctx.sheet.height)}
end

-- The cape's emblems that show (emblem_of), row then layer order, each with the sheet's name and size; {} when it has
-- none or its sheet is not readable here. tint: the cape LUT ({values, width, height}), height: the material LUT's.
local function emblems_of(piece, tint, grad, height, deps)
    local found = {}
    for r = 0, math.min(tint.height, height) - 1 do
        for k = 0, 3 do found[#found + 1] = layer_of(tint, r, k) end
    end
    if #found == 0 then return {} end
    local sheet = sheet_mip(piece.decal, deps)
    if not sheet then return {} end
    local ctx = {sheet = sheet, tint = tint, grad = grad, colour = deps.Colour, yield = deps.yield}
    local out = {}
    for _, l in ipairs(found) do
        local e = emblem_of(l, ctx)
        if e then
            e.sheet, e.sheet_width, e.sheet_height, e.sheet_format = piece.decal, sheet.width, sheet.height, sheet.format
            e.sheet_mips = sheet.mips
            out[#out + 1] = e
        end
    end
    return out
end

-- 0-255 RGB of a BC color endpoint (16 bits, 5-6-5), expanded by bit replication as the decoders do.
local function endpoint_rgb(v)
    local r, g, b = band(rshift(v, 11), 31), band(rshift(v, 5), 63), band(v, 31)
    return r * 8 + rshift(r, 2), g * 4 + rshift(g, 4), b * 8 + rshift(b, 2)
end

-- The nearest endpoint to 0-1 sRGB.
local function to565(r, g, b)
    local function q(x, top) return math.min(math.max(math.floor(x * top + 0.5), 0), top) end
    return q(r, 31) * 2048 + q(g, 63) * 32 + q(b, 31)
end

-- An endpoint moved by shift ({dL, da, db}: the emblem's new color minus its own), clipped to sRGB.
local function recolor_endpoint(v, shift, Colour)
    local r, g, b = endpoint_rgb(v)
    local L, a, bb = Colour.srgb_to_lab(r / 255, g / 255, b / 255)
    return to565(Colour.lab_to_srgb(L + shift[1], a + shift[2], bb + shift[3]))
end

-- The color endpoints of blocks x0..x1-1, y0..y1-1 of one mip (bw blocks per row, from byte `offset`) moved by
-- ctx.shift (ctx: {data, shift, memo, Colour, yield}); an endpoint is recolored once (memo); yield after every 4 block
-- rows (about 500 blocks).
local function recolor_blocks(ctx, offset, bw, x0, y0, x1, y1)
    local data, memo = ctx.data, ctx.memo
    for by = y0, y1 - 1 do
        for bx = x0, x1 - 1 do
            local at = offset + (by * bw + bx) * 16 + 8
            for k = 0, 2, 2 do
                local v = data[at + k] + data[at + k + 1] * 256
                local new = memo[v] or recolor_endpoint(v, ctx.shift, ctx.Colour)
                memo[v] = new
                data[at + k], data[at + k + 1] = band(new, 255), rshift(new, 8)
            end
        end
        if ctx.yield and (by - y0) % 4 == 3 then ctx.yield() end
    end
end

-- A BC3 sheet's mip chain (data: uint8_t pointer, DDS order; sheet: {width, height, mips}) with every color block
-- that overlaps cell.rect ({x0, y0, x1, y1}: mip-0 texels, half-open) moved by cell.shift at every mip, in place: the
-- two color endpoints of each block (bytes 8-11), its color indices and its alpha block kept, so the emblem keeps its
-- shape, edges and shading (research/capes.py recolor_sheet). yield (optional): recolor_blocks'.
function Capes.recolor_sheet(data, sheet, cell, Colour, yield)
    local ctx = {data = data, shift = cell.shift, memo = {}, Colour = Colour, yield = yield}
    local rect, offset = cell.rect, 0
    for m = 0, sheet.mips - 1 do
        local mw, mh = math.max(1, rshift(sheet.width, m)), math.max(1, rshift(sheet.height, m))
        local bw, bh = math.max(1, rshift(mw + 3, 2)), math.max(1, rshift(mh + 3, 2))
        local rx0, ry0 = rshift(rect[1], m), rshift(rect[2], m)
        local x1 = math.min(math.floor((math.max(rshift(rect[3], m), rx0 + 1) + 3) / 4), bw)
        local y1 = math.min(math.floor((math.max(rshift(rect[4], m), ry0 + 1) + 3) / 4), bh)
        recolor_blocks(ctx, offset, bw, math.floor(rx0 / 4), math.floor(ry0 / 4), x1, y1)
        offset = offset + bw * bh * 16
    end
end

-- A cape kit's analysis, as Kits.analyse gives one for a helmet or an armor: {kit, body, pieces (the cape piece,
-- slot 1), luts (its material LUT, and its cape LUT when a tint shows), rows (the material rows in row order, then the
-- tint rows, with area), tint_of ({[cape LUT] = material LUT} when a tint shows), zones (Capes.zones, or nil),
-- emblems (emblems_of), patterns = {}, tint_note (why no tint was modelled, or nil)}; nil and why when its material
-- LUT is not in the searched archives. deps: Kits.analyse's (textures, find, colour, scratch, yield) and Texture,
-- Kits, Colour (the module: the emblems' color math).
local cells_buffer, grad_buffer -- GRID x GRID x 4 bytes each, reused by every analysis (jobs run one at a time)

-- Texture `name` sampled on the grid into out (Capes.cells, out cleared first); nil when it is not in the searched
-- archives.
local function sample(name, deps, out)
    local Texture = deps.Texture
    local archive, record, info = texture_info(name, deps)
    if not archive then return nil end
    ffi.fill(out, Capes.GRID * Capes.GRID * 4)
    return Capes.cells(Texture, Texture.pixels(deps.slim, archive, record, info), info, deps.big_scratch, out, deps.yield)
end

-- The cape LUT and the gradient's cells, and why no tint is modelled (either missing or unreadable), or nil.
local function tint_inputs(piece, deps)
    local none = deps.Kits.NO_LUT
    if not piece.cape_lut or piece.cape_lut == none then return nil, nil, nil end
    local ok, spec = pcall(deps.textures.lut, piece.cape_lut)
    if not ok then return nil, nil, 'cape LUT unreadable: ' .. tostring(spec) end
    if not spec then return nil, nil, 'cape LUT ' .. piece.cape_lut .. ' not found' end
    if not piece.gradient or piece.gradient == none then return spec, nil, nil end
    grad_buffer = grad_buffer or ffi.new('uint8_t[?]', Capes.GRID * Capes.GRID * 4)
    local done, grad = pcall(sample, piece.gradient, deps, grad_buffer)
    if not done then return spec, nil, 'gradient unreadable: ' .. tostring(grad) end
    if not grad then return spec, nil, 'gradient ' .. piece.gradient .. ' not found' end
    return spec, grad, nil
end

-- How many emblem-sheet layers (cape LUT columns 4-6, 7-9, 10-12, 13-15; column 6, 9, 12 or 15 y sets one) a row
-- that shows outside (areas, tints: Capes.areas's, rows 0-3) enables: their colors are the decal sheet's, never
-- recolored (diagnostics).
local function emblem_layers(tint, areas, tints)
    local count = 0
    for layer = 0, 3 do
        local column, found = 6 + 3 * layer, false
        for r = 0, math.min(tint.height, 4) - 1 do
            if ((areas[r] or 0) > 0 or (tints[r] or 0) > 0)
                and math.abs(tint.values[(r * tint.width + column) * 4 + 1]) > 0.001 then
                found = true
            end
        end
        if found then count = count + 1 end
    end
    return count
end

-- One analysis row: row r of spec ({values (float array), width}) under `key` with `area`.
local function row_entry(deps, key, lut_name, spec, r, area, emissive)
    local L, a, b, metal, camo, mode, full, ar, ag, ab = deps.colour.row_info(spec.values, spec.width, r)
    return {key = key, lut = lut_name, row = r, area = area, under = 0, L = L, a = a, b = b, metal = metal,
            camo = camo, mode = mode, full = full, ar = ar, ag = ag, ab = ab, emissive = emissive}
end

-- The tint rows (key '<cape LUT>:<row>'): material row r with column 0 RGB its cape LUT row's column 3 RGB, appended
-- to rows; true when any.
local function add_tint_rows(deps, rows, piece, lut, tint, tints)
    local copy, any = ffi.new('float[?]', lut.width * 4), false
    for r = 0, lut.height - 1 do
        if (tints[r] or 0) > 1e-6 then
            ffi.copy(copy, lut.values + r * lut.width * 4, lut.width * 16)
            local t = (r * tint.width + 3) * 4
            copy[0], copy[1], copy[2] = tint.values[t], tint.values[t + 1], tint.values[t + 2]
            rows[#rows + 1] = row_entry(deps, piece.cape_lut .. ':' .. r, piece.cape_lut,
                                        {values = copy, width = lut.width}, 0, tints[r], deps.Kits.emissive(lut, r))
            rows[#rows].row = r
            any = true
            deps.yield()
        end
    end
    return any
end

-- The material rows that show (areas: Capes.areas's), in row order.
local function material_rows(deps, piece, lut, areas)
    local rows = {}
    for r = 0, lut.height - 1 do
        if (areas[r] or 0) > 1e-6 then
            rows[#rows + 1] = row_entry(deps, piece.lut .. ':' .. r, piece.lut, lut, r, areas[r],
                                        deps.Kits.emissive(lut, r))
            deps.yield() -- a row's color work is up to about 0.5 ms outside the game, as in Kits.analyse
        end
    end
    return rows
end

function Capes.analyse(kit, body, deps)
    local Kits = deps.Kits
    local piece = kit.pieces[1]
    if not piece or piece.lut == Kits.NO_LUT then return nil, 'cape without a material LUT' end
    local lut = deps.textures.lut(piece.lut)
    if not lut then return nil, 'cape LUT ' .. piece.lut .. ' not found' end
    cells_buffer = cells_buffer or ffi.new('uint8_t[?]', Capes.GRID * Capes.GRID * 4)
    local cells = cells_buffer
    if not sample(piece.fields, deps, cells) then
        ffi.fill(cells, Capes.GRID * Capes.GRID * 4)
        for i = 0, Capes.GRID * Capes.GRID - 1 do cells[i * 4 + 3] = 255 end -- no fields: a plain cape
    end
    deps.yield()
    local tint, grad, note = tint_inputs(piece, deps)
    local areas, tints = Capes.areas(cells, lut.height, deps.yield, tint, grad)
    local rows = material_rows(deps, piece, lut, areas)
    local luts, tint_of = {[piece.lut] = lut}, nil
    if tint and grad and add_tint_rows(deps, rows, piece, lut, tint, tints) then
        luts[piece.cape_lut], tint_of = tint, {[piece.cape_lut] = piece.lut}
    end
    local zones = Capes.zones(cells, lut.height, tint, grad, deps.yield)
    local emblems = tint and emblems_of(piece, tint, grad, lut.height, deps) or {} -- after zones: ROWS
    local entry = {piece = {path = piece.path, slot = 1, type = 0, body = Kits.BODY_ANY, lut = piece.lut, tone = 0},
                   weight = 1.0, materials = {{material = 'cape', lut = piece.lut}}, skin = false}
    return {kit = kit, body = body, pieces = {entry}, luts = luts, rows = rows, patterns = {}, dropped = 0,
            tint_of = tint_of, zones = zones, emblems = emblems, tint_note = note,
            emblem_layers = tint and emblem_layers(tint, areas, tints) or 0}
end

-- Runs inside recolor jobs only: interpreted (no traces in the LuaJIT code cache every mod shares).
if type(jit) == 'table' and type(jit.off) == 'function' then
    for _, fn in ipairs({Capes.outline, expand565, alpha_palette, Capes.bc4_block, Capes.bc3_block, choose_mip,
                         plain_cell, block_cell, read_mip, grid_positions, reset_blocks, Capes.cells, tint_steps,
                         cell_rows, add_side, count_cell, count_rows, Capes.areas, outside_rows, zero_bins,
                         border_cell, count_border, zone_row, Capes.zones, layer_of, layer_point, sheet_rect,
                         texture_info, sheet_mip, sheet_texel, emblem_cell, emblem_of, emblems_of, endpoint_rgb, to565,
                         recolor_endpoint, recolor_blocks, Capes.recolor_sheet, sample, tint_inputs, emblem_layers,
                         row_entry, add_tint_rows, material_rows, Capes.analyse}) do
        jit.off(fn, true)
    end
end

return Capes
