"""Test and build Flame Damage Fixed.

Needs a Bingus Shared Loader checkout beside this repository (or its path in BINGUS_SHARED_LOADER) for
scripts/archive.py and scripts/build_addon.py, a LuaJIT (HD2_LUAJIT, default: the workspace build, else
`luajit` on PATH) and the installed game's bin/lua51.dll for the in-game runtime tests (tests/game_lua.py,
HD2_LUA51_DLL). tests/test_constants.py runs when both flame effects are extracted into data/ (README.md).
"""

from __future__ import annotations

import json
import os
from pathlib import Path
import shutil
import struct
import subprocess
import sys
import uuid
import zipfile

sys.dont_write_bytecode = True
HERE = Path(__file__).resolve().parents[1]
WORKSPACE = HERE.parent
LOADER = Path(os.environ.get('BINGUS_SHARED_LOADER', WORKSPACE / 'BingusSharedLoader'))
sys.path.insert(0, str(LOADER / 'scripts'))
from archive import ARCHIVE, make_archive, resource_hash  # noqa: E402
from build_addon import entry_source  # noqa: E402

VERSION = '1.2'
LUA_NAME = 'mods/cowboybingus/flame_damage_fixed'
GUID = '9ae59986-d77f-47d3-be47-77d50c564c30'
TITLE = 'Flame Damage Fixed v' + VERSION
DESCRIPTION = ("Fixes the Lumberer's flamethrower (and the Flame Sentry, which shares its flame): two flame "
               "parts that never spawned now do (they hit but are not drawn, so the flame still looks like one "
               "stream), the flame starts at the Cremator's distances, and it no longer burns the weapon that "
               "fires it while still hitting everything else. Steam build 25480438. Requires Bingus Shared "
               "Loader v18+.")
GAME_LUA = HERE / 'tests/game_lua.py'
EFFECTS = (HERE / 'data/shared_flame_e3d15622a42863c4.particles',
           HERE / 'data/cremator_flame_a4f17daba8ecd8e5.particles')
# Local copies that must stay byte-identical to the workspace's canonical ones (checked when present).
CANONICAL = {'tests/frame_budget.lua': 'PerformanceBaseline/frame_budget.lua',
             'tests/game_lua.py': 'PerformanceBaseline/game_lua.py',
             'tests/hostile_vm.lua': 'BingusSharedRuntime/hostile_vm.lua',
             'src/bingus_runtime.lua': 'BingusSharedRuntime/runtime/bingus_runtime.lua',
             'src/bingus_memory.lua': 'BingusSharedRuntime/runtime/bingus_memory.lua'}
# Vendored Bingus Shared Runtime files assembled ahead of the mod's own source, in order. The mod reads game
# memory through its own adapter, so it vendors the core and the read side, not bingus_write.lua.
RUNTIME_FILES = ('bingus_runtime.lua', 'bingus_memory.lua')
# Load orders of the FFI name clash test (tests/test_ffi_names.lua); each needs a fresh Lua state.
CLASH_MODES = ('sdk', 'hostile', 'reverse')
FORBIDDEN = ('VirtualProtect', 'VirtualAlloc', 'FlushInstructionCache', 'CreateRemoteThread', 'LoadLibrary')


def assemble() -> bytes:
    """One plaintext addon entry: the re-entry guard, the vendored runtime files, then the mod, which installs
    the runtime's update guard. The entry carries the loader's discovery declaration on its first line."""
    marker = '-- HD2-Addon: ' + LUA_NAME
    sources = {name: (HERE / 'src' / name).read_text(encoding='utf-8') for name in RUNTIME_FILES}
    mod = (HERE / 'src/flame_damage_fixed.lua').read_text(encoding='utf-8')
    if not mod.startswith(marker + '\n'):
        raise ValueError('flame_damage_fixed.lua must begin with its HD2-Addon declaration')
    mod = mod.split('\n', 1)[1]  # the entry carries the declaration once, on its own first line
    lines = [marker,
             '-- Flame Damage Fixed v%s for Steam build 25480438. Generated by scripts/build.py from %s; edit those.'
             % (VERSION, ', '.join('src/' + n for n in RUNTIME_FILES + ('flame_damage_fixed.lua',))),
             "if rawget(_G, 'FlameDamageFixedInstalled') then return end",
             'local bingus_runtime = (function()', sources['bingus_runtime.lua'].rstrip('\n'), 'end)()',
             'local bingus_memory = (function()', sources['bingus_memory.lua'].rstrip('\n'), 'end)()',
             'local Fix = (function()', mod.rstrip('\n'), 'end)()',
             'Fix.install(bingus_runtime, bingus_memory.new(bingus_runtime))']
    return ('\n'.join(lines) + '\n').encode('utf-8')


def luajit() -> Path:
    if 'HD2_LUAJIT' in os.environ:
        return Path(os.environ['HD2_LUAJIT'])
    workspace = WORKSPACE / 'tools/src/LuaJIT/src/luajit.exe'
    return workspace if workspace.exists() else Path(shutil.which('luajit') or workspace)


def run(args: list) -> str:
    result = subprocess.run([str(a) for a in args], capture_output=True, text=True, cwd=HERE)
    output = (result.stdout + result.stderr).strip()
    if result.returncode or 'PASS' not in output:
        raise RuntimeError(f'{args}: {output}')
    return [line for line in output.splitlines() if 'PASS' in line][0]


def test() -> list[str]:
    source = (HERE / 'src/flame_damage_fixed.lua').read_text(encoding='utf-8')
    for word in FORBIDDEN:
        if word in source:
            raise ValueError('Unexpected executable memory mutation: ' + word)
    for local, shared in CANONICAL.items():
        canonical = WORKSPACE / shared
        if canonical.exists() and canonical.read_bytes() != (HERE / local).read_bytes():
            raise ValueError(f'{local} differs from the canonical {shared}')
    if all(path.exists() for path in EFFECTS):
        results = [run([sys.executable, HERE / 'tests/test_constants.py'])]
    else:
        results = ['SKIP: tests/test_constants.py needs both flame effects extracted into data/ (README.md)']
    lua = luajit()
    for vm in ([lua], [sys.executable, GAME_LUA]):
        results.append(run(vm + [HERE / 'tests/test_fix.lua', HERE]))
        results.append(run(vm + [HERE / 'tests/test_fix_adapter.lua', HERE]))
        results.append(run(vm + [HERE / 'tests/test_guard_diff.lua', HERE]))
        for mode in CLASH_MODES:
            results.append(run(vm + [HERE / 'tests/test_ffi_names.lua', HERE, mode]))
    # The assembled entry (runtime + memory + mod) must compile as one LuaJIT chunk in both VMs.
    entry = HERE / 'build/entry-check.lua'
    entry.parent.mkdir(parents=True, exist_ok=True)
    entry.write_bytes(assemble())
    for vm in ([lua], [sys.executable, GAME_LUA]):
        results.append(run(vm + [HERE / 'tests/compile_entry.lua', entry]))
    return results


def build(output: Path) -> Path:
    body = entry_source(LUA_NAME, assemble())
    lua = struct.pack('<II', len(body), 2) + body
    option = {'Name': TITLE, 'Description': DESCRIPTION, 'Include': ['Addon']}
    manifest = {'Version': 1, 'Guid': str(uuid.UUID(GUID)), 'Name': TITLE, 'Description': DESCRIPTION,
                'Options': [option]}
    files = {'INSTALL.txt': (HERE / 'INSTALL.txt').read_bytes()}
    thumbnail = HERE / 'assets/thumbnail.png'
    if thumbnail.exists():
        files['thumbnail.png'] = thumbnail.read_bytes()
        manifest['IconPath'] = option['Image'] = 'thumbnail.png'
    files.update({
        'manifest.json': (json.dumps(manifest, indent=2) + '\n').encode(),
        'Addon/' + ARCHIVE: make_archive({resource_hash(LUA_NAME): lua}),
        'Addon/' + ARCHIVE + '.stream': b'',
        'Addon/' + ARCHIVE + '.gpu_resources': b'',
    })
    output.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(output, 'w', compression=zipfile.ZIP_DEFLATED) as archive:
        for path, payload in sorted(files.items()):
            info = zipfile.ZipInfo(path, date_time=(1980, 1, 1, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o100644 << 16
            archive.writestr(info, payload)
    return output


if __name__ == '__main__':
    for line in test():
        print(line)
    print(build(HERE / 'releases' / f'Flame-Damage-Fixed-v{VERSION}.zip'))
