"""Better Lobby Management's addon entry: src/ assembled into one plaintext Lua resource that carries the
loader's discovery declaration on its first line. Standard library only and no side effects on import, so
scripts/build.py and the Vanilla Plus Megapack build produce the same bytes from the same sources."""
from pathlib import Path

NAME = 'mods/cowboybingus/better_lobby_management'
EXE_SHA = 'F5FEE03DCFDB2E553A4752C283590950AC13316B376D8196AA556FF0400D5F06'
GAME_DLL_SHA = '2E2C3B7C2500646DADD5F2B4C6E0504DBB7E7896139F64CDDC0D1813C718F51E'
SOURCES = [('T', 'bingus_text.lua'), ('create_api', 'windows_api.lua'), ('G', 'game.lua'), ('L', 'lobby.lua'),
           ('R', 'region.lua'), ('M', 'menu.lua'), ('C', 'chat.lua'), ('S', 'scanner.lua'), ('B', 'sos.lua'),
           ('install', 'addon.lua')]
DIAG_SOURCES = SOURCES[:-1] + [('D', 'diag.lua'), SOURCES[-1]]
FORBIDDEN = (b'VirtualAlloc', b'VirtualProtect', b'FlushInstructionCache', b'CreateRemoteThread',
             b'LoadLibrary', b'jit.flush', b'jit.attach', b'jit.opt')


def locale_files(root):
    """locales/en.lua first, then each bundled translation (<tag>.lua)."""
    folder = Path(root) / 'locales'
    return [folder / 'en.lua'] + sorted(p for p in folder.glob('*.lua') if p.name != 'en.lua')


def read_lua(path):
    code = Path(path).read_bytes().decode('utf-8')
    if '\r' in code:
        raise ValueError(f'{Path(path).name} must use LF line endings')
    return code.rstrip('\n')


def entry_text(root, version, diag=False):
    """The entry for version (e.g. '1.0') from root/src and root/locales; diag: the test build with
    src/diag.lua."""
    sources = DIAG_SOURCES if diag else SOURCES
    locales = locale_files(root)
    lines = [f'-- HD2-Addon: {NAME}',
             f'-- Better Lobby Management v{version} for Steam build 25480438. Generated by scripts/build.py from '
             + ', '.join('src/' + name for _, name in sources) + ' and '
             + ', '.join('locales/' + path.name for path in locales) + '; edit those instead.']
    for variable, name in sources:
        lines += [f'local {variable} = (function()', read_lua(Path(root) / 'src' / name), 'end)()']
    # Locale files are data (return {...}); scripts/build.py checks them with translations.py first.
    lines.append('local locales = {bundled = {}}')
    for path in locales:
        target = 'locales.en' if path.name == 'en.lua' else f"locales.bundled['{path.stem}']"
        lines += [f'{target} = (function()', read_lua(path), 'end)()']
    lines.append(f"install(create_api, G, L, R, M, C, S, B, T, locales, {{version = 'v{version}', "
                 f"game_sha256 = '{GAME_DLL_SHA}', exe_sha256 = '{EXE_SHA}'"
                 + (", diag = true}, D)" if diag else "})"))
    text = ('\n'.join(lines) + '\n').encode('utf-8')
    for word in FORBIDDEN:
        if word in text:
            raise ValueError('Forbidden API in the addon: ' + word.decode())
    return text
