"""Better Lobby Management's addon entry: src/ assembled into one plaintext Lua resource that carries the
loader's discovery declaration on its first line. Standard library only and no side effects on import, so
scripts/build.py and the Vanilla Plus Megapack build produce the same bytes from the same sources."""
from pathlib import Path

NAME = 'mods/cowboybingus/better_lobby_management'
EXE_SHA = 'F5FEE03DCFDB2E553A4752C283590950AC13316B376D8196AA556FF0400D5F06'
GAME_DLL_SHA = '2E2C3B7C2500646DADD5F2B4C6E0504DBB7E7896139F64CDDC0D1813C718F51E'
SOURCES = [('create_api', 'windows_api.lua'), ('G', 'game.lua'), ('L', 'lobby.lua'), ('R', 'region.lua'),
           ('M', 'menu.lua'), ('C', 'chat.lua'), ('S', 'scanner.lua'), ('install', 'addon.lua')]
DIAG_SOURCES = SOURCES[:-1] + [('D', 'diag.lua'), SOURCES[-1]]
FORBIDDEN = (b'VirtualAlloc', b'VirtualProtect', b'FlushInstructionCache', b'CreateRemoteThread',
             b'LoadLibrary', b'jit.flush', b'jit.attach', b'jit.opt')


def entry_text(root, version, diag=False):
    """The entry for version (e.g. '1.0') from root/src; diag: the test build with src/diag.lua."""
    sources = DIAG_SOURCES if diag else SOURCES
    lines = [f'-- HD2-Addon: {NAME}',
             f'-- Better Lobby Management v{version} for Steam build 25480438. Generated by scripts/build.py from '
             + ', '.join('src/' + name for _, name in sources) + '; edit those instead.']
    for variable, name in sources:
        code = (Path(root) / 'src' / name).read_bytes().decode('utf-8')
        if '\r' in code:
            raise ValueError(f'src/{name} must use LF line endings')
        lines += [f'local {variable} = (function()', code.rstrip('\n'), 'end)()']
    lines.append(f"install(create_api, G, L, R, M, C, S, {{version = 'v{version}', game_sha256 = '{GAME_DLL_SHA}', "
                 f"exe_sha256 = '{EXE_SHA}'" + (", diag = true}, D)" if diag else "})"))
    text = ('\n'.join(lines) + '\n').encode('utf-8')
    for word in FORBIDDEN:
        if word in text:
            raise ValueError('Forbidden API in the addon: ' + word.decode())
    return text
