-- HD2-Addon: mods/cowboybingus/flame_damage_fixed
-- Flame Damage Fixed v1.0 for Helldivers 2 Steam build 25480438. Three data fixes to the flame shared by
-- the Lumberer's flamethrower arm and the Flame Sentry:
--   1. Flame systems 0 and 3 spawn again. Their spawn-rate curves are keyed on normalized effect time
--      (elapsed / effect lifetime) and step up at 0.3-0.9 % of it; the shared flame's lifetime is 1e10 s,
--      so they never spawned. Their step keys are rescaled to the Cremator's real timing (64 s lifetime).
--   2. The four main flame systems start at the Cremator's distances from the nozzle (1-4 m, not 7-15 m).
--   3. The flame no longer hits the Lumberer itself: its particle systems move from Havok collision layer
--      11 to layer 104, a copy of layer 11 without layer 20 (the Lumberer's hit-boxes, used by nothing else).
-- Damage, fuel, heat and fire values are untouched, and other flamethrowers keep their collision layer.
-- A second deployed copy (standalone and Vanilla Plus Megapack) does nothing.
if rawget(_G, 'FlameDamageFixedInstalled') then return end
local Fix = {}
local bit = require('bit')

local SPRAY_MANAGER_RVA = 0x3326bb0 -- game.dll: SprayWeaponComponent manager pointer
local RESOURCE_ROOT_RVA = 0x23621a8 -- helldivers2.exe: object whose +0x3f8 is the resource manager
-- Spray weapons that fire the shared flame (lo, hi): Lumberer flamethrower arm, Flame Sentry.
Fix.TRACKED = {{0xd6328726, 0x0736bee2}, {0xfe962858, 0x820cc3ba}}
local PARTICLES = {0x526fad64, 0xa8193123} -- resource type "particles"
local EFFECT = {0xa42863c4, 0xe3d15622}    -- shared Lumberer arm / Flame Sentry firing effect
local EFFECT_SIZE = 30896
local NOT_LOADED = 0xfafef0f1
local EMPTY_BUCKET, CHAIN_END = 0xfffffffe, 0x7fffffff
local SCAN_SECONDS = 0.5
local WATCH_SECONDS = 1.0 -- keep watching the flame's instances this long after the last firing frame
local MAX_SPRAYS, MAX_TRACKED, MAX_INSTANCES, MAX_SYSTEMS = 128, 8, 64, 32
Fix.EFFECT_SIZE = EFFECT_SIZE

-- First 0x60 bytes of the shipped effect as u32 words, and every system's (offset, size) in file order.
Fix.HEADER = {0x00000073, 0x501502f9, 0x501502f9, 0x5368d4a5, 0x00000023, 0x00000000, 0x0000000c, 0x00000000,
              0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
              0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000014, 0x0000000b, 0x00000044, 0x00000010}
Fix.SYSTEMS = {{80, 3600}, {3680, 2572}, {6252, 3084}, {9336, 2544}, {11880, 1256}, {13136, 3396},
               {16532, 2272}, {18804, 2472}, {21276, 3356}, {24632, 2628}, {27260, 2008}, {29268, 1628}}

-- Generated by scripts/patch_table.py (spawn: step keys * 64 s / 1e10 s; emitters: the Cremator's values).
Fix.PATCHES = {
    {o=252, v=0x41700000, t=0x40800000}, -- sys0+0xac emitters 15 -> 4
    {o=264, v=0x40a8bd3c, t=0x4060fc50}, -- sys0+0xb8 emitters 5.2731 -> 3.5154
    {o=1212, v=0x3c185f07, t=0x2e82e2c8}, -- sys0+0x46c spawn 0.0093 -> 5.952e-11
    {o=1216, v=0x3c185f07, t=0x2e82e2c8}, -- sys0+0x470 spawn 0.0093 -> 5.952e-11
    {o=1292, v=0x3c185f07, t=0x2e82e2c8}, -- sys0+0x4bc spawn 0.0093 -> 5.952e-11
    {o=1296, v=0x3c185f07, t=0x2e82e2c8}, -- sys0+0x4c0 spawn 0.0093 -> 5.952e-11
    {o=3852, v=0x41400000, t=0x40200000}, -- sys1+0xac emitters 12 -> 2.5
    {o=3864, v=0x418f23a3, t=0x41380903}, -- sys1+0xb8 emitters 17.8924 -> 11.5022
    {o=6424, v=0x40e00000, t=0x3f800000}, -- sys2+0xac emitters 7 -> 1
    {o=6436, v=0x4160eecc, t=0x4106f5a3}, -- sys2+0xb8 emitters 14.0583 -> 8.43497
    {o=9508, v=0x40e00000, t=0x40400000}, -- sys3+0xac emitters 7 -> 3
    {o=9520, v=0x40a70f28, t=0x4042e704}, -- sys3+0xb8 emitters 5.2206 -> 3.04535
    {o=10228, v=0x3bcb295f, t=0x2e2e83b6}, -- sys3+0x37c spawn 0.0062 -> 3.968e-11
    {o=10232, v=0x3b4b295f, t=0x2dae83b6}, -- sys3+0x380 spawn 0.0031 -> 1.984e-11
    {o=10308, v=0x3bcb295f, t=0x2e2e83b6}, -- sys3+0x3cc spawn 0.0062 -> 3.968e-11
    {o=10312, v=0x3b4b295f, t=0x2dae83b6}, -- sys3+0x3d0 spawn 0.0031 -> 1.984e-11
}

-- Havok (hknp) group-filter layers. Particle queries use the world's hknpGroupCollisionFilter: the row
-- of the query layer, the bit of the body layer. hknp copies a particle system's query filter info
-- (PS+5764) into every particle query (EXE 0xe3daf0), so moving it takes effect on the next step.
local PHYS = {
    FILTER_PTR = 0x27C5E40, FILTER_VTABLE = 0x148B938, MATRIX = 40,
    WORLDS = 0x27BA890, WORLD_STRIDE = 176, PS_TABLE = 32 + 1144, PS_ARRAY = 8, PS_FILTER = 5764,
    WORLD_PTR = 0x346BFA0, PARTICLE_MANAGER = 0x230888,
    FLAME_LAYER = 11, HULL_LAYER = 20, NEW_LAYER = 104,
}
Fix.PHYS = PHYS
-- Layer 11's row in the live matrix (the flame's collision filter 0x12d0abf1).
Fix.FLAME_ROW = {0, 2, 14, 17, 19, 20, 22, 27, 31, 39, 48, 54, 55, 59, 60, 63, 66, 77, 83, 86, 94, 100, 101}

local function le32(v)
    return string.char(v % 256, math.floor(v / 256) % 256, math.floor(v / 65536) % 256, math.floor(v / 16777216) % 256)
end
-- Byte strings for the writes are built once here, never per frame.
for _, row in ipairs(Fix.PATCHES) do row.tb = le32(row.t) end
local NEW_LAYER_BYTES = le32(PHYS.NEW_LAYER)

local function u32at(bytes, offset)
    local a, b, c, d = bytes:byte(offset + 1, offset + 4)
    return a + b * 256 + c * 65536 + d * 16777216
end

local function valid_address(value)
    return type(value) == 'number' and value >= 0x10000 and value < 0x800000000000
end

-- 64-bit words are read as two u32 halves: addresses (< 2^47) become exact Lua numbers and 64-bit
-- hashes are compared per half, so no cdata or string is created for them.
local function u64(api, address)
    local lo, hi = api.u32(address), api.u32(address + 4)
    if not lo or not hi then return nil end
    return lo + hi * 4294967296, lo, hi
end

local function pointer(api, address)
    local value = u64(api, address)
    if valid_address(value) then return value end
    return nil
end

-- Walks one of the engine's chained hash tables (bucket = hash_hi % buckets).
local function chain(api, entries, stride, next_offset, buckets, lo, hi, limit)
    if not valid_address(entries) or not buckets or buckets == 0 or buckets > 1048576 then return nil end
    local index = hi % buckets
    if api.u32(entries + index * stride + next_offset) == EMPTY_BUCKET then return nil end
    for _ = 1, limit do
        local base = entries + index * stride
        if api.u32(base) == lo and api.u32(base + 4) == hi then return base end
        index = api.u32(base + next_offset)
        if not index or index == CHAIN_END or index >= limit then return nil end
    end
    return nil
end

-- ===== 1 + 2: effect data =====

-- Returns the loaded shared effect's data address, or nil and a reason. Reads only.
function Fix.resolve_effect(api, exe)
    local root = pointer(api, exe + RESOURCE_ROOT_RVA)
    local manager = root and pointer(api, root + 0x3f8)
    if not manager then return nil, 'resource manager unavailable' end
    local types, type_count, type_buckets = pointer(api, manager + 0x2f0), api.u32(manager + 0x300), api.u32(manager + 0x304)
    if not type_count or type_count > 4096 then return nil, 'resource type table unavailable' end
    local entry = chain(api, types, 0xd0, 0xc8, type_buckets, PARTICLES[1], PARTICLES[2], type_buckets or 0)
    if not entry then return nil, 'particles type not registered' end
    local names, name_buckets = pointer(api, entry + 0x28), api.u32(entry + 0x3c)
    local slots = api.u32(entry + 0x20)
    if not slots or slots > 1048576 then return nil, 'particle name table unavailable' end
    local name = chain(api, names, 24, 0x10, name_buckets, EFFECT[1], EFFECT[2], slots)
    if not name then return nil, 'flame effect not loaded' end
    local value = api.u32(name + 8)
    if not value or value == NOT_LOADED or value > 1048576 then return nil, 'flame effect pending' end
    local records = pointer(api, entry + 0x10)
    local data = records and pointer(api, records + value * 160)
    local size = records and api.u32(records + value * 160 + 0x18)
    if not data or size ~= EFFECT_SIZE then return nil, 'unexpected effect record' end
    return data
end

-- Checks the loaded effect against the shipped header and layout, and every patched word against its
-- shipped or fixed value. Word reads only: nothing is allocated.
function Fix.check_effect(api, data)
    for i, word in ipairs(Fix.HEADER) do
        if api.u32(data + 4 * (i - 1)) ~= word then return false, 'effect header changed' end
    end
    for _, system in ipairs(Fix.SYSTEMS) do
        if api.u32(data + system[1] + 0x100) ~= system[2] then return false, 'effect layout changed' end
    end
    local pending = 0
    for _, row in ipairs(Fix.PATCHES) do
        local word = api.u32(data + row.o)
        if word ~= row.v and word ~= row.t then return false, 'unknown value at ' .. row.o end
        if word ~= row.t then pending = pending + 1 end
    end
    return true, pending
end

-- Writes the fixed value of every patched word that still holds the shipped one.
function Fix.apply_effect(api, data)
    local ok, pending = Fix.check_effect(api, data)
    if not ok then return false, pending end
    if pending == 0 then return true, 0 end
    if not api.writable_data(data, EFFECT_SIZE) then return false, 'effect memory not writable private data' end
    local writes = 0
    for _, row in ipairs(Fix.PATCHES) do
        if api.u32(data + row.o) ~= row.t then
            if not api.write_raw(data + row.o, row.tb) then return false, 'effect write failed at ' .. row.o end
            writes = writes + 1
        end
    end
    for _, row in ipairs(Fix.PATCHES) do
        if api.u32(data + row.o) ~= row.t then return false, 'effect verify failed at ' .. row.o end
    end
    return true, writes
end

-- ===== 3: self-hit layer =====

local function row_words(matrix, layer)
    local o = 16 * layer
    return {u32at(matrix, o), u32at(matrix, o + 4), u32at(matrix, o + 8), u32at(matrix, o + 12)}
end
local function words_of(layers)
    local w = {0, 0, 0, 0}
    for _, layer in ipairs(layers) do
        local i = math.floor(layer / 32) + 1
        w[i] = w[i] + 2 ^ (layer % 32)
    end
    return w
end
local function has_bit(words, layer)
    return math.floor(words[math.floor(layer / 32) + 1] / 2 ^ (layer % 32)) % 2 == 1
end
local NEW_ROW = {}
for _, layer in ipairs(Fix.FLAME_ROW) do
    if layer ~= PHYS.HULL_LAYER then NEW_ROW[#NEW_ROW + 1] = layer end
end
local NEW_ROW_WORDS = words_of(NEW_ROW)
Fix.NEW_ROW = NEW_ROW

-- Adds layer 104 = layer 11 without layer 20 (both directions). Returns the filter address, detail or
-- nil, reason. Once per session: one 2 KB read, one writable_data check, up to 25 word writes.
function Fix.ensure_layer(api, exe)
    local filter = pointer(api, exe + PHYS.FILTER_PTR)
    if not filter then return nil, 'collision filter unavailable' end
    if u64(api, filter) ~= exe + PHYS.FILTER_VTABLE then return nil, 'collision filter type changed' end
    local matrix = api.read(filter + PHYS.MATRIX, 128 * 16)
    if not matrix or #matrix ~= 2048 then return nil, 'collision matrix unreadable' end
    local flame, expected = row_words(matrix, PHYS.FLAME_LAYER), words_of(Fix.FLAME_ROW)
    for i = 1, 4 do
        if flame[i] ~= expected[i] then return nil, 'flame layer row changed' end
    end
    local current = row_words(matrix, PHYS.NEW_LAYER)
    local ready = true
    for i = 1, 4 do ready = ready and current[i] == NEW_ROW_WORDS[i] end
    for _, layer in ipairs(NEW_ROW) do ready = ready and has_bit(row_words(matrix, layer), PHYS.NEW_LAYER) end
    if ready then return filter, 'present' end
    -- Unused layer: only the default layer 0 may reference it.
    local empty = words_of({0})
    for i = 1, 4 do
        if current[i] ~= empty[i] and current[i] ~= NEW_ROW_WORDS[i] then return nil, 'layer 104 in use' end
    end
    local writes = {}
    for i = 1, 4 do
        if current[i] ~= NEW_ROW_WORDS[i] then writes[#writes + 1] = {16 * PHYS.NEW_LAYER + 4 * (i - 1), NEW_ROW_WORDS[i]} end
    end
    local word, mask = math.floor(PHYS.NEW_LAYER / 32), 2 ^ (PHYS.NEW_LAYER % 32)
    for _, layer in ipairs(NEW_ROW) do
        local words = row_words(matrix, layer)
        if not has_bit(words, PHYS.NEW_LAYER) then writes[#writes + 1] = {16 * layer + 4 * word, words[word + 1] + mask} end
    end
    if not api.writable_data(filter + PHYS.MATRIX, 2048) then return nil, 'collision matrix not writable private data' end
    for _, item in ipairs(writes) do
        if not api.write_raw(filter + PHYS.MATRIX + item[1], le32(item[2])) then return nil, 'matrix write failed' end
    end
    for i = 1, 4 do
        if api.u32(filter + PHYS.MATRIX + 16 * PHYS.NEW_LAYER + 4 * (i - 1)) ~= NEW_ROW_WORDS[i] then
            return nil, 'matrix verify failed'
        end
    end
    return filter, #writes .. ' matrix words'
end

-- True while layer 104's first word still holds the added row (one read; the layer is session state).
function Fix.layer_present(api, filter)
    return api.u32(filter + PHYS.MATRIX + 16 * PHYS.NEW_LAYER) == NEW_ROW_WORDS[1]
end

-- Address of the shared flame's instance list entry {count u32, records ptr} in the particle manager,
-- or nil when no instance of it exists. The entry moves when the effect is unregistered, so it is
-- looked up again at every burst start.
function Fix.flame_slot(api, game)
    local world = pointer(api, game + PHYS.WORLD_PTR)
    local manager = world and pointer(api, world + PHYS.PARTICLE_MANAGER)
    if not manager then return nil end
    local entries, count, buckets = pointer(api, manager + 0x1b8), api.u32(manager + 0x1c8), api.u32(manager + 0x1cc)
    if not entries or not count or count == 0 or count > 65536 or not buckets or buckets == 0 or buckets > 1048576 then
        return nil
    end
    local index, value = EFFECT[2] % buckets, nil
    if api.u32(entries + 24 * index + 0x10) == EMPTY_BUCKET then return nil end
    for _ = 1, count + 1 do
        local base = entries + 24 * index
        if api.u32(base) == EFFECT[1] and api.u32(base + 4) == EFFECT[2] then value = api.u32(base + 8) break end
        index = api.u32(base + 0x10)
        if not index or index == CHAIN_END then return nil end
    end
    local mask, lists = api.u32(manager + 0x228), pointer(api, manager + 0x278)
    if not value or not mask or not lists then return nil end
    return lists + 24 * (bit.band(value, mask) % 4294967296)
end

-- Moves one flame instance's particle systems from layer 11 to 104. `region` carries the last verified
-- writable heap region ({base, limit}) so particle systems in one region share one query. Returns the
-- number of systems moved, or nil and a reason.
function Fix.retarget_instance(api, exe, sim, data, region)
    if pointer(api, sim + 32) ~= data then return 0 end -- another effect's instance
    local systems, list = api.u32(sim + 40), pointer(api, sim + 48)
    if not systems or not list or systems > MAX_SYSTEMS then return 0 end
    local moved = 0
    for s = 0, systems - 1 do
        local handle = api.u32(list + 80 * s + 52)
        if handle and handle ~= 0 then
            local index, generation, w = handle % 65536, math.floor(handle / 65536) % 256, math.floor(handle / 1073741824)
            local wrapper = pointer(api, exe + PHYS.WORLDS + PHYS.WORLD_STRIDE * w)
            local tbl = wrapper and pointer(api, wrapper + PHYS.PS_TABLE)
            local array = tbl and pointer(api, tbl + PHYS.PS_ARRAY)
            local ps = array and pointer(api, array + 16 * index)
            local tag = array and api.u32(array + 16 * index + 8)
            if ps and tag and tag % 65536 == index and math.floor(tag / 16777216) == generation
                and api.u32(ps + PHYS.PS_FILTER) == PHYS.FLAME_LAYER then
                local target = ps + PHYS.PS_FILTER
                if not (region[1] and target >= region[1] and target + 4 <= region[2]) then
                    local base, size = api.writable_region(target)
                    if not base then return nil, 'particle system not writable private data' end
                    region[1], region[2] = base, base + size
                end
                if not api.write_raw(target, NEW_LAYER_BYTES) then return nil, 'particle system write failed' end
                moved = moved + 1
            end
        end
    end
    return moved
end

-- ===== per-frame driver =====

-- log(line) receives one line per notable event (fix applied, refusals), never per frame.
function Fix.new(api, game, exe, log)
    local self = {clock = 0, since_scan = SCAN_SECONDS, tracked = {}, last = {}, watch_until = nil,
                  slot = nil, data = nil, filter = nil, layer_off = nil, seen_count = -1, seen_records = 0,
                  seen_sims = {}, region = {}, moved = 0, told = {}}
    log = log or function() end
    local function tell(key, line)
        if not self.told[key] then self.told[key] = true; log(line) end
    end

    -- Tracked spray weapons (Lumberer arms, Flame Sentries) by their instance's state word. Every
    -- SCAN_SECONDS of game time; per-weapon last states survive the rescan. Two state tables take
    -- turns, so a scan allocates nothing.
    local spare = {}
    function self.scan()
        self.since_scan = 0
        local tracked, previous, last = self.tracked, self.last, spare
        for key in pairs(last) do last[key] = nil end
        for i = #tracked, 1, -1 do tracked[i] = nil end
        local manager = pointer(api, game + SPRAY_MANAGER_RVA)
        local count = manager and api.u32(manager + 0x38)
        if count and count > 0 and count <= MAX_SPRAYS then
            local entities, instances = pointer(api, manager + 0x60), pointer(api, manager + 0x70)
            if entities and instances then
                for index = 0, count - 1 do
                    local entity = pointer(api, entities + 8 * index)
                    local lo = entity and api.u32(entity)
                    if lo == Fix.TRACKED[1][1] or lo == Fix.TRACKED[2][1] then
                        local hi = api.u32(entity + 4)
                        if hi == Fix.TRACKED[1][2] or hi == Fix.TRACKED[2][2] then
                            local weapon = instances + 0x218 * index
                            tracked[#tracked + 1] = weapon
                            last[weapon] = previous[weapon]
                            if #tracked == MAX_TRACKED then break end
                        end
                    end
                end
            end
        end
        spare, self.last = previous, last
    end

    function self.burst_start()
        local data, why = Fix.resolve_effect(api, exe)
        self.data = data
        if not data then
            tell('effect:' .. why, 'Flame effect not fixed: ' .. why)
        elseif not (self.patched == data and api.u32(data + Fix.PATCHES[1].o) == Fix.PATCHES[1].t) then
            local ok, detail = Fix.apply_effect(api, data)
            if ok then
                self.patched = data
                if detail > 0 then log('Flame effect fixed (' .. detail .. ' words).') end
            else
                tell('effect:' .. tostring(detail), 'Flame effect not fixed: ' .. tostring(detail))
            end
        end
        if not self.layer_off then
            if not (self.filter and Fix.layer_present(api, self.filter)) then
                local filter, detail = Fix.ensure_layer(api, exe)
                if filter then
                    self.filter = filter
                    if detail ~= 'present' then log('Self-hit collision layer added (' .. detail .. ').') end
                else
                    self.layer_off = detail
                    log('Self-hit fix disabled for this session: ' .. tostring(detail))
                end
            end
        end
        self.slot = Fix.flame_slot(api, game)
        self.seen_count = -1
    end

    -- Firing frames: moves any new flame instance to the self-hit layer. A burst's instance can appear
    -- frames after the state change, so this second check runs while firing and briefly after.
    function self.watch()
        if self.layer_off or not self.filter or not self.data then return end
        local slot = self.slot or Fix.flame_slot(api, game)
        self.slot = slot
        if not slot then return end
        local count, records = api.u32(slot), pointer(api, slot + 8)
        if not count or not records or count > MAX_INSTANCES then return end
        local changed = count ~= self.seen_count or records ~= self.seen_records
        local sims = self.seen_sims
        for i = 1, count do
            local sim = pointer(api, records + 136 * (i - 1) + 8) or 0
            if sims[i] ~= sim then sims[i] = sim; changed = true end
        end
        if not changed then return end
        self.seen_count, self.seen_records = count, records
        local region = self.region
        region[1], region[2] = nil, nil
        for i = 1, count do
            if sims[i] ~= 0 then
                local moved, why = Fix.retarget_instance(api, exe, sims[i], self.data, region)
                if not moved then
                    self.layer_off = why
                    log('Self-hit fix disabled for this session: ' .. tostring(why))
                    return
                end
                self.moved = self.moved + moved
                if moved > 0 then tell('moved', 'Self-hit fix active (' .. moved .. ' flame particle systems moved).') end
            end
        end
    end

    function self.step(dt)
        self.clock = self.clock + dt
        self.since_scan = self.since_scan + dt
        if self.since_scan >= SCAN_SECONDS then self.scan() end
        local tracked, last = self.tracked, self.last
        local firing, started = false, false
        for i = 1, #tracked do
            local weapon = tracked[i]
            local state = api.u32(weapon)
            local previous = last[weapon]
            last[weapon] = state
            if state == 1 or state == 2 then
                firing = true
                if previous ~= 1 and previous ~= 2 then started = true end
            end
        end
        if started then self.burst_start() end
        if firing then self.watch_until = self.clock + WATCH_SECONDS end
        if self.watch_until then
            if self.clock <= self.watch_until then self.watch() else self.watch_until = nil end
        end
    end
    return self
end

-- Bingus Shared Loader v18+ with API 1. The loader's own version field is not its release number (the v18
-- release reports 17), so v18 is recognized by the `jit` state it added.
function Fix.loader_ok(loader)
    return type(loader) == 'table' and loader.api == 1 and type(loader.open_log) == 'function'
        and type(loader.jit) == 'table'
end

if rawget(_G, 'FLAME_DAMAGE_FIXED_TEST') then return Fix end

-- ===== In-game adapter =====
local GAME_SHA256 = '2E2C3B7C2500646DADD5F2B4C6E0504DBB7E7896139F64CDDC0D1813C718F51E'
local EXE_SHA256 = 'F5FEE03DCFDB2E553A4752C283590950AC13316B376D8196AA556FF0400D5F06'
local ffi = require('ffi')
-- Same prototypes as the other Bingus mods; each is guarded so an identical earlier declaration is fine.
for _, declaration in ipairs({
    'void *GetModuleHandleA(const char *name);',
    'uint32_t GetModuleFileNameW(void *module, uint16_t *path, uint32_t capacity);',
    'void *GetCurrentProcess(void);',
    'int ReadProcessMemory(void *process, const void *address, void *buffer, size_t size, size_t *read);',
    'int WriteProcessMemory(void *process, void *address, const void *buffer, size_t size, size_t *written);',
    'size_t VirtualQuery(const void *address, void *region, size_t size);',
    'void *CreateFileW(const uint16_t *path, uint32_t access, uint32_t share, void *security, uint32_t disposition, uint32_t flags, void *template_file);',
    'int ReadFile(void *file, void *buffer, uint32_t size, uint32_t *read, void *overlapped);',
    'int CloseHandle(void *handle);',
    'int32_t BCryptOpenAlgorithmProvider(void **algorithm, const uint16_t *name, const uint16_t *provider, uint32_t flags);',
    'int32_t BCryptCloseAlgorithmProvider(void *algorithm, uint32_t flags);',
    'int32_t BCryptCreateHash(void *algorithm, void **hash, void *object, uint32_t object_size, const void *secret, uint32_t secret_size, uint32_t flags);',
    'int32_t BCryptHashData(void *hash, const void *data, uint32_t size, uint32_t flags);',
    'int32_t BCryptFinishHash(void *hash, void *digest, uint32_t size, uint32_t flags);',
    'int32_t BCryptDestroyHash(void *hash);',
}) do pcall(ffi.cdef, declaration) end
-- Named once (function-pointer type strings would create a new C type on every load). No 64-bit value
-- is ever read back into Lua: interpreted code boxes each one as a cdata, so SIZE_T results and counts
-- are read as uint32 halves. VirtualQuery's SIZE_T result (0 or 48) is taken from its low half.
if not pcall(ffi.typeof, 'FlameDamageFixedRegion') then
    ffi.cdef([[
typedef struct { uintptr_t base, allocation; uint32_t allocation_protect; uint32_t partition; size_t size; uint32_t state, protection, type; } FlameDamageFixedRegion;
typedef int (*FlameDamageFixedReadMemory)(void *, uintptr_t, void *, size_t, uint32_t *);
typedef int (*FlameDamageFixedWriteMemory)(void *, uintptr_t, const void *, size_t, uint32_t *);
typedef uint32_t (*FlameDamageFixedQueryMemory)(uintptr_t, FlameDamageFixedRegion *, size_t);
]])
end
local kernel, bcrypt = ffi.load('kernel32'), ffi.load('bcrypt')
local process = kernel.GetCurrentProcess()
-- One-time casts: numeric addresses go straight in, results land in reused buffers.
local read_memory = ffi.cast('FlameDamageFixedReadMemory', kernel.ReadProcessMemory)
local write_memory = ffi.cast('FlameDamageFixedWriteMemory', kernel.WriteProcessMemory)
local query_memory = ffi.cast('FlameDamageFixedQueryMemory', kernel.VirtualQuery)
local word, count = ffi.new('uint32_t[1]'), ffi.new('uint32_t[2]') -- count: SIZE_T as two halves
local BULK_SIZE = 2048
local bulk = ffi.new('uint8_t[?]', BULK_SIZE)
local region = ffi.new('FlameDamageFixedRegion[1]')
local REGION_SIZE = ffi.sizeof('FlameDamageFixedRegion')
-- The region as uint32 words (written only by VirtualQuery): base 0-1, size 6-7, state 8, protect 9, type 10.
local region_words = ffi.cast('uint32_t *', region)

local api = {}
function api.u32(address)
    if read_memory(process, address, word, 4, count) == 0 or count[0] ~= 4 or count[1] ~= 0 then return nil end
    return word[0]
end
-- Bulk read (once per session: the 2 KB collision matrix).
function api.read(address, size)
    if size < 1 or size > BULK_SIZE then return nil end
    if read_memory(process, address, bulk, size, count) == 0 or count[0] ~= size or count[1] ~= 0 then return nil end
    return ffi.string(bulk, size)
end
local function private_rw(address)
    if query_memory(address, region, REGION_SIZE) == 0 then return nil end
    local w = region_words
    if w[8] ~= 0x1000 or w[10] ~= 0x20000 or w[9] ~= 4 then return nil end
    return w[0] + w[1] * 4294967296, w[6] + w[7] * 4294967296
end
-- Committed, private, read-write data only: never executable, image-mapped or read-only pages.
function api.writable_data(address, size)
    local cursor, remaining = address, size
    while remaining > 0 do
        local base, span = private_rw(cursor)
        if not base then return false end
        local available = base + span - cursor
        if available <= 0 then return false end
        local step = math.min(available, remaining)
        cursor, remaining = cursor + step, remaining - step
    end
    return true
end
-- The committed private read-write region holding address: base, size (one VirtualQuery) or nil.
function api.writable_region(address)
    return private_rw(address)
end
-- Caller must have passed api.writable_data or api.writable_region for the target in the same frame.
function api.write_raw(address, bytes)
    return write_memory(process, address, bytes, #bytes, count) ~= 0 and count[0] == #bytes and count[1] == 0
end
if rawget(_G, 'FLAME_DAMAGE_FIXED_ADAPTER_TEST') then return api end

local function module_hash(module)
    local path = ffi.new('uint16_t[32768]')
    local length = kernel.GetModuleFileNameW(module, path, 32768)
    assert(length > 0 and length < 32768, 'Cannot resolve module file')
    local file = kernel.CreateFileW(path, 0x80000000, 7, nil, 3, 0x08000000, nil)
    assert(file ~= ffi.cast('void *', -1), 'Cannot read module file')
    local algorithm, hash = ffi.new('void *[1]'), ffi.new('void *[1]')
    local ok, result = pcall(function()
        local name = ffi.new('uint16_t[7]', {83, 72, 65, 50, 53, 54, 0})
        assert(bcrypt.BCryptOpenAlgorithmProvider(algorithm, name, nil, 0) == 0, 'SHA256 unavailable')
        assert(bcrypt.BCryptCreateHash(algorithm[0], hash, nil, 0, nil, 0, 0) == 0, 'SHA256 creation failed')
        local buffer, got = ffi.new('uint8_t[1048576]'), ffi.new('uint32_t[1]')
        while true do
            assert(kernel.ReadFile(file, buffer, 1048576, got, nil) ~= 0, 'Module file read failed')
            if got[0] == 0 then break end
            assert(bcrypt.BCryptHashData(hash[0], buffer, got[0], 0) == 0, 'SHA256 update failed')
        end
        local digest, hex = ffi.new('uint8_t[32]'), {}
        assert(bcrypt.BCryptFinishHash(hash[0], digest, 32, 0) == 0, 'SHA256 finish failed')
        for i = 0, 31 do hex[#hex + 1] = string.format('%02X', digest[i]) end
        return table.concat(hex)
    end)
    if hash[0] ~= nil then bcrypt.BCryptDestroyHash(hash[0]) end
    if algorithm[0] ~= nil then bcrypt.BCryptCloseAlgorithmProvider(algorithm[0], 0) end
    kernel.CloseHandle(file)
    if not ok then error(result) end
    return result
end

local loader = rawget(_G, 'CowboyBingusModLoader')
local log_file
if loader and type(loader.open_log) == 'function' then
    pcall(function() log_file = loader.open_log('FlameDamageFixed.log') end)
end
local function note(line)
    print('[FlameDamageFixed] ' .. line)
    if log_file then pcall(function() log_file:write(line .. '\n'); log_file:flush() end) end
end

local ready, fix = pcall(function()
    assert(Fix.loader_ok(loader), 'Bingus Shared Loader v18+ / API 1 required')
    local game, exe = kernel.GetModuleHandleA('game.dll'), kernel.GetModuleHandleA(nil)
    assert(game ~= nil and exe ~= nil, 'Game modules unavailable')
    assert(module_hash(game) == GAME_SHA256 and module_hash(exe) == EXE_SHA256, 'Unsupported game build (needs 25480438)')
    return Fix.new(api, tonumber(ffi.cast('uintptr_t', game)), tonumber(ffi.cast('uintptr_t', exe)), note)
end)
if not ready then
    note('Disabled: ' .. tostring(fix))
    return
end

local previous_update = rawget(_G, 'update')
local traceback, errors = debug.traceback, 0
local step = fix.step
update = function(dt)
    if errors < 8 then
        -- xpcall passes dt on (LuaJIT extension), so no closure is built per frame.
        local ok, err = xpcall(step, traceback, dt)
        if not ok then
            errors = errors + 1
            note('Update error ' .. errors .. ': ' .. tostring(err))
        end
    end
    if type(previous_update) == 'function' then return previous_update(dt) end
end
_G.FlameDamageFixedInstalled = true
note('Flame Damage Fixed v1.0 initialized (spawn fix, Cremator emitter distances, self-hit layer).')
