-- HD2-Addon: mods/cowboybingus/flame_damage_fixed
-- Flame Damage Fixed v1.2 for Helldivers 2 Steam build 25480438. Three fixes to the flame shared by the
-- Lumberer's flamethrower arm and the Flame Sentry:
--   1. Flame systems 0 and 3 spawn again. Their spawn-rate curves are keyed on normalized effect time
--      (elapsed / effect lifetime) and step up at 0.3-0.9 % of it; the shared flame's lifetime is 1e10 s,
--      so they never spawned. Their step keys are rescaled to the Cremator's real timing (64 s lifetime).
--   2. The four main flame systems start at the Cremator's distances from the nozzle (1-4 m, not 7-15 m).
--      Systems 0 and 3 are not drawn (visualizer count 1 -> 0, like the game's invisible carrier system): they
--      hit, but the flame looks like one stream, not a second wide cone at the nozzle.
--   3. The flame no longer hits the weapon that fires it. From its first burst until it is gone, the weapon's own
--      hit-boxes (the Lumberer's hull, arm and cannon; the Flame Sentry) share a private Havok system group with
--      that weapon's flame particle systems, and members of that group skip each other. Every other body, from
--      Chargers to teammates, keeps its vanilla collision with the flame: no collision layer is changed.
-- Damage, fuel, heat and fire values are untouched, and other flamethrowers are not affected.
-- A second deployed copy (standalone and Vanilla Plus Megapack) does nothing.
if rawget(_G, 'FlameDamageFixedInstalled') then return end
local Fix = {}
local bit = require('bit')

local SPRAY_MANAGER_RVA = 0x3326bb0 -- game.dll: SprayWeaponComponent manager pointer
local RESOURCE_ROOT_RVA = 0x23621a8 -- helldivers2.exe: object whose +0x3f8 is the resource manager
-- Spray weapons that fire the shared flame (lo, hi): Lumberer flamethrower arm, Flame Sentry.
Fix.TRACKED = {{0xd6328726, 0x0736bee2}, {0xfe962858, 0x820cc3ba}}
local PARTICLES = {0x526fad64, 0xa8193123} -- resource type "particles"
local EFFECT = {0xa42863c4, 0xe3d15622}    -- shared Lumberer arm / Flame Sentry firing effect
local EFFECT_SIZE = 30896
local NOT_LOADED = 0xfafef0f1
local EMPTY_BUCKET, CHAIN_END = 0xfffffffe, 0x7fffffff
local SCAN_SECONDS = 0.5
local WATCH_SECONDS = 1.0 -- keep looking for a burst's flame instance this long after the last firing frame
local RETRY_SECONDS = 5.0 -- a failed family lookup is tried again after this long
local MAX_SPRAYS, MAX_TRACKED, MAX_INSTANCES, MAX_SYSTEMS = 128, 8, 64, 32
local MAX_FAMILY, MAX_BODIES, SCAN_BLOCKS = 16, 64, 4
Fix.EFFECT_SIZE = EFFECT_SIZE

-- First 0x60 bytes of the shipped effect as u32 words, and every system's (offset, size) in file order.
Fix.HEADER = {0x00000073, 0x501502f9, 0x501502f9, 0x5368d4a5, 0x00000023, 0x00000000, 0x0000000c, 0x00000000,
              0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
              0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000014, 0x0000000b, 0x00000044, 0x00000010}
Fix.SYSTEMS = {{80, 3600}, {3680, 2572}, {6252, 3084}, {9336, 2544}, {11880, 1256}, {13136, 3396},
               {16532, 2272}, {18804, 2472}, {21276, 3356}, {24632, 2628}, {27260, 2008}, {29268, 1628}}

-- Generated by scripts/patch_table.py (spawn: step keys * 64 s / 1e10 s; emitters: the Cremator's values;
-- hide: the restored systems 0 and 3 are not drawn, their visualizer count goes from 1 to 0).
Fix.PATCHES = {
    {o=252, v=0x41700000, t=0x40800000}, -- sys0+0xac emitters 15 -> 4
    {o=264, v=0x40a8bd3c, t=0x4060fc50}, -- sys0+0xb8 emitters 5.2731 -> 3.5154
    {o=328, v=0x00000001, t=0x00000000}, -- sys0+0xf8 hide 1 -> 0
    {o=1212, v=0x3c185f07, t=0x2e82e2c8}, -- sys0+0x46c spawn 0.0093 -> 5.952e-11
    {o=1216, v=0x3c185f07, t=0x2e82e2c8}, -- sys0+0x470 spawn 0.0093 -> 5.952e-11
    {o=1292, v=0x3c185f07, t=0x2e82e2c8}, -- sys0+0x4bc spawn 0.0093 -> 5.952e-11
    {o=1296, v=0x3c185f07, t=0x2e82e2c8}, -- sys0+0x4c0 spawn 0.0093 -> 5.952e-11
    {o=3852, v=0x41400000, t=0x40200000}, -- sys1+0xac emitters 12 -> 2.5
    {o=3864, v=0x418f23a3, t=0x41380903}, -- sys1+0xb8 emitters 17.8924 -> 11.5022
    {o=6424, v=0x40e00000, t=0x3f800000}, -- sys2+0xac emitters 7 -> 1
    {o=6436, v=0x4160eecc, t=0x4106f5a3}, -- sys2+0xb8 emitters 14.0583 -> 8.43497
    {o=9508, v=0x40e00000, t=0x40400000}, -- sys3+0xac emitters 7 -> 3
    {o=9520, v=0x40a70f28, t=0x4042e704}, -- sys3+0xb8 emitters 5.2206 -> 3.04535
    {o=9584, v=0x00000001, t=0x00000000}, -- sys3+0xf8 hide 1 -> 0
    {o=10228, v=0x3bcb295f, t=0x2e2e83b6}, -- sys3+0x37c spawn 0.0062 -> 3.968e-11
    {o=10232, v=0x3b4b295f, t=0x2dae83b6}, -- sys3+0x380 spawn 0.0031 -> 1.984e-11
    {o=10308, v=0x3bcb295f, t=0x2e2e83b6}, -- sys3+0x3cc spawn 0.0062 -> 3.968e-11
    {o=10312, v=0x3b4b295f, t=0x2dae83b6}, -- sys3+0x3d0 spawn 0.0031 -> 1.984e-11
}

-- Havok (hknp) filter info: layer (bits 0-6) | subsystem (7-13) | don't-collide subsystem (14-20) | system
-- group (21-31). The world's hknpGroupCollisionFilter (query check EXE 0xce6030) decides by the layer matrix
-- unless both sides are in the same non-zero group; then only the subsystems decide, and two members whose
-- subsystem and don't-collide are both 0 never collide. Particle queries run the particle filter's own checks,
-- then this one (EXE 0xe66f60), with the particle system's filter info (PS+5764, copied per query).
local PHYS = {
    FILTER_PTR = 0x27C5E40, FILTER_VTABLE = 0x148B938, MATRIX = 40,
    WORLDS = 0x27BA890, WORLD_STRIDE = 176, WORLD_VTABLE = 0x14B3148,
    PS_TABLE = 32 + 1144, PS_ARRAY = 8, PS_FILTER = 5764,
    WORLD_PTR = 0x346BFA0, PARTICLE_MANAGER = 0x230888, INSTANCE = 136, INSTANCE_ID = 0x10,
    BODIES = 0x38, BODY_LIMIT = 0x50, BODY = 160,
    UNITS = 0x1A100F0, UNIT_OBJECTS = 0x88, UNIT_HANDLE = 0x8, UNIT_PARENT = 0x1D0, UNIT_CHILD = 0x1D8,
    UNIT_SIBLING = 0x1E0, UNIT_RESOURCE = 0x358,
    GROUPS = 0x27C5B88, GROUP_TOP = 2047, GROUP_LOW = 2040,
    SPRAY_INSTANCE = 0x24,
    FLAME_LAYER = 11,
}
Fix.PHYS = PHYS
-- Layer 11's row in the live matrix (the flame's collision filter 0x12d0abf1): the layers the flame can hit.
Fix.FLAME_ROW = {0, 2, 14, 17, 19, 20, 22, 27, 31, 39, 48, 54, 55, 59, 60, 63, 66, 77, 83, 86, 94, 100, 101}
Fix.AVATAR = {0x294dfa97, 0x4d1c334d} -- avatar_helldiver unit resource (lo, hi): a seated pilot stays out

local function le32(v)
    return string.char(v % 256, math.floor(v / 256) % 256, math.floor(v / 65536) % 256, math.floor(v / 16777216) % 256)
end
-- Byte strings for the writes are built once here, never per frame.
for _, row in ipairs(Fix.PATCHES) do row.tb = le32(row.t) end

-- Keeps rarely-run functions out of the JIT: jit.off on each listed function only, when the mod loads (before any of
-- them has a trace). No other function is affected and no JIT setting changes. Straight-line code that runs on a few
-- frames (a burst start, grouping, a release, the weapon scan every 0.5 s) would otherwise compile into the LuaJIT
-- code cache the game and every mod share, mostly inlined into side traces of the per-frame step, and it runs as fast
-- interpreted. The body scan's loop over every body record stays compiled: there the JIT pays. Measured in the game's
-- lua51.dll with the real adapter (synthetic world of 37,000 bodies, 30 bursts, a rescan, a release; the step called
-- from C, as the game calls update): machine code 80.9 KB with everything compiled -> 35.3 KB (median of 10 fresh
-- processes; 20.9 KB with the scan loop interpreted too). Per frame, everything compiled -> this split (test process,
-- median of 15 interleaved runs): body-scan frame 25.7 -> 25.8 us (91.0 with the scan loop interpreted), burst start
-- 48.7 -> 48.9 us, release 219.5 -> 162.7 us, the 0.5 s weapon scan 11.9 -> 17.5 us. In game, unmeasured.
local function interpreted(list)
    if type(jit) ~= 'table' or type(jit.off) ~= 'function' then return end
    for i = 1, #list do jit.off(list[i]) end
end

local function u32at(bytes, offset)
    local a, b, c, d = bytes:byte(offset + 1, offset + 4)
    return a + b * 256 + c * 65536 + d * 16777216
end

local function valid_address(value)
    return type(value) == 'number' and value >= 0x10000 and value < 0x800000000000
end

-- 64-bit words are read as two u32 halves: addresses (< 2^47) become exact Lua numbers and 64-bit
-- hashes are compared per half, so no cdata or string is created for them.
local function u64(api, address)
    local lo, hi = api.u32(address), api.u32(address + 4)
    if not lo or not hi then return nil end
    return lo + hi * 4294967296, lo, hi
end

local function pointer(api, address)
    local value = u64(api, address)
    if valid_address(value) then return value end
    return nil
end

-- Walks one of the engine's chained hash tables (bucket = hash_hi % buckets).
local function chain(api, entries, stride, next_offset, buckets, lo, hi, limit)
    if not valid_address(entries) or not buckets or buckets == 0 or buckets > 1048576 then return nil end
    local index = hi % buckets
    if api.u32(entries + index * stride + next_offset) == EMPTY_BUCKET then return nil end
    for _ = 1, limit do
        local base = entries + index * stride
        if api.u32(base) == lo and api.u32(base + 4) == hi then return base end
        index = api.u32(base + next_offset)
        if not index or index == CHAIN_END or index >= limit then return nil end
    end
    return nil
end

-- ===== 1 + 2: effect data =====

-- Returns the loaded shared effect's data address, or nil and a reason. Reads only.
function Fix.resolve_effect(api, exe)
    local root = pointer(api, exe + RESOURCE_ROOT_RVA)
    local manager = root and pointer(api, root + 0x3f8)
    if not manager then return nil, 'resource manager unavailable' end
    local types, type_count, type_buckets = pointer(api, manager + 0x2f0), api.u32(manager + 0x300), api.u32(manager + 0x304)
    if not type_count or type_count > 4096 then return nil, 'resource type table unavailable' end
    local entry = chain(api, types, 0xd0, 0xc8, type_buckets, PARTICLES[1], PARTICLES[2], type_buckets or 0)
    if not entry then return nil, 'particles type not registered' end
    local names, name_buckets = pointer(api, entry + 0x28), api.u32(entry + 0x3c)
    local slots = api.u32(entry + 0x20)
    if not slots or slots > 1048576 then return nil, 'particle name table unavailable' end
    local name = chain(api, names, 24, 0x10, name_buckets, EFFECT[1], EFFECT[2], slots)
    if not name then return nil, 'flame effect not loaded' end
    local value = api.u32(name + 8)
    if not value or value == NOT_LOADED or value > 1048576 then return nil, 'flame effect pending' end
    local records = pointer(api, entry + 0x10)
    local data = records and pointer(api, records + value * 160)
    local size = records and api.u32(records + value * 160 + 0x18)
    if not data or size ~= EFFECT_SIZE then return nil, 'unexpected effect record' end
    return data
end

-- Checks the loaded effect against the shipped header and layout, and every patched word against its
-- shipped or fixed value. Word reads only: nothing is allocated.
function Fix.check_effect(api, data)
    for i, word in ipairs(Fix.HEADER) do
        if api.u32(data + 4 * (i - 1)) ~= word then return false, 'effect header changed' end
    end
    for _, system in ipairs(Fix.SYSTEMS) do
        if api.u32(data + system[1] + 0x100) ~= system[2] then return false, 'effect layout changed' end
    end
    local pending = 0
    for _, row in ipairs(Fix.PATCHES) do
        local word = api.u32(data + row.o)
        if word ~= row.v and word ~= row.t then return false, 'unknown value at ' .. row.o end
        if word ~= row.t then pending = pending + 1 end
    end
    return true, pending
end

-- Writes the fixed value of every patched word that still holds the shipped one.
function Fix.apply_effect(api, data)
    local ok, pending = Fix.check_effect(api, data)
    if not ok then return false, pending end
    if pending == 0 then return true, 0 end
    if not api.writable_data(data, EFFECT_SIZE) then return false, 'effect memory not writable private data' end
    local writes = 0
    for _, row in ipairs(Fix.PATCHES) do
        if api.u32(data + row.o) ~= row.t then
            if not api.write_raw(data + row.o, row.tb) then return false, 'effect write failed at ' .. row.o end
            writes = writes + 1
        end
    end
    for _, row in ipairs(Fix.PATCHES) do
        if api.u32(data + row.o) ~= row.t then return false, 'effect verify failed at ' .. row.o end
    end
    return true, writes
end

-- ===== 3: self-hit fix (private Havok system groups) =====

-- Each tracked weapon takes a group from the top of the 2048-group pool (2047 down to 2040) that the game's
-- allocator still marks free. The game hands groups out lowest first, to ragdolls only (at most 144 were in use,
-- highest 154, in busy missions); the engine treats every allocator-claimed group as a ragdoll group, so a mod
-- must never claim one for other bodies (a claimed group 159 crashed the game, exe+0x16c768, 2026-10-04). The mod
-- never writes the allocator: a group counts as this weapon's only while the allocator still marks it free, no
-- other weapon of this mod holds it, and the weapon's latest body scan found no other body in it, checked at
-- every use. README.md states the convention for other mods.
local GROUP_UNIT = 2097152 -- 2^21: group 1 in a filter info
local TOP_FILTER = PHYS.GROUP_LOW * GROUP_UNIT -- a filter info at or above this is in one of groups 2040-2047
local BLOCK_BODIES = 409   -- bodies per read (65440 B)
local SPAN_GAP = 64        -- kept bodies closer than this many records share one read
local W_FLAGS, W_FILTER, W_ID, W_ACTOR, W_UNIT = 17, 27, 28, 36, 37 -- u32 words of a 160 B body record
local HITTABLE = {}
for _, layer in ipairs(Fix.FLAME_ROW) do HITTABLE[layer] = true end

local function words_of(layers)
    local w = {0, 0, 0, 0}
    for _, layer in ipairs(layers) do
        local i = math.floor(layer / 32) + 1
        w[i] = w[i] + 2 ^ (layer % 32)
    end
    return w
end
local FLAME_WORDS = words_of(Fix.FLAME_ROW)

-- The world's collision filter must be the known hknpGroupCollisionFilter with layer 11's recorded row
-- (the kept bodies are the ones this row can hit). Once per session: 8 reads. Returns the filter or nil, reason.
function Fix.check_filter(api, exe)
    local filter = pointer(api, exe + PHYS.FILTER_PTR)
    if not filter then return nil, 'collision filter unavailable' end
    if u64(api, filter) ~= exe + PHYS.FILTER_VTABLE then return nil, 'collision filter type changed' end
    for i = 1, 4 do
        if api.u32(filter + PHYS.MATRIX + 16 * PHYS.FLAME_LAYER + 4 * (i - 1)) ~= FLAME_WORDS[i] then
            return nil, 'flame layer row changed'
        end
    end
    return filter
end

-- The weapon's family: its parent unit (the Lumberer hull) or itself when it has none, and every descendant
-- (first-child / next-sibling links) except avatar subtrees, so a seated pilot is never included. Unit handles
-- go to out[1..n] (and out.set); returns n, or nil and a reason. Reads only.
function Fix.family(api, exe, handle, out, stack)
    local registry = pointer(api, exe + PHYS.UNITS)
    local objects = registry and pointer(api, registry + PHYS.UNIT_OBJECTS)
    if not objects then return nil, 'unit registry unavailable' end
    local unit = pointer(api, objects + 8 * (handle % 4194304))
    if not unit or api.u32(unit + PHYS.UNIT_HANDLE) ~= handle then return nil, 'weapon unit not found' end
    local set = out.set
    for key in pairs(set) do set[key] = nil end
    local n, depth = 0, 1
    stack[1] = pointer(api, unit + PHYS.UNIT_PARENT) or unit
    while depth > 0 do
        local node = stack[depth]
        depth = depth - 1
        if not (api.u32(node + PHYS.UNIT_RESOURCE) == Fix.AVATAR[1] and api.u32(node + PHYS.UNIT_RESOURCE + 4) == Fix.AVATAR[2]) then
            local own = api.u32(node + PHYS.UNIT_HANDLE)
            if not own then return nil, 'unit unreadable' end
            n = n + 1
            if n > MAX_FAMILY then return nil, 'family too large' end
            out[n], set[own] = own, true
            local child = pointer(api, node + PHYS.UNIT_CHILD)
            while child do
                depth = depth + 1
                if depth > MAX_FAMILY then return nil, 'family too large' end
                stack[depth] = child
                child = pointer(api, child + PHYS.UNIT_SIBLING)
            end
        end
    end
    for i = n + 1, #out do out[i] = nil end
    return n
end

-- Starts a body scan for a family: every physics world's body array up to its index bound. Reads only.
function Fix.scan_begin(api, exe, job)
    job.worlds, job.w, job.i, job.n, job.done, job.spans = 0, 1, 0, 0, false, 0
    job.foreign = job.foreign or {}
    for g = PHYS.GROUP_LOW, PHYS.GROUP_TOP do job.foreign[g] = false end
    for w = 0, 3 do
        local world = pointer(api, exe + PHYS.WORLDS + PHYS.WORLD_STRIDE * w)
        if world and u64(api, world) == exe + PHYS.WORLD_VTABLE then
            local bodies, size, limit = pointer(api, world + PHYS.BODIES), api.u32(world + PHYS.BODIES + 8),
                api.u32(world + PHYS.BODY_LIMIT)
            if bodies and size and limit and limit <= size and size <= 1048576 then
                job.worlds = job.worlds + 1
                job.bases[job.worlds], job.limits[job.worlds] = bodies, limit
            end
        end
    end
    if job.worlds == 0 then return nil, 'no physics world' end
    return true
end

-- Groups the kept bodies (in scan order) into spans that one read covers: same body array, at most
-- BLOCK_BODIES records, gaps under SPAN_GAP. Span s covers kept bodies span_k[s] .. span_k[s + 1] - 1.
local function build_spans(job)
    local s = 0
    for k = 1, job.n do
        local first = s > 0 and job.index[job.span_k[s]] or nil
        if s == 0 or job.span_base[s] ~= job.base[k] or job.index[k] - job.index[k - 1] > SPAN_GAP
            or job.index[k] - first + 1 > BLOCK_BODIES then
            s = s + 1
            job.span_k[s], job.span_base[s] = k, job.base[k]
        end
    end
    job.span_k[s + 1], job.spans = job.n + 1, s
end

local function not_own() return false end

-- A live body of interest at record o (its filter info is a flame-hittable layer alone, or in groups 2040-2047).
-- Keeps one of the family's bodies (job.set) the flame can hit whose subsystem and don't-collide are 0 (bits the
-- game may use are never touched), in no group or in the weapon's own group job.g (kept as marked). Notes a group
-- from 2040 up that any other body carries in job.foreign, unless job.own(group, unit) says it is another of this
-- mod's weapons' own. Returns a reason when the family has too many bodies.
local function scan_body(job, words, o, base, index, filter)
    local unit = words[o + W_UNIT]
    local mine = job.set[unit]
    local group, low = math.floor(filter / GROUP_UNIT), filter % GROUP_UNIT
    if mine and low < 128 and HITTABLE[low] and (group == 0 or group == job.g) then
        local n = job.n + 1
        if n > MAX_BODIES then return 'too many own bodies' end
        job.n, job.base[n], job.index[n], job.layer[n] = n, base, index, low
        job.actor[n], job.unit[n], job.marked[n] = words[o + W_ACTOR], unit, group ~= 0
    elseif group >= PHYS.GROUP_LOW and not (mine and group == job.g) and not job.own(group, unit) then
        job.foreign[group] = true
    end
    return nil
end

-- One block of body records. Every body the scan keeps or notes has a filter info in groups 2040-2047, or a
-- flame-hittable layer alone (no group, subsystem 0, don't-collide 0) and a unit of the family. The filter word is
-- read first, the unit only for a hittable layer, and the rest for those bodies only: one or two words per record.
local function scan_block(job, words, base, first, count)
    local set = job.set
    for k = 0, count - 1 do
        local o = 40 * k
        local filter = words[o + W_FILTER]
        if filter >= TOP_FILTER or HITTABLE[filter] and set[words[o + W_UNIT]] then
            if words[o + W_FLAGS] % 4 ~= 0 and words[o + W_ID] % 16777216 == first + k then
                local why = scan_body(job, words, o, base, first + k, filter)
                if why then return why end
            end
        end
    end
    return nil
end

-- Advances a body scan by up to `blocks` block reads: keeps the family's own bodies (set: its unit handles; g: the
-- weapon's group, if any) and notes which of groups 2040-2047 other bodies carry (own(group, unit): true for the
-- bodies of this mod's other weapons). Returns true when the scan is complete, false while it continues, or nil and
-- a reason.
function Fix.scan_step(api, job, set, blocks, g, own)
    job.set, job.g, job.own = set, g or 0, own or not_own
    while blocks > 0 and job.w <= job.worlds do
        local base, limit, first = job.bases[job.w], job.limits[job.w], job.i
        if first >= limit then
            job.w, job.i = job.w + 1, 0
        else
            local count = math.min(BLOCK_BODIES, limit - first)
            local words = api.load(base + PHYS.BODY * first, PHYS.BODY * count)
            if not words then return nil, 'body array unreadable' end
            blocks = blocks - 1
            local why = scan_block(job, words, base, first, count)
            if why then return nil, why end
            job.i = first + count
        end
    end
    job.done = job.w > job.worlds
    if job.done then build_spans(job) end
    return job.done
end

-- region = {base, limit} of the last committed private read-write region checked in this frame.
local function writable(api, region, target)
    if region[1] and target >= region[1] and target + 4 <= region[2] then return true end
    local base, size = api.writable_region(target)
    if not base then return false end
    region[1], region[2] = base, base + size
    return true
end

-- Walks the kept bodies span by span (one read per span) and classifies each against group g:
--   'own'    grouped (g) on the layer the scan saw          'free'    still group-free: to be grouped
--   'moved'  grouped (g) on another layer (the game switched it, as on destruction)
--   'stale'  no longer the body the scan kept (rebuilt, removed or recycled)
-- visit(k, class, words, offset) is called per body; returns false if a span could not be read.
local function each_body(api, job, g, visit)
    for s = 1, job.spans do
        local k0, k1 = job.span_k[s], job.span_k[s + 1] - 1
        local first = job.index[k0]
        local words = api.load(job.span_base[s] + PHYS.BODY * first, PHYS.BODY * (job.index[k1] - first + 1))
        if not words then return false end
        for k = k0, k1 do
            local o = 40 * (job.index[k] - first)
            local class
            if words[o + W_ID] % 16777216 ~= job.index[k] or words[o + W_ACTOR] ~= job.actor[k]
                or words[o + W_UNIT] ~= job.unit[k] or words[o + W_FLAGS] % 4 == 0 then
                class = 'stale'
            else
                local filter = words[o + W_FILTER]
                local group, low = math.floor(filter / GROUP_UNIT), filter % GROUP_UNIT
                if g and group == g and low < 128 then
                    class = low == job.layer[k] and 'own' or 'moved'
                elseif filter < 128 and HITTABLE[filter] then
                    class = 'free'
                else
                    class = 'stale' -- the game gave it another group or layer bits: leave it alone
                end
            end
            visit(k, class, words, o)
        end
    end
    return true
end

-- Summary of the kept bodies for group g: counts per class (reads only, one read per span).
local counts = {own = 0, free = 0, moved = 0, stale = 0}
local function tally(k, class) counts[class] = counts[class] + 1 end
function Fix.verify(api, job, g)
    counts.own, counts.free, counts.moved, counts.stale = 0, 0, 0, 0
    if not each_body(api, job, g, tally) then return nil, 'body array unreadable' end
    return counts
end

-- Puts the kept bodies that are still theirs and group-free into group g (only bits 21-31 change). Returns
-- how many carry g afterwards, or nil and a reason.
local mark_state = {api = nil, g = 0, region = nil, marked = 0, failed = nil}
local function mark_one(k, class, words, o)
    local st = mark_state
    if st.failed then return end
    local job = st.job
    job.marked[k] = false
    if class == 'free' then
        local target = job.base[k] + PHYS.BODY * job.index[k] + 4 * W_FILTER
        if not writable(st.api, st.region, target) then st.failed = 'body memory not writable private data' return end
        if not st.api.write_u32(target, words[o + W_FILTER] + st.g * GROUP_UNIT) then st.failed = 'body write failed' return end
        job.marked[k], st.marked = true, st.marked + 1
    elseif class == 'own' then
        job.marked[k], st.marked = true, st.marked + 1
    end
end
function Fix.mark(api, job, g, region)
    region[1], region[2] = nil, nil
    local st = mark_state
    st.api, st.job, st.g, st.region, st.marked, st.failed = api, job, g, region, 0, nil
    if not each_body(api, job, g, mark_one) then return nil, 'body array unreadable' end
    if st.failed then return nil, st.failed end
    return st.marked
end

-- Clears group g from every kept body that still belongs to its unit (same index and unit; the actor may have
-- been rebuilt) and still carries g, whatever its layer. Returns the number cleared, or nil and a reason.
local function unmark_one(k, class, words, o)
    local st = mark_state
    if st.failed then return end
    local job = st.job
    job.marked[k] = false
    local filter = words[o + W_FILTER]
    if words[o + W_ID] % 16777216 == job.index[k] and words[o + W_UNIT] == job.unit[k]
        and math.floor(filter / GROUP_UNIT) == st.g then
        local target = job.base[k] + PHYS.BODY * job.index[k] + 4 * W_FILTER
        if not writable(st.api, st.region, target) then st.failed = 'body memory not writable private data' return end
        if not st.api.write_u32(target, filter - st.g * GROUP_UNIT) then st.failed = 'body write failed' return end
        st.marked = st.marked + 1
    end
end
function Fix.unmark(api, job, g, region)
    region[1], region[2] = nil, nil
    local st = mark_state
    st.api, st.job, st.g, st.region, st.marked, st.failed = api, job, g, region, 0, nil
    if not each_body(api, job, g, unmark_one) then return nil, 'body array unreadable' end
    if st.failed then return nil, st.failed end
    return st.marked
end

-- True when the game's system-group allocator still marks group g free (its bitmap bit set). 7 reads.
function Fix.group_free(api, exe, g)
    local allocator = pointer(api, exe + PHYS.GROUPS)
    if not allocator then return false end
    local capacity, words, bitmap = api.u32(allocator), api.u32(allocator + 4), pointer(api, allocator + 8)
    if capacity ~= PHYS.GROUP_TOP + 1 or not words or words < 1 or words > 64 or not bitmap then return false end
    local word = api.u32(bitmap + 8 * words + 8 * math.floor(g / 64) + 4 * math.floor((g % 64) / 32))
    return word ~= nil and math.floor(word / 2 ^ (g % 32)) % 2 == 1
end

-- Address of the shared flame's instance list entry {count u32, records ptr} in the particle manager,
-- or nil when no instance of it exists. The entry moves when the effect is unregistered, so it is
-- looked up again at every burst start.
function Fix.flame_slot(api, game)
    local world = pointer(api, game + PHYS.WORLD_PTR)
    local manager = world and pointer(api, world + PHYS.PARTICLE_MANAGER)
    if not manager then return nil end
    local entries, count, buckets = pointer(api, manager + 0x1b8), api.u32(manager + 0x1c8), api.u32(manager + 0x1cc)
    if not entries or not count or count == 0 or count > 65536 or not buckets or buckets == 0 or buckets > 1048576 then
        return nil
    end
    local index, value = EFFECT[2] % buckets, nil
    if api.u32(entries + 24 * index + 0x10) == EMPTY_BUCKET then return nil end
    for _ = 1, count + 1 do
        local base = entries + 24 * index
        if api.u32(base) == EFFECT[1] and api.u32(base + 4) == EFFECT[2] then value = api.u32(base + 8) break end
        index = api.u32(base + 0x10)
        if not index or index == CHAIN_END then return nil end
    end
    local mask, lists = api.u32(manager + 0x228), pointer(api, manager + 0x278)
    if not value or not mask or not lists then return nil end
    return lists + 24 * (bit.band(value, mask) % 4294967296)
end

-- Record address of the flame instance with this id (instance record +0x10) in the flame slot, or nil.
function Fix.find_instance(api, slot, id)
    local count, records = api.u32(slot), pointer(api, slot + 8)
    if not count or not records or count > MAX_INSTANCES then return nil end
    for i = 0, count - 1 do
        local record = records + PHYS.INSTANCE * i
        if api.u32(record + PHYS.INSTANCE_ID) == id then return record end
    end
    return nil
end

-- The particle system a system handle names (world: bits 30-31, generation: 16-23, index: 0-15) while the world's
-- particle-system array still holds that generation at that index, else nil. cache keeps the last world's array.
local function system_of(api, exe, handle, cache)
    local index, generation, w = handle % 65536, math.floor(handle / 65536) % 256, math.floor(handle / 1073741824)
    if w ~= cache.world then
        local wrapper = pointer(api, exe + PHYS.WORLDS + PHYS.WORLD_STRIDE * w)
        local tbl = wrapper and pointer(api, wrapper + PHYS.PS_TABLE)
        cache.world, cache.array = w, tbl and pointer(api, tbl + PHYS.PS_ARRAY)
    end
    local array = cache.array
    if not array then return nil end
    local ps, tag = pointer(api, array + 16 * index), api.u32(array + 16 * index + 8)
    if ps and tag and tag % 65536 == index and math.floor(tag / 16777216) == generation then return ps end
    return nil
end

-- Sets the query filter info of one flame instance's particle systems that hold `from` (default: layer 11) to
-- `value` (layer 11 in the weapon's group, or back). The world's particle-system array is looked up once per
-- instance. `region` carries the last verified writable heap region. Returns the number of systems changed, or nil
-- and a reason.
local system_cache = {}
function Fix.retarget_instance(api, exe, sim, data, region, value, from)
    if pointer(api, sim + 32) ~= data then return 0 end -- another effect's instance
    local systems, list = api.u32(sim + 40), pointer(api, sim + 48)
    if not systems or not list or systems > MAX_SYSTEMS then return 0 end
    from = from or PHYS.FLAME_LAYER
    system_cache.world, system_cache.array = nil, nil
    local moved = 0
    for s = 0, systems - 1 do
        local handle = api.u32(list + 80 * s + 52)
        local ps = handle and handle ~= 0 and system_of(api, exe, handle, system_cache)
        if ps and api.u32(ps + PHYS.PS_FILTER) == from then
            if not writable(api, region, ps + PHYS.PS_FILTER) then return nil, 'particle system not writable private data' end
            if not api.write_u32(ps + PHYS.PS_FILTER, value) then return nil, 'particle system write failed' end
            moved = moved + 1
        end
    end
    return moved
end

-- Every live instance of the shared flame (the flame slot's records): systems that hold `from` get `value`.
-- Returns the number of systems changed, or nil and a reason.
function Fix.restore_flames(api, exe, slot, data, region, value, from)
    local count, records = api.u32(slot), pointer(api, slot + 8)
    if not count or not records or count > MAX_INSTANCES then return 0 end
    local changed = 0
    for i = 0, count - 1 do
        local sim = pointer(api, records + PHYS.INSTANCE * i + 8)
        if sim then
            local moved, why = Fix.retarget_instance(api, exe, sim, data, region, value, from)
            if not moved then return nil, why end
            changed = changed + moved
        end
    end
    return changed
end

-- Rarely run: effect lookup and fix (burst starts), filter check (once per session), the family walk and the start and
-- end of a body scan (once per family), grouping, release and flame instances (burst starts and releases). The body
-- scan's loop (Fix.scan_step, scan_block, scan_body) stays compiled.
interpreted({chain, Fix.resolve_effect, Fix.check_effect, Fix.apply_effect, Fix.check_filter, Fix.family,
             Fix.scan_begin, build_spans, writable, each_body, tally, Fix.verify, mark_one, Fix.mark, unmark_one,
             Fix.unmark, Fix.group_free, Fix.flame_slot, Fix.find_instance, system_of, Fix.retarget_instance,
             Fix.restore_flames})

-- ===== per-frame driver =====

local WEAPON_NAMES = {[0x0736bee2] = 'Lumberer', [0x820cc3ba] = 'Flame Sentry'}

-- log(line) receives one line per notable event (fix applied, refusals), never per frame.
function Fix.new(api, game, exe, log)
    local self = {clock = 0, since_scan = SCAN_SECONDS, tracked = {}, last = {}, weapons = {}, watch_until = nil,
                  slot = nil, data = nil, filter = nil, self_hit_off = nil, region = {}, told = {},
                  scanning = nil}
    log = log or function() end
    local function tell(key, line)
        if not self.told[key] then self.told[key] = true; log(line) end
    end
    -- Once per reason; the reason string itself is the key, so a repeat builds no string.
    local function tell_once(reason, prefix)
        if not self.told[reason] then self.told[reason] = true; log(prefix .. tostring(reason)) end
    end
    local NO_GROUP = 'Self-hit fix skipped: no free Havok system group in ' .. PHYS.GROUP_LOW .. '-' .. PHYS.GROUP_TOP
    local ON_BODIES, IN_ALLOCATOR = 'other bodies carry it', "the game's group allocator handed it out"
    local SKIPPED, DROPPED = {}, {}
    for g = PHYS.GROUP_LOW, PHYS.GROUP_TOP do
        SKIPPED[g] = 'Self-hit group ' .. g .. ' not used: ' .. ON_BODIES
        DROPPED[g] = 'Self-hit group ' .. g .. ' is no longer this mod\'s alone ('
    end

    local function new_job()
        return {bases = {}, limits = {}, base = {}, index = {}, layer = {}, actor = {}, unit = {}, marked = {},
                span_k = {}, span_base = {}, spans = 0, worlds = 0, w = 1, i = 0, n = 0, done = false, foreign = {}}
    end
    -- job: the last complete body scan (job_ok once there is one); scan_job: the scan in progress.
    local function new_weapon(address, handle, hi)
        return {address = address, handle = handle, name = WEAPON_NAMES[hi] or 'weapon', started = false,
                firing = false, family = {set = {}}, stack = {}, job = new_job(), scan_job = new_job(),
                job_ok = false, next_try = 0, group = nil, marked = false, destroyed = false, instance = nil,
                awaiting = false, flames = false}
    end

    -- The weapon's bodies leave its group (it is gone, or its vehicle was destroyed). Returns true, or nil and the
    -- reason a body kept its group.
    local function release(weapon)
        local ok, why = true, nil
        if weapon.marked and weapon.group and weapon.job_ok then
            ok, why = Fix.unmark(api, weapon.job, weapon.group, self.region)
            if not ok then tell_once(why, 'Self-hit group not released: ') end
        end
        weapon.marked = false
        return ok, why
    end

    -- Flame systems of live instances still in the weapon's group go back to plain layer 11.
    local function restore_flames(weapon, slot)
        if not (weapon.flames and weapon.group and slot and self.data) then return true end
        local region = self.region
        region[1], region[2] = nil, nil
        local restored, why = Fix.restore_flames(api, exe, slot, self.data, region, PHYS.FLAME_LAYER,
            PHYS.FLAME_LAYER + weapon.group * GROUP_UNIT)
        if restored then weapon.flames = false end
        return restored, why
    end

    -- A body of `unit` in group g is this mod's own when the weapon holding g has the unit in its family.
    local function own_body(g, unit)
        for _, other in pairs(self.weapons) do
            if other.group == g and other.family.set[unit] then return true end
        end
        return false
    end

    -- Group g can be this weapon's: no other weapon of this mod holds it, the weapon's latest complete body scan found
    -- no other body in it, and the game's allocator still marks it free (7 reads).
    local function usable(weapon, g)
        for _, other in pairs(self.weapons) do
            if other ~= weapon and other.group == g then return false end
        end
        if weapon.job.foreign[g] then
            tell(SKIPPED[g], SKIPPED[g])
            return false
        end
        return Fix.group_free(api, exe, g)
    end

    -- Checked at every use of the weapon's group (each burst start, and every SCAN_SECONDS while grouped): the
    -- latest body scan found no body outside the mod's own in it, and the allocator still marks it free (7 reads).
    local function still_own(weapon)
        local g = weapon.group
        if weapon.job.foreign[g] then return false, ON_BODIES end
        if not Fix.group_free(api, exe, g) then return false, IN_ALLOCATOR end
        return true
    end

    -- The weapon's group is no longer this mod's alone: its bodies and flame systems leave it at once, and the next
    -- grouping picks another free group, or none (the weapon keeps the game's own collision). A refused write turns
    -- the self-hit fix off for the session, as for any refused group write. Returns true when everything left it.
    local function drop_group(weapon, why)
        local g = weapon.group
        local released, reason = release(weapon)
        local restored, failure = restore_flames(weapon, weapon.flames and self.data and Fix.flame_slot(api, game))
        weapon.group = nil
        if not (released and restored) then
            self.self_hit_off = reason or failure
            log('Self-hit fix disabled for this session: ' .. tostring(self.self_hit_off))
            return false
        end
        if not self.told[DROPPED[g]] then
            self.told[DROPPED[g]] = true
            log(DROPPED[g] .. why .. '): the ' .. weapon.name .. "'s hit-boxes and flames left it.")
        end
        return true
    end

    -- Family and body scan for a weapon: the walk now, the scan over the next present frames, into the weapon's
    -- scan job. Until that scan is complete the last complete job stays in use, so a grouped weapon can always be
    -- released, also while its bodies are rescanned; a scan while grouped keeps the grouped bodies (as grouped).
    -- A walk or scan that fails is tried again after RETRY_SECONDS.
    local function begin_family(weapon)
        local ok, why = Fix.family(api, exe, weapon.handle, weapon.family, weapon.stack)
        if ok then ok, why = Fix.scan_begin(api, exe, weapon.scan_job) end
        if not ok then
            weapon.next_try = self.clock + RETRY_SECONDS
            tell_once(why, 'Self-hit fix unavailable: ')
            return
        end
        self.scanning = weapon
    end

    -- A body that is no longer the one a grouped weapon's scan kept (rebuilt, removed or recycled) starts a new scan.
    local function rescan_if_stale(weapon, c)
        if c.stale > 0 and self.scanning == nil and self.clock >= weapon.next_try then begin_family(weapon) end
    end

    -- A grouped weapon's bodies and group, checked on the weapon scan (every SCAN_SECONDS, one read per span and the
    -- allocator): a body the game moved to another layer means the vehicle was destroyed (its wreck leaves the
    -- group); a group no longer this mod's alone is left; a rebuilt body starts a new scan; a body back to
    -- group-free is grouped again at the next burst.
    local function check_marks(weapon)
        local c = Fix.verify(api, weapon.job, weapon.group)
        if not c then return end
        if c.moved > 0 then
            release(weapon)
            weapon.destroyed = true
            return
        end
        local own, why = still_own(weapon)
        if own then rescan_if_stale(weapon, c) else drop_group(weapon, why) end
    end

    -- Tracked spray weapons (Lumberer arms, Flame Sentries) by their instance's state word. Every
    -- SCAN_SECONDS of game time; per-weapon states and families survive the rescan.
    local spare, seen = {}, {}
    function self.scan()
        self.since_scan = 0
        local tracked, previous, last = self.tracked, self.last, spare
        for key in pairs(last) do last[key] = nil end
        for key in pairs(seen) do seen[key] = nil end
        for i = #tracked, 1, -1 do tracked[i] = nil end
        local manager = pointer(api, game + SPRAY_MANAGER_RVA)
        local count = manager and api.u32(manager + 0x38)
        if count and count > 0 and count <= MAX_SPRAYS then
            local entities, instances = pointer(api, manager + 0x60), pointer(api, manager + 0x70)
            if entities and instances then
                for index = 0, count - 1 do
                    local entity = pointer(api, entities + 8 * index)
                    local lo = entity and api.u32(entity)
                    if lo == Fix.TRACKED[1][1] or lo == Fix.TRACKED[2][1] then
                        local hi = api.u32(entity + 4)
                        if hi == Fix.TRACKED[1][2] or hi == Fix.TRACKED[2][2] then
                            local address, handle = instances + 0x218 * index, api.u32(entity + 12)
                            tracked[#tracked + 1] = address
                            last[address] = previous[address]
                            local weapon = self.weapons[address]
                            if not weapon or weapon.handle ~= handle then
                                if weapon then
                                    release(weapon)
                                    if self.scanning == weapon then self.scanning = nil end
                                end
                                weapon = new_weapon(address, handle, hi)
                                self.weapons[address] = weapon
                            end
                            seen[address] = true
                            if #tracked == MAX_TRACKED then break end
                        end
                    end
                end
            end
        end
        for address, weapon in pairs(self.weapons) do
            if not seen[address] then
                release(weapon)
                if self.scanning == weapon then self.scanning = nil end
                self.weapons[address] = nil
            elseif weapon.marked and weapon.job_ok and not weapon.firing then
                check_marks(weapon)
            end
        end
        spare, self.last = previous, last
    end

    -- A free group for this weapon: the highest usable one.
    local function pick_group(weapon)
        for g = PHYS.GROUP_TOP, PHYS.GROUP_LOW, -1 do
            if usable(weapon, g) then return g end
        end
        return nil
    end

    -- Puts the weapon's group-free bodies into its group (its own, checked just before, or a newly picked one).
    -- Returns false when the self-hit fix cannot go on for this weapon now.
    local function group_bodies(weapon)
        local g = weapon.group or pick_group(weapon)
        if not g then
            tell(NO_GROUP, NO_GROUP)
            return false
        end
        weapon.group = g
        local marked, reason = Fix.mark(api, weapon.job, g, self.region)
        if not marked then
            self.self_hit_off = reason
            log('Self-hit fix disabled for this session: ' .. tostring(reason))
            return false
        end
        weapon.marked = marked > 0
        if weapon.marked and not weapon.announced then
            weapon.announced = true
            log('Self-hit fix active for the ' .. weapon.name .. ' (' .. marked .. '/' .. weapon.job.n
                .. ' own bodies in group ' .. g .. ').')
        end
        return true
    end

    -- Effect fix (once per burst start of any tracked weapon). The full lookup runs every burst start: the effect
    -- is reloaded with each mission, and a stale shortcut could leave a mission's flame unfixed.
    function self.burst_start()
        local data, why = Fix.resolve_effect(api, exe)
        self.data = data
        if not data then
            tell_once(why, 'Flame effect not fixed: ')
        elseif not (self.patched == data and api.u32(data + Fix.PATCHES[1].o) == Fix.PATCHES[1].t) then
            local ok, detail = Fix.apply_effect(api, data)
            if ok then
                self.patched = data
                if detail > 0 then log('Flame effect fixed (' .. detail .. ' words).') end
            else
                tell_once(detail, 'Flame effect not fixed: ')
            end
        end
        if not self.filter and not self.self_hit_off then
            local filter, reason = Fix.check_filter(api, exe)
            if filter then self.filter = filter else
                self.self_hit_off = reason
                log('Self-hit fix disabled for this session: ' .. tostring(reason))
            end
        end
        self.slot = Fix.flame_slot(api, game)
    end

    -- Self-hit fix for one weapon's new burst. Its own bodies stay grouped from the first burst until the
    -- weapon is gone; a burst confirms the bodies (one read per span) and the group (the allocator), groups bodies
    -- found group-free, and moves to another free group when the weapon's group is no longer this mod's alone.
    local function weapon_burst(weapon)
        weapon.instance, weapon.awaiting = nil, true
        if not (self.filter and not self.self_hit_off and weapon.job_ok and not weapon.destroyed) then return end
        local c = Fix.verify(api, weapon.job, weapon.group)
        if not c then return end
        if c.moved > 0 then
            release(weapon)
            weapon.destroyed = true
            return
        end
        local regroup = c.free > 0
        if weapon.group then
            local own, why = still_own(weapon)
            if not own then regroup = drop_group(weapon, why) end
        end
        if regroup and not group_bodies(weapon) then return end
        rescan_if_stale(weapon, c)
    end

    -- Firing and briefly after: the weapon's burst instance (spray record +0x24) gets its group.
    local function find_burst_instance(weapon)
        local slot = self.slot or Fix.flame_slot(api, game)
        self.slot = slot
        local id = api.u32(weapon.address + PHYS.SPRAY_INSTANCE)
        if not slot or not id or id == 0 or id == weapon.instance then return end
        local record = Fix.find_instance(api, slot, id)
        if not record then return end
        weapon.instance, weapon.awaiting = id, false
        if weapon.marked and self.data then
            local sim = pointer(api, record + 8)
            local region = self.region
            region[1], region[2] = nil, nil
            local moved, why = 0, nil
            if sim then
                moved, why = Fix.retarget_instance(api, exe, sim, self.data, region,
                    PHYS.FLAME_LAYER + weapon.group * GROUP_UNIT)
            end
            if not moved then
                self.self_hit_off = why
                log('Self-hit fix disabled for this session: ' .. tostring(why))
                release(weapon)
            elseif moved > 0 then
                weapon.flames = true
            end
        end
    end

    -- Restores this mod's group writes and starts over (the update guard's pause and stop): every weapon's bodies
    -- leave its group, flame systems of live instances still in a weapon's group go back to plain layer 11, and the
    -- tracked weapons are forgotten, so the next step finds them again. The effect fix stays: it needs no upkeep, and
    -- the game reloads the effect with every mission. Raises the first reason a write was refused, after trying all.
    function self.reset()
        local slot = self.data and Fix.flame_slot(api, game)
        local failure
        for address, weapon in pairs(self.weapons) do
            local released, why = release(weapon)
            local restored, reason = restore_flames(weapon, slot)
            failure = failure or (not released and why) or (not restored and reason) or nil
            self.weapons[address] = nil
        end
        for i = #self.tracked, 1, -1 do self.tracked[i] = nil end
        for key in pairs(self.last) do self.last[key] = nil end
        self.scanning, self.watch_until, self.slot, self.since_scan = nil, nil, nil, SCAN_SECONDS
        if failure then error(failure, 0) end
    end

    -- A complete scan becomes the weapon's job. Bodies found still grouped (a scan while grouped) keep their group,
    -- and the weapon stays grouped; a group the scan found on other bodies is left at once.
    local function scan_done(weapon)
        self.scanning, weapon.job_ok = nil, true
        weapon.job, weapon.scan_job = weapon.scan_job, weapon.job
        for k = 1, weapon.job.n do weapon.marked = weapon.marked or weapon.job.marked[k] end
        if weapon.group and weapon.job.foreign[weapon.group] then drop_group(weapon, ON_BODIES) end
    end

    -- The per-frame step is one function on purpose: split into helpers (read_states, watch, scan_tick) it compiled
    -- to 50.4 instead of 20.7 KB of machine code (game's lua51.dll, same measurement as `interpreted`).
    function self.step(dt)
        self.clock = self.clock + dt
        self.since_scan = self.since_scan + dt
        if self.since_scan >= SCAN_SECONDS then self.scan() end
        local tracked, last = self.tracked, self.last
        local firing, started = false, false
        for i = 1, #tracked do
            local address = tracked[i]
            local state = api.u32(address)
            local previous = last[address]
            last[address] = state
            local weapon = self.weapons[address]
            weapon.firing = state == 1 or state == 2
            weapon.started = weapon.firing and previous ~= 1 and previous ~= 2
            firing = firing or weapon.firing
            started = started or weapon.started
        end
        if started then
            self.burst_start()
            for i = 1, #tracked do
                local weapon = self.weapons[tracked[i]]
                if weapon.started then weapon_burst(weapon) end
            end
        end
        if firing then self.watch_until = self.clock + WATCH_SECONDS end
        local watching = self.watch_until and self.clock <= self.watch_until
        if self.watch_until and not watching then self.watch_until = nil end
        if watching then
            for i = 1, #tracked do
                local weapon = self.weapons[tracked[i]]
                if weapon.firing or weapon.awaiting then find_burst_instance(weapon) end
            end
        end
        -- One family's body scan at a time, a few block reads per frame.
        local weapon = self.scanning
        if weapon then
            local done, why = Fix.scan_step(api, weapon.scan_job, weapon.family.set, SCAN_BLOCKS, weapon.group, own_body)
            if done == nil then
                self.scanning, weapon.next_try = nil, self.clock + RETRY_SECONDS
                tell_once(why, 'Self-hit fix unavailable: ')
            elseif done then
                scan_done(weapon)
            end
        else
            for i = 1, #tracked do
                local candidate = self.weapons[tracked[i]]
                if not candidate.job_ok and self.clock >= candidate.next_try then
                    begin_family(candidate)
                    break
                end
            end
        end
    end

    -- Every function above runs on a few frames only, except step and find_burst_instance (every frame, and every
    -- firing frame) and own_body (called from the compiled body-scan loop).
    interpreted({begin_family, scan_done, release, restore_flames, drop_group, self.reset, pick_group, group_bodies,
                 usable, still_own, rescan_if_stale, check_marks, self.scan, self.burst_start, weapon_burst})
    return self
end


-- ===== update chain =====
-- Flame Damage Fixed installs the shared update guard from Bingus Shared Runtime (bingus_runtime.lua),
-- which the build bundles. The guard enforces the same policy the mod used to carry by hand: the previous
-- update runs outside pcall (P1); 8 errors stop the mod, counted per burst and separately for the mod's own
-- errors and errors below, reset after 3600 clean frames (P3); an error below pauses the mod (which restores
-- its group writes and starts over) and it resumes after 60 clean frames; the first failure survives shutdown
-- (P2). ERRORS/RESUME/CLEAN below are the runtime's defaults, kept for the tests.
Fix.ERRORS, Fix.RESUME_FRAMES, Fix.CLEAN_FRAMES = 8, 60, 3600

local GAME_SHA256 = '2E2C3B7C2500646DADD5F2B4C6E0504DBB7E7896139F64CDDC0D1813C718F51E'
local EXE_SHA256 = 'F5FEE03DCFDB2E553A4752C283590950AC13316B376D8196AA556FF0400D5F06'

-- Bingus Shared Loader v18+ with API 1. The loader's own version field is not its release number (the v18
-- release reports 17), so v18 is recognized by the `jit` state it added.
function Fix.loader_ok(loader)
    return type(loader) == 'table' and loader.api == 1 and type(loader.open_log) == 'function'
        and type(loader.jit) == 'table'
end

-- The guard's pause and stop restore work: the mod takes its hit-boxes and flames out of their groups and
-- starts over (fix.reset, which raises when a write cannot be restored, so the guard stops). At shutdown it
-- restores nothing: the game is closing and its physics may already be gone.
function Fix.restore_on(fix)
    return function(reason)
        if reason ~= 'shutdown' then fix.reset() end
    end
end

-- The in-game adapter: a reused-buffer reader and writer over the game's own memory. Windows functions are
-- declared under private names, each with an __asm__ label naming the real
-- export, and the only type names are the mod's own, so another mod's declarations of the real names (before or
-- after this one) neither change what this mod calls nor are changed by it. Addresses go in as uintptr_t and no
-- 64-bit value is read back into Lua (interpreted code boxes each one): SIZE_T counts and VirtualQuery's SIZE_T
-- result are read as uint32 halves. Module files are hashed by bingus_memory.lua's shared session cache, so this
-- adapter declares no file or hashing functions. Returns the api and a module-handle getter.
function Fix.adapter()
    local ffi = require('ffi')
    if not pcall(ffi.typeof, 'hd2fdf_region') then
        ffi.cdef([[
typedef struct { uintptr_t base, allocation; uint32_t allocation_protect; uint32_t partition; size_t size; uint32_t state, protection, type; } hd2fdf_region;
void *hd2fdf_GetModuleHandleA(const char *name) __asm__("GetModuleHandleA");
void *hd2fdf_GetCurrentProcess(void) __asm__("GetCurrentProcess");
int hd2fdf_ReadProcessMemory(void *process, uintptr_t address, void *buffer, size_t size, uint32_t *done) __asm__("ReadProcessMemory");
int hd2fdf_WriteProcessMemory(void *process, uintptr_t address, const void *buffer, size_t size, uint32_t *done) __asm__("WriteProcessMemory");
uint32_t hd2fdf_VirtualQuery(uintptr_t address, hd2fdf_region *region, size_t size) __asm__("VirtualQuery");
]])
    end
    local kernel = ffi.load('kernel32')
    local process = kernel.hd2fdf_GetCurrentProcess()
    -- Bound once: numeric addresses go straight in, results land in reused buffers.
    local read_memory, write_memory = kernel.hd2fdf_ReadProcessMemory, kernel.hd2fdf_WriteProcessMemory
    local query_memory = kernel.hd2fdf_VirtualQuery
    local word, count = ffi.new('uint32_t[1]'), ffi.new('uint32_t[2]') -- count: SIZE_T as two halves
    local out_word = ffi.new('uint32_t[1]')
    local BULK_SIZE, BLOCK_SIZE = 2048, 65536
    local bulk = ffi.new('uint8_t[?]', BULK_SIZE)
    local block = ffi.new('uint8_t[?]', BLOCK_SIZE)
    local block_words = ffi.cast('uint32_t *', block)
    local region = ffi.new('hd2fdf_region[1]')
    local REGION_SIZE = ffi.sizeof('hd2fdf_region')
    -- The region as uint32 words (written only by VirtualQuery): base 0-1, size 6-7, state 8, protect 9, type 10.
    local region_words = ffi.cast('uint32_t *', region)

    local api = {}
    function api.u32(address)
        if read_memory(process, address, word, 4, count) == 0 or count[0] ~= 4 or count[1] ~= 0 then return nil end
        return word[0]
    end
    -- Bulk read into a string (tests and cold paths only).
    function api.read(address, size)
        if size < 1 or size > BULK_SIZE then return nil end
        if read_memory(process, address, bulk, size, count) == 0 or count[0] ~= size or count[1] ~= 0 then return nil end
        return ffi.string(bulk, size)
    end
    -- Block read into a reused 64 KB buffer: returns its u32 view (0-based word index), valid until the next
    -- load. Nothing is allocated: indexing a uint32_t pointer yields plain numbers.
    function api.load(address, size)
        if size < 4 or size > BLOCK_SIZE then return nil end
        if read_memory(process, address, block, size, count) == 0 or count[0] ~= size or count[1] ~= 0 then return nil end
        return block_words
    end
    local function private_rw(address)
        if query_memory(address, region, REGION_SIZE) == 0 then return nil end
        local w = region_words
        if w[8] ~= 0x1000 or w[10] ~= 0x20000 or w[9] ~= 4 then return nil end
        return w[0] + w[1] * 4294967296, w[6] + w[7] * 4294967296
    end
    -- Committed, private, read-write data only: never executable, image-mapped or read-only pages.
    function api.writable_data(address, size)
        local cursor, remaining = address, size
        while remaining > 0 do
            local base, span = private_rw(cursor)
            if not base then return false end
            local available = base + span - cursor
            if available <= 0 then return false end
            local step = math.min(available, remaining)
            cursor, remaining = cursor + step, remaining - step
        end
        return true
    end
    -- The committed private read-write region holding address: base, size (one VirtualQuery) or nil.
    function api.writable_region(address)
        return private_rw(address)
    end
    -- Caller must have passed api.writable_data or api.writable_region for the target in the same frame.
    function api.write_raw(address, bytes)
        return write_memory(process, address, bytes, #bytes, count) ~= 0 and count[0] == #bytes and count[1] == 0
    end
    -- One u32 from a reused buffer (same rule as write_raw).
    function api.write_u32(address, value)
        out_word[0] = value
        return write_memory(process, address, out_word, 4, count) ~= 0 and count[0] == 4 and count[1] == 0
    end
    return api, kernel.hd2fdf_GetModuleHandleA
end

-- Builds the fix and installs the shared runtime's update guard. runtime and memory come from the vendored
-- bingus_runtime.lua and bingus_memory.lua, which the build bundles ahead of this file. The game build is
-- checked through memory.verify_build, which hashes game.dll and the EXE at most once per session for every mod
-- (the shared hash cache).
function Fix.install(runtime, memory)
    local ffi = require('ffi')
    local loader = rawget(_G, 'CowboyBingusModLoader')
    local log_file
    if loader and type(loader.open_log) == 'function' then
        pcall(function() log_file = loader.open_log('FlameDamageFixed.log') end)
    end
    local function note(line)
        print('[FlameDamageFixed] ' .. line)
        if log_file then pcall(function() log_file:write(line .. '\n'); log_file:flush() end) end
    end
    local ready, fix = pcall(function()
        assert(Fix.loader_ok(loader), 'Bingus Shared Loader v18+ / API 1 required')
        local api, get_module = Fix.adapter()
        local game, exe = get_module('game.dll'), get_module(nil)
        assert(game ~= nil and exe ~= nil, 'Game modules unavailable')
        local ok, why = memory.verify_build({exe_sha256 = EXE_SHA256, game_sha256 = GAME_SHA256})
        assert(ok, why == 'unsupported game build' and 'Unsupported game build (needs 25480438)' or why)
        return Fix.new(api, tonumber(ffi.cast('uintptr_t', game)), tonumber(ffi.cast('uintptr_t', exe)), note)
    end)
    if not ready then
        note('Disabled: ' .. tostring(fix))
        return
    end
    runtime.guard({name = 'FlameDamageFixed', step = fix.step, stop = Fix.restore_on(fix),
                   pause = Fix.restore_on(fix), log = note, env = _G}).install()
    _G.FlameDamageFixedInstalled = true
    note('Flame Damage Fixed v1.2 initialized (spawn fix, Cremator emitter distances, self-hit fix by Havok system group).')
end

if rawget(_G, 'FLAME_DAMAGE_FIXED_TEST') then return Fix end
-- The real adapter and the module lookup, for tests/test_fix_adapter.lua and tests/test_ffi_names.lua.
if rawget(_G, 'FLAME_DAMAGE_FIXED_ADAPTER_TEST') then return Fix.adapter() end
return Fix
