"""Ship Station Hotkeys' addon entry: src/bingus_text.lua and locales/, then Bingus Shared Runtime's vendored
src/bingus_runtime.lua and src/bingus_memory.lua, ahead of src/galactic_menu_hotkey.lua, as one plaintext Lua
resource with the loader's discovery declaration first. Standard library only and no side effects on import, so
scripts/build.py and the Vanilla Plus Megapack build produce the same bytes."""
from pathlib import Path

NAME = 'mods/cowboybingus/galactic_menu_hotkey'
MAIN = 'src/galactic_menu_hotkey.lua'
# Bingus Shared Runtime's files, byte-identical copies of the canonical ones: field of ssh_runtime -> file.
RUNTIME = (('core', 'src/bingus_runtime.lua'), ('memory', 'src/bingus_memory.lua'))


def read_lua(path):
    code = Path(path).read_bytes().decode('utf-8')
    if '\r' in code:
        raise ValueError(f'{Path(path).name} must use LF line endings')
    return code.rstrip('\n')


def locale_files(root):
    """locales/en.lua first, then each bundled translation (<tag>.lua)."""
    folder = Path(root) / 'locales'
    return [folder / 'en.lua'] + sorted(p for p in folder.glob('*.lua') if p.name != 'en.lua')


def entry_text(root):
    """The entry: the main file's declaration line, then the text module and the locales as the local
    ssh_text, then the runtime files as the functions of the local ssh_runtime (each returns its table; the main
    file runs them after its re-entry guard), then the rest of the main file."""
    root = Path(root)
    header, _, main = read_lua(root / MAIN).partition('\n')
    if header != '-- HD2-Addon: ' + NAME:
        raise ValueError(f'{MAIN} must start with its discovery declaration')
    lines = [header,
             '-- Generated by scripts/build.py from src/bingus_text.lua, '
             + ', '.join('locales/' + p.name for p in locale_files(root)) + ', '
             + ', '.join(path for _, path in RUNTIME) + ' and ' + MAIN + '; edit those instead.',
             'local ssh_text = {module = (function()', read_lua(root / 'src/bingus_text.lua'), 'end)(),',
             '    locales = {bundled = {}}}']
    for path in locale_files(root):
        target = 'ssh_text.locales.en' if path.name == 'en.lua' else f"ssh_text.locales.bundled['{path.stem}']"
        lines += [f'{target} = (function()', read_lua(path), 'end)()']
    lines.append('local ssh_runtime = {}')
    for field, path in RUNTIME:
        lines += [f'ssh_runtime.{field} = function(...)', read_lua(root / path), 'end']
    lines.append(main)
    return ('\n'.join(lines) + '\n').encode('utf-8')
