"""Mod Options Menu's addon entry: src/bingus_text.lua and locales/, then the other source files (Bingus Shared
Runtime's vendored src/bingus_runtime.lua and src/bingus_memory.lua among them), ahead of src/mod_options_menu.lua,
as one plaintext Lua resource with the loader's discovery declaration first. Standard library only and no side
effects on import, so scripts/build.py and the Vanilla Plus Megapack build produce the same bytes."""
import re
from pathlib import Path

NAME = 'mods/cowboybingus/mod_options_menu'
MAIN = 'src/mod_options_menu.lua'
TEXT = 'src/bingus_text.lua'
# The main file runs each other source file once, outside comments: mom_files.<name>(mom) for MOM's own files,
# mom_files.<name>() for the runtime files, which return their tables.
RUN = re.compile(r'^(?!\s*--)[^\n]*?\bmom_files\.(\w+)\(', re.MULTILINE)


def read_lua(path):
    code = Path(path).read_bytes().decode('utf-8')
    if '\r' in code:
        raise ValueError(f'{Path(path).name} must use LF line endings')
    return code.rstrip('\n')


def locale_files(root):
    """locales/en.lua first, then each bundled translation (<tag>.lua)."""
    folder = Path(root) / 'locales'
    return [folder / 'en.lua'] + sorted(p for p in folder.glob('*.lua') if p.name != 'en.lua')


def source_files(root):
    """Every other src/*.lua file, by name: neither the main file nor the text module."""
    skip = {Path(MAIN).name, Path(TEXT).name}
    return sorted(p for p in (Path(root) / 'src').glob('*.lua') if p.name not in skip)


def entry_text(root):
    """The entry: the main file's declaration line, then the text module and the locales as the one local
    mom_text, then each other source file as a function of its own (with its own limit of 200 locals) in the
    one local mom_files, then the rest of the main file, which runs those functions after its re-entry guard.
    The vendored runtime files are embedded unchanged, each as such a function, which returns its table."""
    root = Path(root)
    header, _, main = read_lua(root / MAIN).partition('\n')
    if header != '-- HD2-Addon: ' + NAME:
        raise ValueError(f'{MAIN} must start with its discovery declaration')
    sources = source_files(root)
    runs = RUN.findall(main)
    if sorted(runs) != [path.stem for path in sources]:
        raise ValueError(f'{MAIN} must run each other src/*.lua file once: runs {runs}, files '
                         f'{[path.name for path in sources]}')
    lines = [header,
             '-- Generated by scripts/build.py from ' + TEXT + ', '
             + ', '.join('locales/' + p.name for p in locale_files(root)) + ', '
             + ', '.join('src/' + p.name for p in sources) + ' and ' + MAIN + '; edit those instead.',
             'local mom_text = {module = (function()', read_lua(root / TEXT), 'end)(),',
             '    locales = {bundled = {}}}']
    for path in locale_files(root):
        target = 'mom_text.locales.en' if path.name == 'en.lua' else f"mom_text.locales.bundled['{path.stem}']"
        lines += [f'{target} = (function()', read_lua(path), 'end)()']
    lines.append('local mom_files = {}')
    for path in sources:
        lines += [f'mom_files.{path.stem} = function(...)', read_lua(path), 'end']
    lines.append(main)
    return ('\n'.join(lines) + '\n').encode('utf-8')
