"""Mod Options Menu's addon entry: src/bingus_text.lua and locales/ ahead of src/mod_options_menu.lua, as one
plaintext Lua resource with the loader's discovery declaration first. Standard library only and no side
effects on import, so scripts/build.py and the Vanilla Plus Megapack build produce the same bytes."""
from pathlib import Path

NAME = 'mods/cowboybingus/mod_options_menu'
MAIN = 'src/mod_options_menu.lua'


def read_lua(path):
    code = Path(path).read_bytes().decode('utf-8')
    if '\r' in code:
        raise ValueError(f'{Path(path).name} must use LF line endings')
    return code.rstrip('\n')


def locale_files(root):
    """locales/en.lua first, then each bundled translation (<tag>.lua)."""
    folder = Path(root) / 'locales'
    return [folder / 'en.lua'] + sorted(p for p in folder.glob('*.lua') if p.name != 'en.lua')


def entry_text(root):
    """The entry: the main file's declaration line, then the text module and the locales as the one
    local mom_text (the main file is near Lua's limit of 200 locals), then the rest of the main file."""
    root = Path(root)
    header, _, main = read_lua(root / MAIN).partition('\n')
    if header != '-- HD2-Addon: ' + NAME:
        raise ValueError(f'{MAIN} must start with its discovery declaration')
    lines = [header,
             '-- Generated by scripts/build.py from src/bingus_text.lua, '
             + ', '.join('locales/' + p.name for p in locale_files(root)) + ' and ' + MAIN + '; edit those instead.',
             'local mom_text = {module = (function()', read_lua(root / 'src/bingus_text.lua'), 'end)(),',
             '    locales = {bundled = {}}}']
    for path in locale_files(root):
        target = 'mom_text.locales.en' if path.name == 'en.lua' else f"mom_text.locales.bundled['{path.stem}']"
        lines += [f'{target} = (function()', read_lua(path), 'end)()']
    lines.append(main)
    return ('\n'.join(lines) + '\n').encode('utf-8')
