"""Test and build Sticky Grenade Handles.

Needs a Bingus Shared Loader checkout beside this repository (or its path in BINGUS_SHARED_LOADER) for
scripts/archive.py and scripts/build_addon.py, a LuaJIT (HD2_LUAJIT, default: the workspace build, else
`luajit` on PATH) and the installed game's bin/lua51.dll for the in-game runtime tests (tests/game_lua.py,
HD2_LUA51_DLL).
"""

from __future__ import annotations

import json
import os
from pathlib import Path
import shutil
import struct
import subprocess
import sys
import uuid
import zipfile

sys.dont_write_bytecode = True
HERE = Path(__file__).resolve().parents[1]
WORKSPACE = HERE.parent
LOADER = Path(os.environ.get('BINGUS_SHARED_LOADER', WORKSPACE / 'BingusSharedLoader'))
sys.path.insert(0, str(LOADER / 'scripts'))
from archive import ARCHIVE, make_archive, resource_hash  # noqa: E402
from build_addon import entry_source  # noqa: E402

VERSION = '1.0'
LUA_NAME = 'mods/cowboybingus/sticky_grenade_handles'
GUID = '2170bc37-eac4-49c9-843f-3fc1fcd578d9'
TITLE = 'Sticky Grenade Handles v' + VERSION
DESCRIPTION = ("The G-123 Thermite and the sticky stun grenade stick when their handle hits first, instead of "
               "bouncing off. Steam build 25480438. Requires Bingus Shared Loader v18 or newer.")
GAME_LUA = HERE / 'tests/game_lua.py'
MOD = 'sticky_grenade_handles.lua'
# Local copies that must stay byte-identical to the workspace's canonical ones (checked when present).
CANONICAL = {'tests/frame_budget.lua': 'PerformanceBaseline/frame_budget.lua',
             'tests/game_lua.py': 'PerformanceBaseline/game_lua.py',
             'tests/hostile_vm.lua': 'BingusSharedRuntime/hostile_vm.lua',
             'src/bingus_runtime.lua': 'BingusSharedRuntime/runtime/bingus_runtime.lua',
             'src/bingus_memory.lua': 'BingusSharedRuntime/runtime/bingus_memory.lua',
             'src/bingus_write.lua': 'BingusSharedRuntime/runtime/bingus_write.lua'}
# Vendored Bingus Shared Runtime files assembled ahead of the mod's own source, in order.
RUNTIME_FILES = ('bingus_runtime.lua', 'bingus_memory.lua', 'bingus_write.lua')
FORBIDDEN = ('VirtualProtect', 'VirtualAlloc', 'FlushInstructionCache', 'CreateRemoteThread', 'LoadLibrary')


def assemble() -> bytes:
    """One plaintext addon entry: the second-copy check, the vendored runtime files, then the mod, which is
    installed with the runtime's memory api extended by its checked writes. The entry carries the loader's
    discovery declaration on its first line."""
    marker = '-- HD2-Addon: ' + LUA_NAME
    sources = {name: (HERE / 'src' / name).read_text(encoding='utf-8') for name in RUNTIME_FILES}
    mod = (HERE / 'src' / MOD).read_text(encoding='utf-8')
    if not mod.startswith(marker + '\n'):
        raise ValueError(MOD + ' must begin with its HD2-Addon declaration')
    mod = mod.split('\n', 1)[1]  # the entry carries the declaration once, on its own first line
    lines = [marker,
             '-- Sticky Grenade Handles v%s for Steam build 25480438. Generated by scripts/build.py from %s; edit those.'
             % (VERSION, ', '.join('src/' + n for n in RUNTIME_FILES + (MOD,))),
             "if rawget(_G, 'StickyGrenadeHandles') then return end",
             'local bingus_runtime = (function()', sources['bingus_runtime.lua'].rstrip('\n'), 'end)()',
             'local bingus_memory = (function()', sources['bingus_memory.lua'].rstrip('\n'), 'end)()',
             'local bingus_write = (function()', sources['bingus_write.lua'].rstrip('\n'), 'end)()',
             'local Mod = (function()', mod.rstrip('\n'), 'end)()',
             'Mod.install(bingus_write.extend(bingus_memory.new(bingus_runtime)))']
    return ('\n'.join(lines) + '\n').encode('utf-8')


def luajit() -> Path:
    if 'HD2_LUAJIT' in os.environ:
        return Path(os.environ['HD2_LUAJIT'])
    workspace = WORKSPACE / 'tools/src/LuaJIT/src/luajit.exe'
    return workspace if workspace.exists() else Path(shutil.which('luajit') or workspace)


def run(args: list) -> str:
    result = subprocess.run([str(a) for a in args], capture_output=True, text=True, cwd=HERE)
    output = (result.stdout + result.stderr).strip()
    if result.returncode or 'PASS' not in output:
        raise RuntimeError(f'{args}: {output}')
    return [line for line in output.splitlines() if 'PASS' in line][-1]


def test() -> list[str]:
    source = (HERE / 'src' / MOD).read_text(encoding='utf-8')
    for word in FORBIDDEN:
        if word in source:
            raise ValueError('Unexpected executable memory mutation: ' + word)
    for local, shared in CANONICAL.items():
        canonical = WORKSPACE / shared
        if canonical.exists() and canonical.read_bytes() != (HERE / local).read_bytes():
            raise ValueError(f'{local} differs from the canonical {shared}')
    results = []
    lua = luajit()
    entry = HERE / 'build/entry-check.lua'
    entry.parent.mkdir(parents=True, exist_ok=True)
    entry.write_bytes(assemble())
    for vm in ([lua], [sys.executable, GAME_LUA]):
        results.append(run(vm + [HERE / 'tests/test_mod.lua', HERE]))
        # The assembled entry (runtime + memory + write + mod) must compile as one LuaJIT chunk in both VMs,
        # refuse outside the game and run only once.
        results.append(run(vm + [HERE / 'tests/compile_entry.lua', entry]))
        results.append(run(vm + [HERE / 'tests/test_entry.lua', entry]))
    return results


def build(output: Path) -> Path:
    body = entry_source(LUA_NAME, assemble())
    lua = struct.pack('<II', len(body), 2) + body
    option = {'Name': TITLE, 'Description': DESCRIPTION, 'Include': ['Addon']}
    manifest = {'Version': 1, 'Guid': str(uuid.UUID(GUID)), 'Name': TITLE, 'Description': DESCRIPTION,
                'Options': [option]}
    files = {'INSTALL.txt': (HERE / 'INSTALL.txt').read_bytes()}
    thumbnail = HERE / 'assets/thumbnail.png'
    if thumbnail.exists():
        files['thumbnail.png'] = thumbnail.read_bytes()
        manifest['IconPath'] = option['Image'] = 'thumbnail.png'
    files.update({
        'manifest.json': (json.dumps(manifest, indent=2) + '\n').encode(),
        'Addon/' + ARCHIVE: make_archive({resource_hash(LUA_NAME): lua}),
        'Addon/' + ARCHIVE + '.stream': b'',
        'Addon/' + ARCHIVE + '.gpu_resources': b'',
    })
    output.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(output, 'w', compression=zipfile.ZIP_DEFLATED) as archive:
        for path, payload in sorted(files.items()):
            info = zipfile.ZipInfo(path, date_time=(1980, 1, 1, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o100644 << 16
            archive.writestr(info, payload)
    return output


if __name__ == '__main__':
    for line in test():
        print(line)
    print(build(HERE / 'releases' / f'Sticky-Grenade-Handles-v{VERSION}.zip'))
