"""Test and build Laser Sentry Cooldown.

    python -B scripts/build.py           tests, then releases/Laser-Sentry-Cooldown-v<VERSION>.zip
    python -B scripts/build.py --test    tests, then also build/Laser-Sentry-Cooldown-v<VERSION>-test.zip (live test
                                         build: the mod plus src/test_hooks.lua; never publish it)

Needs a Bingus Shared Loader checkout (BINGUS_SHARED_LOADER, default: the workspace's ongoing-work checkout
publication/resilience-v1/checkouts/BingusSharedLoader, else BingusSharedLoader beside this repository) for
scripts/archive.py and scripts/build_addon.py, a LuaJIT (HD2_LUAJIT, default: the workspace build, else `luajit` on
PATH) and the installed game's bin/lua51.dll for the in-game VM tests (tests/game_lua.py, HD2_LUA51_DLL).
"""

from __future__ import annotations

import json
import os
from pathlib import Path
import shutil
import struct
import subprocess
import sys
import uuid
import zipfile

sys.dont_write_bytecode = True
HERE = Path(__file__).resolve().parents[1]
WORKSPACE = HERE.parent


def loader_checkout() -> Path:
    if 'BINGUS_SHARED_LOADER' in os.environ:
        return Path(os.environ['BINGUS_SHARED_LOADER'])
    ongoing = WORKSPACE / 'publication/resilience-v1/checkouts/BingusSharedLoader'
    return ongoing if (ongoing / 'scripts/build_addon.py').exists() else WORKSPACE / 'BingusSharedLoader'


sys.path.insert(0, str(loader_checkout() / 'scripts'))
from archive import ARCHIVE, make_archive, resource_hash  # noqa: E402
from build_addon import entry_source  # noqa: E402

VERSION = '1.1'
LUA_NAME = 'mods/cowboybingus/laser_sentry_cooldown'
GUID = 'e13da4a7-0d70-4ddf-a7d0-d172a96caa57'
TITLE = 'Laser Sentry Cooldown v' + VERSION
DESCRIPTION = ('At max heat the A/LAS-98 Laser Sentry overheats and stops firing as usual, then cools at its normal '
               'rate (about 50 s) and fires again, instead of exploding. No options; every value is the game\'s '
               'own. Steam build 25480438. Requires Bingus Shared Loader v18+.')
TEST_TITLE = 'Laser Sentry Cooldown v' + VERSION + ' TEST'
TEST_DESCRIPTION = ('Live test build of Laser Sentry Cooldown: behaves exactly like the release and logs every Laser '
                    'Sentry\'s heat to LaserSentryCooldown.log. Not for normal play.')
GAME_LUA = HERE / 'tests/game_lua.py'
# Local copies that must stay byte-identical to the workspace's canonical ones (checked when present).
CANONICAL = {'tests/frame_budget.lua': 'PerformanceBaseline/frame_budget.lua',
             'tests/game_lua.py': 'PerformanceBaseline/game_lua.py',
             'tests/hostile_vm.lua': 'BingusSharedRuntime/hostile_vm.lua',
             'src/bingus_runtime.lua': 'BingusSharedRuntime/runtime/bingus_runtime.lua',
             'src/bingus_memory.lua': 'BingusSharedRuntime/runtime/bingus_memory.lua'}
# Vendored Bingus Shared Runtime files, assembled ahead of the mod in this order. The mod writes through its own
# adapter (the record is on a read-only page, which bingus_write.lua refuses by design), so it vendors the core
# and the read side only; bingus_memory.lua verifies the game build.
RUNTIME_FILES = ('bingus_runtime.lua', 'bingus_memory.lua')
# Names the mod's sources must never contain: code or thread creation, library loading, network calls.
FORBIDDEN = ('VirtualAlloc', 'FlushInstructionCache', 'CreateRemoteThread', 'LoadLibrary', 'Network.', 'RPC.')
ADAPTER_MODES = ('plain', 'hostile', 'sdk')


def assemble(test: bool = False) -> bytes:
    """One plaintext addon entry: the re-entry guard, the vendored runtime files, the mod (and, for the live test
    build, the test hooks). The entry carries the loader's discovery declaration on its first line."""
    marker = '-- HD2-Addon: ' + LUA_NAME
    sources = {name: (HERE / 'src' / name).read_text(encoding='utf-8') for name in RUNTIME_FILES}
    mod = (HERE / 'src/laser_sentry_cooldown.lua').read_text(encoding='utf-8')
    if not mod.startswith(marker + '\n'):
        raise ValueError('laser_sentry_cooldown.lua must begin with its HD2-Addon declaration')
    mod = mod.split('\n', 1)[1]  # the entry carries the declaration once, on its own first line
    files = ['src/' + n for n in RUNTIME_FILES + ('laser_sentry_cooldown.lua',)] + (['src/test_hooks.lua'] if test else [])
    lines = [marker,
             '-- Laser Sentry Cooldown v%s%s for Steam build 25480438. Generated by scripts/build.py from %s; edit those.'
             % (VERSION, ' (LIVE TEST BUILD)' if test else '', ', '.join(files)),
             "if rawget(_G, 'LaserSentryCooldownInstalled') then return end",
             'local bingus_runtime = (function()', sources['bingus_runtime.lua'].rstrip('\n'), 'end)()',
             'local bingus_memory = (function()', sources['bingus_memory.lua'].rstrip('\n'), 'end)()',
             'local Cooldown = (function()', mod.rstrip('\n'), 'end)()',
             'local memory = bingus_memory.new(bingus_runtime)',
             'local instance = Cooldown.install(bingus_runtime, memory)']
    if test:
        hooks = (HERE / 'src/test_hooks.lua').read_text(encoding='utf-8')
        lines += ['local test_hooks = (function()', hooks.rstrip('\n'), 'end)()',
                  'if instance then test_hooks(Cooldown, instance, bingus_runtime, memory) end']
    for line in lines:
        if '\r' in line:
            raise ValueError('sources must use LF line endings')
    return ('\n'.join(lines) + '\n').encode('utf-8')


def luajit() -> Path:
    if 'HD2_LUAJIT' in os.environ:
        return Path(os.environ['HD2_LUAJIT'])
    workspace = WORKSPACE / 'tools/src/LuaJIT/src/luajit.exe'
    return workspace if workspace.exists() else Path(shutil.which('luajit') or workspace)


def run(args: list) -> str:
    result = subprocess.run([str(a) for a in args], capture_output=True, text=True, cwd=HERE)
    output = (result.stdout + result.stderr).strip()
    if result.returncode or 'PASS' not in output:
        raise RuntimeError(f'{args}: {output}')
    return [line for line in output.splitlines() if 'PASS' in line][0]


def test() -> list[str]:
    for path in sorted((HERE / 'src').glob('*.lua')):
        if path.name in RUNTIME_FILES:
            continue
        text = path.read_text(encoding='utf-8')
        for word in FORBIDDEN:
            if word in text:
                raise ValueError(f'{path.name}: forbidden name {word}')
    for local, shared in CANONICAL.items():
        canonical = WORKSPACE / shared
        if canonical.exists() and canonical.read_bytes() != (HERE / local).read_bytes():
            raise ValueError(f'{local} differs from the canonical {shared}')
    results = []
    lua = luajit()
    build = HERE / 'build'
    build.mkdir(exist_ok=True)
    entries = {'release': build / 'entry-check.lua', 'test': build / 'entry-check-test.lua'}
    entries['release'].write_bytes(assemble(False))
    entries['test'].write_bytes(assemble(True))
    for vm in ([lua], [sys.executable, GAME_LUA]):
        results.append(run(vm + [HERE / 'tests/test_cooldown.lua', HERE]))
        results.append(run(vm + [HERE / 'tests/test_hooks.lua', HERE]))
        results.append(run(vm + [HERE / 'tests/test_turret.lua', HERE]))
        for mode in ADAPTER_MODES:
            results.append(run(vm + [HERE / 'tests/test_adapter.lua', HERE, mode]))
        for kind, entry in entries.items():
            results.append(run(vm + [HERE / 'tests/compile_entry.lua', entry]) + ' (' + kind + ')')
    return results


def build(output: Path, test: bool = False) -> Path:
    body = entry_source(LUA_NAME, assemble(test))
    lua = struct.pack('<II', len(body), 2) + body
    title, description = (TEST_TITLE, TEST_DESCRIPTION) if test else (TITLE, DESCRIPTION)
    option = {'Name': title, 'Description': description, 'Include': ['Addon']}
    manifest = {'Version': 1, 'Guid': str(uuid.UUID(GUID)), 'Name': title, 'Description': description,
                'Options': [option]}
    files = {'INSTALL.txt': (HERE / 'INSTALL.txt').read_bytes()}
    thumbnail = HERE / 'assets/thumbnail.png'
    if thumbnail.exists():
        files['thumbnail.png'] = thumbnail.read_bytes()
        manifest['IconPath'] = option['Image'] = 'thumbnail.png'
    files.update({
        'manifest.json': (json.dumps(manifest, indent=2) + '\n').encode(),
        'Addon/' + ARCHIVE: make_archive({resource_hash(LUA_NAME): lua}),
        'Addon/' + ARCHIVE + '.stream': b'',
        'Addon/' + ARCHIVE + '.gpu_resources': b'',
    })
    output.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(output, 'w', compression=zipfile.ZIP_DEFLATED) as archive:
        for path, payload in sorted(files.items()):
            info = zipfile.ZipInfo(path, date_time=(1980, 1, 1, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o100644 << 16
            archive.writestr(info, payload)
    return output


if __name__ == '__main__':
    for line in test():
        print(line)
    print(build(HERE / 'releases' / f'Laser-Sentry-Cooldown-v{VERSION}.zip'))
    if '--test' in sys.argv[1:]:
        print(build(HERE / 'build' / f'Laser-Sentry-Cooldown-v{VERSION}-test.zip', test=True))
