-- Checks that the assembled addon entry (runtime + memory + the mod, generated by scripts/build.py) compiles
-- as one LuaJIT chunk, in the workspace LuaJIT and in the game's lua51.dll. It never runs the chunk.
-- Usage: luajit tests/compile_entry.lua <path to the assembled entry>
local path = assert(arg[1], 'entry path required')
local chunk, err = loadfile(path)
assert(chunk, 'assembled entry does not compile: ' .. tostring(err))
print('PASS: assembled entry compiles')
