-- Runs the assembled addon entry (generated by scripts/build.py) twice in a test VM with a stand-in loader:
-- outside the game the real build check refuses, so the first copy disables itself without hooking anything,
-- and the second copy returns at once. Usage: luajit tests/test_entry.lua <path to the assembled entry>
local path = assert(arg[1], 'entry path required')
local lines = {}
_G.CowboyBingusModLoader = {api = 1, open_log = function()
    return {write = function(_, text) lines[#lines + 1] = text end, flush = function() end}
end}
local function vanilla() return 'vanilla' end
_G.update, _G.shutdown = vanilla, nil
local quiet = print
print = function() end -- the mod's console line
local chunk = assert(loadfile(path))
chunk()
local state = rawget(_G, 'StickyGrenadeHandles')
assert(type(state) == 'table' and not state.applied, 'no state after the first copy')
assert(state.status:find('^disabled: '), state.status)
assert(_G.update == vanilla and _G.shutdown == nil, 'a refused copy hooked the game')
assert(#lines == 1 and lines[1]:find('disabled', 1, true), table.concat(lines))
chunk()
assert(rawget(_G, 'StickyGrenadeHandles') == state and #lines == 1, 'the second copy did something')
print = quiet
print('PASS: assembled entry refuses outside the game and runs once (' .. state.status .. ')')
