-- Generated by scripts/generate_profiles.py from profiles/catalog.json.
-- Exact resource, skeleton, main-body and auxiliary actor allowlists.
local profiles = {
    ['\059\238\251\018\066\231\248\220']={name="Impaler",nodes=139,bodies=15,finish_disabled=false,main={
        0x9b115563,0x58d886fb,0x5a4bbaa2,0x1fba9b23,0xacb975d0,0xe411e02e,0x8329f875,0x4014953a,0xc1466369,0xf69f42da,0x73bc7ae4,0xce7e106a,0x38f24831,0xf452db4a,0x9b47948d},
        disabled_main={},actors={
            [0x06041d5c]=0xf69f42da,
            [0x0a4517aa]=0xc1466369,
            [0x0aec1ca8]=0xacb975d0,
            [0x0be61734]=0x4508030c,
            [0x0bf0d87a]=0xf452db4a,
            [0x1245edba]=0xcb0c4b47,
            [0x1ff1c46a]=0x91c08b37,
            [0x50b19c0a]=0xbc852b90,
            [0x5f3a2d43]=0xa5dd6396,
            [0x6635646b]=0x47cd28d0,
            [0x681424d1]=0x4014953a,
            [0x6c0f2f68]=0x38f24831,
            [0x70f1db61]=0x9b47948d,
            [0x82219dbd]=0xb9b5a67f,
            [0x8668a205]=0x80f85d7b,
            [0x879c1a75]=0x5a4bbaa2,
            [0x87a058bf]=0x9b115563,
            [0x92d0871f]=0x0135b322,
            [0x9a7b92fa]=0xce7e106a,
            [0x9f5aae0c]=0x8329f875,
            [0xa3d491d1]=0x9b115563,
            [0xa4ab9dfd]=0x73bc7ae4,
            [0xc35018a3]=0x9b115563,
            [0xe42bf5f2]=0xe411e02e,
            [0xed574a1d]=0x9b115563,
            [0xed967ef1]=0xdb63f30c,
            [0xf6c42514]=0x58d886fb,
            [0xf91972b9]=0x1fba9b23,
        }},
    ['\148\235\211\007\028\161\129\163']={name="Burrowing Spewer",nodes=102,bodies=14,finish_disabled=false,main={
        0x9b115563,0x0f0196b3,0xc96f8166,0xae5a7e64,0xdcb76f26,0x1ecb5822,0x0f5d4be0,0x12fd8f94,0x341adbcc,0xd66758f9,0x8b9102b4,0xfa1accaf,0x6e8366df,0x0f5f005b},
        disabled_main={},actors={
            [0x312d55bb]=0x0e835875,
            [0x4ea4da87]=0x09a026f5,
            [0x573a0652]=0x1c5f3be4,
            [0xa3d491d1]=0xbccf91e5,
            [0xbc01b5fd]=0x0f0196b3,
            [0xc947ded4]=0xbccf91e5,
        }},
    ['\194\023\090\036\147\002\087\239']={name="Automaton assault walker",nodes=104,bodies=10,finish_disabled=false,main={
        0x9b115563,0x09a026f5,0x748f4281,0x8e1c9de6,0x4cb04651,0x5d8553b4,0xb7681bdc,0x1fb60c2a,0xbcbfce4f,0xc0e8f3b9},
        corpse_dynamic_main={[0x09a026f5]=true,[0xb7681bdc]=true,[0x1fb60c2a]=true},
        disabled_main={[0xb7681bdc]=true,[0x1fb60c2a]=true,[0xbcbfce4f]=true,[0xc0e8f3b9]=true},actors={
            [0x24a81ad3]=0x372f0418,
            [0x29bdbcff]=0x8e1c9de6,
            [0x2d729a79]=0xf9baf117,
            [0x3326c96e]=0x48741b07,
            [0x33dc3693]=0x46ddad11,
            [0x6f2078a8]=0x46ddad11,
            [0x807a2fe2]=0x4cb04651,
            [0x83498e9e]=0x748f4281,
            [0x87e4519b]=0x9b115563,
            [0xb2d0e941]=0x8eb19d6a,
            [0xcd2f2b20]=0x9b115563,
            [0xce7c02c9]=0x5d8553b4,
            [0xe55b4e87]=0x8eb19d6a,
            [0xfbb9eb3d]=0x372f0418,
            [0xfd9562d4]=0x9b115563,
        }},
    ['\155\008\114\209\253\034\112\204']={name="Nursing Spewer",nodes=99,bodies=14,finish_disabled=false,main={
        0x9b115563,0x0f0196b3,0xc96f8166,0xae5a7e64,0xdcb76f26,0x1ecb5822,0x0f5d4be0,0x12fd8f94,0x341adbcc,0xd66758f9,0x8b9102b4,0xfa1accaf,0x6e8366df,0x0f5f005b},
        disabled_main={},actors={
            [0x312d55bb]=0x0e835875,
            [0x4ea4da87]=0x09a026f5,
            [0x573a0652]=0x1c5f3be4,
            [0xa3d491d1]=0xbccf91e5,
            [0xbc01b5fd]=0x0f0196b3,
        }},
    ['\183\145\213\172\100\082\174\204']={name="Bile Spewer tier 2",nodes=99,bodies=14,finish_disabled=false,main={
        0x9b115563,0x0f0196b3,0xc96f8166,0xae5a7e64,0xdcb76f26,0x1ecb5822,0x0f5d4be0,0x12fd8f94,0x341adbcc,0xd66758f9,0x8b9102b4,0xfa1accaf,0x6e8366df,0x0f5f005b},
        disabled_main={},actors={
            [0x312d55bb]=0x0e835875,
            [0x4ea4da87]=0x09a026f5,
            [0x573a0652]=0x1c5f3be4,
            [0xa3d491d1]=0xbccf91e5,
            [0xbc01b5fd]=0x0f0196b3,
        }},
    ['\070\001\230\229\204\153\170\054']={name="Bile Spewer",nodes=117,bodies=14,finish_disabled=false,main={
        0x9b115563,0x0f0196b3,0xc96f8166,0xae5a7e64,0xdcb76f26,0x1ecb5822,0x0f5d4be0,0x12fd8f94,0x341adbcc,0xd66758f9,0x8b9102b4,0xfa1accaf,0x6e8366df,0x0f5f005b},
        disabled_main={},actors={
            [0x312d55bb]=0x0e835875,
            [0x4ea4da87]=0x09a026f5,
            [0x573a0652]=0x1c5f3be4,
            [0xa3d491d1]=0xbccf91e5,
            [0xbc01b5fd]=0x0f0196b3,
        }},
    ['\175\183\081\008\255\203\063\214']={name="Illuminate tripod tier 2",nodes=151,bodies=10,finish_disabled=true,main={
        0x9b115563,0x54efdee3,0xb4a6064f,0xa7f9b6c7,0xc6b89048,0xe225767c,0xb1332141,0xa76ee4c6,0x9615b731,0x18ca9123},
        disabled_main={[0x9b115563]=true,[0x54efdee3]=true,[0xb4a6064f]=true,[0xa7f9b6c7]=true,[0xc6b89048]=true,[0xe225767c]=true,[0xb1332141]=true,[0xa76ee4c6]=true,[0x9615b731]=true,[0x18ca9123]=true},actors={
            [0x0143255a]=0xa7f9b6c7,
            [0x0410bac8]=0xe225767c,
            [0x105602e6]=0x8c5570c9,
            [0x1fcfcae3]=0xb4a6064f,
            [0x2434f4a4]=0x9615b731,
            [0x251fe443]=0x8c5570c9,
            [0x285484ce]=0x8c5570c9,
            [0x29ca953e]=0x18ca9123,
            [0x37236374]=0xe9b4fd2d,
            [0x3d43b4b1]=0x8c5570c9,
            [0x43a3844e]=0x8c5570c9,
            [0x470cf2c5]=0xb4a6064f,
            [0x4bca1f07]=0xa7f9b6c7,
            [0x53db7fab]=0x8c5570c9,
            [0x58a98e8a]=0x8c5570c9,
            [0x599c3f71]=0xb1332141,
            [0x7394dd4e]=0xe225767c,
            [0x764e448d]=0x54efdee3,
            [0x84ffdd57]=0x18ca9123,
            [0x8ffb63db]=0xa7f9b6c7,
            [0x918bc99f]=0x8c5570c9,
            [0x9212fdd7]=0x8c5570c9,
            [0x9ee677a7]=0x8c5570c9,
            [0xa7e3257e]=0xb1332141,
            [0xb7ff9cb7]=0x8c5570c9,
            [0xb875a8c9]=0xe90e668d,
            [0xc7134a8c]=0x18ca9123,
            [0xcabc21d4]=0xa76ee4c6,
            [0xcd871ca9]=0xc6b89048,
            [0xcec2d2ea]=0xb4a6064f,
            [0xd48608a6]=0xb1332141,
            [0xdf038f71]=0x9615b731,
            [0xecf00ed4]=0x9615b731,
            [0xee8b6459]=0x78678dbb,
            [0xf2931585]=0xe225767c,
            [0xf8720bf5]=0x8c5570c9,
            [0xfbb9eb3d]=0x8c5570c9,
        }},
    ['\007\241\190\055\123\002\045\242']={name="Illuminate war machine",nodes=124,bodies=6,finish_disabled=false,main={
        0x9b115563,0xad3058fd,0x730d4fce,0x963fef84,0x98f66bd1,0x26059f72},
        disabled_main={},actors={
            [0x02a72e9d]=0x1fc641f6,
            [0x03bf2ea0]=0x3e2ee4c1,
            [0x0d213aba]=0x7ce6544d,
            [0x14231a1f]=0xe9b8ff15,
            [0x1f02fa15]=0x1fc641f6,
            [0x4d0ec52f]=0x98829f00,
            [0x568574e3]=0xe9b8ff15,
            [0x6f16b93e]=0x3e2ee4c1,
            [0x7320fca3]=0xe9b8ff15,
            [0x750e1696]=0x1fc641f6,
            [0x8eebeedd]=0x3e2ee4c1,
            [0xc6597663]=0xe9b8ff15,
            [0xcc90682d]=0x7ce6544d,
            [0xd8af4506]=0xe9b8ff15,
            [0xda16193c]=0x1fc641f6,
            [0xdd53208d]=0x98829f00,
            [0xe9e90424]=0x98829f00,
            [0xed78bda7]=0x3e2ee4c1,
            [0xf4b7d5ca]=0x98829f00,
        }},
    ['\074\221\172\081\090\174\094\150']={name="Illuminate tripod",nodes=151,bodies=10,finish_disabled=true,main={
        0x9b115563,0x54efdee3,0xb4a6064f,0xa7f9b6c7,0xc6b89048,0xe225767c,0xb1332141,0xa76ee4c6,0x9615b731,0x18ca9123},
        disabled_main={[0x9b115563]=true,[0x54efdee3]=true,[0xb4a6064f]=true,[0xa7f9b6c7]=true,[0xc6b89048]=true,[0xe225767c]=true,[0xb1332141]=true,[0xa76ee4c6]=true,[0x9615b731]=true,[0x18ca9123]=true},actors={
            [0x0143255a]=0xa7f9b6c7,
            [0x0410bac8]=0xe225767c,
            [0x105602e6]=0x8c5570c9,
            [0x1fcfcae3]=0xb4a6064f,
            [0x2434f4a4]=0x9615b731,
            [0x251fe443]=0x8c5570c9,
            [0x285484ce]=0x8c5570c9,
            [0x29ca953e]=0x18ca9123,
            [0x37236374]=0xe9b4fd2d,
            [0x3d43b4b1]=0x8c5570c9,
            [0x43a3844e]=0x8c5570c9,
            [0x470cf2c5]=0xb4a6064f,
            [0x4bca1f07]=0xa7f9b6c7,
            [0x53db7fab]=0x8c5570c9,
            [0x58a98e8a]=0x8c5570c9,
            [0x599c3f71]=0xb1332141,
            [0x7394dd4e]=0xe225767c,
            [0x764e448d]=0x54efdee3,
            [0x84ffdd57]=0x18ca9123,
            [0x8ffb63db]=0xa7f9b6c7,
            [0x918bc99f]=0x8c5570c9,
            [0x9212fdd7]=0x8c5570c9,
            [0x9ee677a7]=0x8c5570c9,
            [0xa7e3257e]=0xb1332141,
            [0xb7ff9cb7]=0x8c5570c9,
            [0xb875a8c9]=0xe90e668d,
            [0xc7134a8c]=0x18ca9123,
            [0xcabc21d4]=0xa76ee4c6,
            [0xcd871ca9]=0xc6b89048,
            [0xcec2d2ea]=0xb4a6064f,
            [0xd48608a6]=0xb1332141,
            [0xdf038f71]=0x9615b731,
            [0xecf00ed4]=0x9615b731,
            [0xee8b6459]=0x78678dbb,
            [0xf2931585]=0xe225767c,
            [0xf8720bf5]=0x8c5570c9,
            [0xfbb9eb3d]=0x8c5570c9,
        }},
    ['\221\175\204\204\242\023\046\158']={name="Bile Titan",nodes=175,bodies=15,finish_disabled=false,main={
        0x9b115563,0xdbd48a04,0x26787c5c,0xae5a7e64,0xdcb76f26,0x1ecb5822,0xc96f8166,0x6e8366df,0x0f5f005b,0x8b9102b4,0xfa1accaf,0x341adbcc,0xd66758f9,0x0f5d4be0,0x12fd8f94},
        disabled_main={},actors={
            [0x004c2c42]=0xdbd48a04,
            [0x039b7f81]=0x21077081,
            [0x10d33410]=0x341adbcc,
            [0x16a59ba2]=0xda85c105,
            [0x19e6fe8a]=0xfa1accaf,
            [0x19f2209c]=0x80e4f7f2,
            [0x1c48292d]=0xfa1accaf,
            [0x23c531ba]=0x6e8366df,
            [0x30e170ff]=0x12fd8f94,
            [0x3be56210]=0xdcb76f26,
            [0x3c46b53c]=0x18dd1e91,
            [0x3c5f0e49]=0xae5a7e64,
            [0x3f30dc56]=0x8b9102b4,
            [0x463a2568]=0x0f5d4be0,
            [0x46423f6e]=0x0f5d4be0,
            [0x47c28216]=0xfa1accaf,
            [0x49a925ae]=0x12fd8f94,
            [0x52d737df]=0x9b115563,
            [0x53db293f]=0xdbd48a04,
            [0x55a57f36]=0x341adbcc,
            [0x55ccc732]=0xd66758f9,
            [0x57b8072f]=0x8c5570c9,
            [0x5a842311]=0xdcb76f26,
            [0x5aadc52d]=0xd66758f9,
            [0x608de44e]=0xc96f8166,
            [0x60f53b5b]=0x1fe1649b,
            [0x651dd67f]=0xc96f8166,
            [0x6a8802b7]=0x1fe1649b,
            [0x6ab1c769]=0x12fd8f94,
            [0x71b2acb6]=0x9b115563,
            [0x7465e8ae]=0xfa1accaf,
            [0x77b2ae41]=0xdbd48a04,
            [0x7ee26daa]=0xd66758f9,
            [0x840ad440]=0x6e8366df,
            [0x89b9e04b]=0x8e1b5638,
            [0x8f13cb1f]=0x0f5f005b,
            [0x903fca3c]=0xc548cf56,
            [0x97f4290d]=0x1ecb5822,
            [0xa01a23bf]=0x9b115563,
            [0xa3dc7cf4]=0x9b115563,
            [0xa482b282]=0xd66758f9,
            [0xa77ec7c7]=0x8b9102b4,
            [0xaa9b9408]=0x0f5f005b,
            [0xb64845ef]=0x18dd1e91,
            [0xb6f6fd4b]=0x0f5f005b,
            [0xb7619f4e]=0x9b115563,
            [0xcac731dd]=0x1ecb5822,
            [0xce53b2c0]=0x1fe1649b,
            [0xd3f3095b]=0xae5a7e64,
            [0xd95fa79e]=0xdbe688f2,
            [0xdb3959e5]=0x12fd8f94,
            [0xe61823ad]=0xad0baf4d,
            [0xef27d4ee]=0x0f5f005b,
            [0xf1f5a7e7]=0x18dd1e91,
        }},
    ['\227\054\040\013\018\141\126\211']={name="Automaton spawner walker",nodes=210,bodies=15,finish_disabled=false,main={
        0x9b115563,0xa3db6464,0x6176721a,0x7f4baf16,0x3811f3cc,0xe4d20fe4,0x45a5d6bd,0x56189626,0x7f397e6d,0xb46dad07,0x6d44c60d,0xc63e0340,0xf0e212f0,0x6de398f6,0xb9b5a67f},
        disabled_main={},actors={
            [0x01ffd62e]=0xf0e212f0,
            [0x039f6e2f]=0xc919e14f,
            [0x03bd6c46]=0xb9b00b54,
            [0x0798ea0b]=0x9b115563,
            [0x0985c473]=0x0017206e,
            [0x0a90fe0c]=0xa3db6464,
            [0x0ba985e6]=0x95333e74,
            [0x0c66ca0e]=0xe4d20fe4,
            [0x0e55ef13]=0xe9ecca21,
            [0x1d167824]=0x6176721a,
            [0x1fb4084c]=0xe4d20fe4,
            [0x2410afc6]=0x9b115563,
            [0x3c48d0c9]=0x1532b593,
            [0x3dc58c92]=0x742da994,
            [0x44d0b43a]=0x7f397e6d,
            [0x45b8cacf]=0x57f106ae,
            [0x4ee68b3c]=0xa4923700,
            [0x5476f807]=0x9b115563,
            [0x55e6b6dd]=0x6176721a,
            [0x5a19e30b]=0xa3db6464,
            [0x5c8d78c7]=0xb122d4b0,
            [0x5cdf5a40]=0xb9b00b54,
            [0x5e44c962]=0xc3034eb8,
            [0x63f3fa41]=0x9b115563,
            [0x69ee871d]=0xc63e0340,
            [0x71290938]=0x7f397e6d,
            [0x74fe2609]=0x063273a4,
            [0x79c05f1c]=0x1fa54006,
            [0x7f16501c]=0xc6b84aef,
            [0x8762b50f]=0x9b115563,
            [0x87e4519b]=0x9b115563,
            [0x8ac8e73d]=0xa4923700,
            [0x8b9f3268]=0x95333e74,
            [0x8e885165]=0x9b115563,
            [0x92744e31]=0x9f6fc899,
            [0x940469dd]=0x3ad27028,
            [0x94451200]=0x9b115563,
            [0x9ea7fa9f]=0x45a5d6bd,
            [0xa0389869]=0x3811f3cc,
            [0xa120e458]=0x6de398f6,
            [0xa93ac296]=0x976d2073,
            [0xaca4ad55]=0x3811f3cc,
            [0xb038f623]=0x9b115563,
            [0xb0b93242]=0x61d12eda,
            [0xb7e47c2b]=0x2c30eee8,
            [0xbb34edee]=0x6d44c60d,
            [0xbdcfda3b]=0xbe9bf707,
            [0xbf3f38bd]=0xd17db882,
            [0xc45a18a3]=0x9b115563,
            [0xc53c7025]=0x976d2073,
            [0xc919245d]=0x747ef0ba,
            [0xcbbfa308]=0x2c30eee8,
            [0xd2dcdd55]=0x9b115563,
            [0xe21afe57]=0x56189626,
            [0xe7306164]=0x7f4baf16,
            [0xeb531a20]=0x6d44c60d,
            [0xf18a6723]=0x56189626,
            [0xf5e59381]=0x9b115563,
            [0xf6aa9cd2]=0xc63e0340,
            [0xfb24a5ea]=0xb46dad07,
            [0xfb53ec91]=0x976d2073,
        }},
    ['\170\250\163\033\164\072\011\150']={name="Terminid dragon",nodes=164,bodies=15,finish_disabled=false,main={
        0x9b115563,0x4b9e7b38,0x668f6a68,0x1030dbaf,0x6891a026,0x9653729b,0x90d91d27,0x6f2c148b,0x71a96497,0xa6585cd3,0xd0db16a9,0x1841c4d5,0x6c288500,0x8cdb60bc,0x220047a7},
        disabled_main={},actors={
            [0x004c2c42]=0xe242c80d,
            [0x039b7f81]=0xcf8445b9,
            [0x10d33410]=0xa6585cd3,
            [0x16a59ba2]=0x68d3fb30,
            [0x19e6fe8a]=0x541fae0e,
            [0x19f2209c]=0x80e4f7f2,
            [0x1b002036]=0x2647e642,
            [0x1c48292d]=0x541fae0e,
            [0x23c531ba]=0x6f2c148b,
            [0x30e170ff]=0x75e05d03,
            [0x3be56210]=0x6891a026,
            [0x3c46b53c]=0x8939410d,
            [0x3c5f0e49]=0x1030dbaf,
            [0x3f30dc56]=0x71a96497,
            [0x408d8403]=0x1841c4d5,
            [0x44016264]=0xd3f287d6,
            [0x463a2568]=0xd0db16a9,
            [0x46423f6e]=0xd0db16a9,
            [0x47c28216]=0x541fae0e,
            [0x49a925ae]=0x75e05d03,
            [0x4b57d58b]=0x8cdb60bc,
            [0x52d737df]=0x9b115563,
            [0x53db293f]=0xe242c80d,
            [0x55a57f36]=0xa6585cd3,
            [0x55ccc732]=0x3523339d,
            [0x57b8072f]=0x8c5570c9,
            [0x5a842311]=0x6891a026,
            [0x5aadc52d]=0x3523339d,
            [0x5e181e2d]=0x7efc7ff4,
            [0x608de44e]=0x90d91d27,
            [0x60f53b5b]=0x2bae612c,
            [0x651dd67f]=0x90d91d27,
            [0x6a8802b7]=0x2bae612c,
            [0x6ab1c769]=0x75e05d03,
            [0x6fa21947]=0xf85a589c,
            [0x71b2acb6]=0x9b115563,
            [0x7465e8ae]=0x541fae0e,
            [0x77b2ae41]=0xe242c80d,
            [0x7ee26daa]=0x3523339d,
            [0x802fe193]=0x6caccdd9,
            [0x840ad440]=0x6f2c148b,
            [0x89b9e04b]=0xc80e43c8,
            [0x8e9de399]=0x8eb0ff62,
            [0x8f13cb1f]=0xfc573edc,
            [0x903fca3c]=0x303f460f,
            [0x97f4290d]=0x9653729b,
            [0xa01a23bf]=0x9b115563,
            [0xa3dc7cf4]=0x9b115563,
            [0xa482b282]=0x3523339d,
            [0xa77ec7c7]=0x71a96497,
            [0xa7c7fa0d]=0x193fe3e3,
            [0xaa9b9408]=0xfc573edc,
            [0xb64845ef]=0x8939410d,
            [0xb6f6fd4b]=0xfc573edc,
            [0xb7619f4e]=0x9b115563,
            [0xc6644231]=0x6c288500,
            [0xc8118f77]=0x3ed1f07b,
            [0xcac731dd]=0x9653729b,
            [0xccb69ff6]=0x220047a7,
            [0xce53b2c0]=0x2bae612c,
            [0xd3f3095b]=0x1030dbaf,
            [0xd95fa79e]=0x0b5fd0b4,
            [0xdb3959e5]=0x75e05d03,
            [0xe61823ad]=0xd2fd31e4,
            [0xef27d4ee]=0xfc573edc,
            [0xf1f5a7e7]=0x8939410d,
        }},
    ['\094\096\171\244\146\035\032\107']={name="Acid Charger",nodes=138,bodies=15,finish_disabled=false,main={
        0x9b115563,0x58d886fb,0x5a4bbaa2,0x1fba9b23,0xacb975d0,0xe411e02e,0x8329f875,0x4014953a,0xc1466369,0xf69f42da,0x73bc7ae4,0xce7e106a,0x38f24831,0xf452db4a,0x9b47948d},
        disabled_main={},actors={
            [0x0be61734]=0x4508030c,
            [0x0c1a03a6]=0x73bc7ae4,
            [0x0f578594]=0x564e8bcc,
            [0x18f490f9]=0xe64ac2fe,
            [0x1e2dfe08]=0x9b47948d,
            [0x1ff1c46a]=0x91c08b37,
            [0x201edb75]=0xe411e02e,
            [0x26480fa9]=0xce7e106a,
            [0x292c4f7f]=0x9b115563,
            [0x36f081c0]=0xf452db4a,
            [0x3e0c625f]=0x8329f875,
            [0x47405e14]=0x38f24831,
            [0x4c1fe16d]=0xc1466369,
            [0x4e884507]=0x9b115563,
            [0x57177953]=0x1fba9b23,
            [0x5f2485fd]=0xf69f42da,
            [0x61a8a415]=0xe411e02e,
            [0x6d151e1b]=0x9b115563,
            [0x6f662c60]=0xacb975d0,
            [0x705c7df3]=0xacb975d0,
            [0x721e0952]=0x73bc7ae4,
            [0x75a5244f]=0x9b47948d,
            [0x82219dbd]=0xb9b5a67f,
            [0x837d120d]=0x58d886fb,
            [0x879c1a75]=0x5a4bbaa2,
            [0x87a058bf]=0x9b115563,
            [0x900f945b]=0x4014953a,
            [0x92117bdc]=0x139899e4,
            [0x929bdf01]=0xb0368f97,
            [0x9738443f]=0xbf117365,
            [0x9ff3e081]=0xc1466369,
            [0xa3d491d1]=0x9b115563,
            [0xbbaa3755]=0x58d886fb,
            [0xbbd1a69d]=0xe64ac2fe,
            [0xc581670e]=0xe38c6308,
            [0xc79200d4]=0x1901e4fb,
            [0xcab4db4c]=0x01172b31,
            [0xd294967b]=0x1fba9b23,
            [0xd90601f5]=0x42831670,
            [0xe3da2507]=0x9b115563,
            [0xe7414eac]=0x9b115563,
            [0xeab0621d]=0xce7e106a,
            [0xf64c750a]=0x42831670,
            [0xf6c42514]=0x58d886fb,
            [0xf6ca3127]=0x9b115563,
            [0xf786b2b4]=0x38f24831,
        }},
    ['\140\034\028\019\043\185\183\010']={name="Burrowing Charger",nodes=129,bodies=15,finish_disabled=false,main={
        0x9b115563,0x58d886fb,0x5a4bbaa2,0x1fba9b23,0xacb975d0,0xe411e02e,0x8329f875,0x4014953a,0xc1466369,0xf69f42da,0x73bc7ae4,0xce7e106a,0x38f24831,0xf452db4a,0x9b47948d},
        disabled_main={},actors={
            [0x0be61734]=0x4508030c,
            [0x0f578594]=0x564e8bcc,
            [0x1e2dfe08]=0x9b47948d,
            [0x1ff1c46a]=0x91c08b37,
            [0x201edb75]=0xe411e02e,
            [0x292c4f7f]=0x9b115563,
            [0x36f081c0]=0xf452db4a,
            [0x3e0c625f]=0x8329f875,
            [0x47405e14]=0x38f24831,
            [0x4c1fe16d]=0xc1466369,
            [0x4e884507]=0x9b115563,
            [0x57177953]=0x1fba9b23,
            [0x5f2485fd]=0xf69f42da,
            [0x6d151e1b]=0x9b115563,
            [0x6f662c60]=0xacb975d0,
            [0x721e0952]=0x73bc7ae4,
            [0x82219dbd]=0xb9b5a67f,
            [0x837d120d]=0x58d886fb,
            [0x879c1a75]=0x5a4bbaa2,
            [0x87a058bf]=0x9b115563,
            [0x900f945b]=0x4014953a,
            [0x92117bdc]=0x139899e4,
            [0x929bdf01]=0xb0368f97,
            [0xa3d491d1]=0x9b115563,
            [0xbbaa3755]=0x58d886fb,
            [0xbbd1a69d]=0xe64ac2fe,
            [0xc581670e]=0xe38c6308,
            [0xc79200d4]=0x1901e4fb,
            [0xc947ded4]=0xbccf91e5,
            [0xcab4db4c]=0x01172b31,
            [0xd90601f5]=0x42831670,
            [0xe3da2507]=0x9b115563,
            [0xe7414eac]=0x9b115563,
            [0xeab0621d]=0xce7e106a,
            [0xf6c42514]=0x58d886fb,
            [0xf6ca3127]=0x9b115563,
        }},
    ['\003\120\137\060\101\071\082\253']={name="Charger bull (unnamed entity variant)",nodes=127,bodies=15,finish_disabled=false,main={
        0x9b115563,0x58d886fb,0x5a4bbaa2,0x1fba9b23,0xacb975d0,0xe411e02e,0x8329f875,0x4014953a,0xc1466369,0xf69f42da,0x73bc7ae4,0xce7e106a,0x38f24831,0xf452db4a,0x9b47948d},
        disabled_main={},actors={
            [0x0be61734]=0x4508030c,
            [0x0f578594]=0x564e8bcc,
            [0x1e2dfe08]=0x9b47948d,
            [0x1ff1c46a]=0x91c08b37,
            [0x201edb75]=0xe411e02e,
            [0x292c4f7f]=0x9b115563,
            [0x36f081c0]=0xf452db4a,
            [0x3e0c625f]=0x8329f875,
            [0x47405e14]=0x38f24831,
            [0x4c1fe16d]=0xc1466369,
            [0x4e884507]=0x9b115563,
            [0x57177953]=0x1fba9b23,
            [0x5f2485fd]=0xf69f42da,
            [0x6d151e1b]=0x9b115563,
            [0x6f662c60]=0xacb975d0,
            [0x721e0952]=0x73bc7ae4,
            [0x82219dbd]=0xb9b5a67f,
            [0x837d120d]=0x58d886fb,
            [0x879c1a75]=0x5a4bbaa2,
            [0x87a058bf]=0x9b115563,
            [0x900f945b]=0x4014953a,
            [0x92117bdc]=0x139899e4,
            [0x929bdf01]=0xb0368f97,
            [0xa3d491d1]=0x9b115563,
            [0xbbaa3755]=0x58d886fb,
            [0xbbd1a69d]=0xe64ac2fe,
            [0xc581670e]=0xe38c6308,
            [0xc79200d4]=0x1901e4fb,
            [0xcab4db4c]=0x01172b31,
            [0xd90601f5]=0x42831670,
            [0xe3da2507]=0x9b115563,
            [0xe7414eac]=0x9b115563,
            [0xeab0621d]=0xce7e106a,
            [0xf6c42514]=0x58d886fb,
            [0xf6ca3127]=0x9b115563,
        }},
    ['\122\034\063\051\226\222\242\048']={name="Automaton jammer spawner walker",nodes=210,bodies=15,finish_disabled=false,main={
        0x9b115563,0xa3db6464,0x6176721a,0x7f4baf16,0x3811f3cc,0xe4d20fe4,0x45a5d6bd,0x56189626,0x7f397e6d,0xb46dad07,0x6d44c60d,0xc63e0340,0xf0e212f0,0x6de398f6,0xb9b5a67f},
        disabled_main={},actors={
            [0x01ffd62e]=0xf0e212f0,
            [0x039f6e2f]=0xc919e14f,
            [0x03bd6c46]=0xb9b00b54,
            [0x0798ea0b]=0x9b115563,
            [0x0985c473]=0x0017206e,
            [0x0a90fe0c]=0xa3db6464,
            [0x0ba985e6]=0x95333e74,
            [0x0c66ca0e]=0xe4d20fe4,
            [0x0e55ef13]=0xe9ecca21,
            [0x1d167824]=0x6176721a,
            [0x1fb4084c]=0xe4d20fe4,
            [0x2410afc6]=0x9b115563,
            [0x3c48d0c9]=0x1532b593,
            [0x3dc58c92]=0x742da994,
            [0x44d0b43a]=0x7f397e6d,
            [0x45b8cacf]=0x57f106ae,
            [0x4ee68b3c]=0xa4923700,
            [0x5476f807]=0x9b115563,
            [0x55e6b6dd]=0x6176721a,
            [0x5a19e30b]=0xa3db6464,
            [0x5c8d78c7]=0xb122d4b0,
            [0x5cdf5a40]=0xb9b00b54,
            [0x5e44c962]=0xc3034eb8,
            [0x63f3fa41]=0x9b115563,
            [0x69ee871d]=0xc63e0340,
            [0x71290938]=0x7f397e6d,
            [0x74fe2609]=0x063273a4,
            [0x79c05f1c]=0x1fa54006,
            [0x7f16501c]=0xc6b84aef,
            [0x8762b50f]=0x9b115563,
            [0x87e4519b]=0x9b115563,
            [0x8ac8e73d]=0xa4923700,
            [0x8b9f3268]=0x95333e74,
            [0x8e885165]=0x9b115563,
            [0x92744e31]=0x9f6fc899,
            [0x940469dd]=0x3ad27028,
            [0x94451200]=0x9b115563,
            [0x9ea7fa9f]=0x45a5d6bd,
            [0xa0389869]=0x3811f3cc,
            [0xa120e458]=0x6de398f6,
            [0xa93ac296]=0x976d2073,
            [0xaca4ad55]=0x3811f3cc,
            [0xb038f623]=0x9b115563,
            [0xb0b93242]=0x61d12eda,
            [0xb7e47c2b]=0x2c30eee8,
            [0xbb34edee]=0x6d44c60d,
            [0xbdcfda3b]=0xbe9bf707,
            [0xbf3f38bd]=0xd17db882,
            [0xc45a18a3]=0x9b115563,
            [0xc53c7025]=0x976d2073,
            [0xc919245d]=0x747ef0ba,
            [0xcbbfa308]=0x2c30eee8,
            [0xd2dcdd55]=0x9b115563,
            [0xe21afe57]=0x56189626,
            [0xe7306164]=0x7f4baf16,
            [0xeb531a20]=0x6d44c60d,
            [0xf18a6723]=0x56189626,
            [0xf5e59381]=0x9b115563,
            [0xf6aa9cd2]=0xc63e0340,
            [0xfb24a5ea]=0xb46dad07,
            [0xfb53ec91]=0x976d2073,
        }},
    ['\136\061\051\056\035\226\033\096']={name="Nursing Spewer mission variant",nodes=99,bodies=14,finish_disabled=false,main={
        0x9b115563,0x0f0196b3,0xc96f8166,0xae5a7e64,0xdcb76f26,0x1ecb5822,0x0f5d4be0,0x12fd8f94,0x341adbcc,0xd66758f9,0x8b9102b4,0xfa1accaf,0x6e8366df,0x0f5f005b},
        disabled_main={},actors={
            [0x312d55bb]=0x0e835875,
            [0x4ea4da87]=0x09a026f5,
            [0x573a0652]=0x1c5f3be4,
            [0xa3d491d1]=0xbccf91e5,
            [0xbc01b5fd]=0x0f0196b3,
        }},
    ['\151\164\151\208\132\203\004\239']={name="Gloom Bile Titan",nodes=175,bodies=15,finish_disabled=false,main={
        0x9b115563,0xdbd48a04,0x26787c5c,0xae5a7e64,0xdcb76f26,0x1ecb5822,0xc96f8166,0x6e8366df,0x0f5f005b,0x8b9102b4,0xfa1accaf,0x341adbcc,0xd66758f9,0x0f5d4be0,0x12fd8f94},
        disabled_main={},actors={
            [0x004c2c42]=0xdbd48a04,
            [0x039b7f81]=0x21077081,
            [0x10d33410]=0x341adbcc,
            [0x16a59ba2]=0xda85c105,
            [0x19e6fe8a]=0xfa1accaf,
            [0x19f2209c]=0x80e4f7f2,
            [0x1c48292d]=0xfa1accaf,
            [0x23c531ba]=0x6e8366df,
            [0x30e170ff]=0x12fd8f94,
            [0x3be56210]=0xdcb76f26,
            [0x3c46b53c]=0x18dd1e91,
            [0x3c5f0e49]=0xae5a7e64,
            [0x3f30dc56]=0x8b9102b4,
            [0x463a2568]=0x0f5d4be0,
            [0x46423f6e]=0x0f5d4be0,
            [0x47c28216]=0xfa1accaf,
            [0x49a925ae]=0x12fd8f94,
            [0x52d737df]=0x9b115563,
            [0x53db293f]=0xdbd48a04,
            [0x55a57f36]=0x341adbcc,
            [0x55ccc732]=0xd66758f9,
            [0x57b8072f]=0x8c5570c9,
            [0x5a842311]=0xdcb76f26,
            [0x5aadc52d]=0xd66758f9,
            [0x608de44e]=0xc96f8166,
            [0x60f53b5b]=0x1fe1649b,
            [0x651dd67f]=0xc96f8166,
            [0x6a8802b7]=0x1fe1649b,
            [0x6ab1c769]=0x12fd8f94,
            [0x71b2acb6]=0x9b115563,
            [0x7465e8ae]=0xfa1accaf,
            [0x77b2ae41]=0xdbd48a04,
            [0x7ee26daa]=0xd66758f9,
            [0x840ad440]=0x6e8366df,
            [0x89b9e04b]=0x8e1b5638,
            [0x8f13cb1f]=0x0f5f005b,
            [0x903fca3c]=0xc548cf56,
            [0x97f4290d]=0x1ecb5822,
            [0xa01a23bf]=0x9b115563,
            [0xa3dc7cf4]=0x9b115563,
            [0xa482b282]=0xd66758f9,
            [0xa77ec7c7]=0x8b9102b4,
            [0xaa9b9408]=0x0f5f005b,
            [0xb64845ef]=0x18dd1e91,
            [0xb6f6fd4b]=0x0f5f005b,
            [0xb7619f4e]=0x9b115563,
            [0xcac731dd]=0x1ecb5822,
            [0xce53b2c0]=0x1fe1649b,
            [0xd3f3095b]=0xae5a7e64,
            [0xd95fa79e]=0xdbe688f2,
            [0xdb3959e5]=0x12fd8f94,
            [0xe61823ad]=0xad0baf4d,
            [0xef27d4ee]=0x0f5f005b,
            [0xf1f5a7e7]=0x18dd1e91,
        }},
    ['\153\011\069\213\215\095\255\058']={name="Charger bull",nodes=127,bodies=15,finish_disabled=false,main={
        0x9b115563,0x58d886fb,0x5a4bbaa2,0x1fba9b23,0xacb975d0,0xe411e02e,0x8329f875,0x4014953a,0xc1466369,0xf69f42da,0x73bc7ae4,0xce7e106a,0x38f24831,0xf452db4a,0x9b47948d},
        disabled_main={},actors={
            [0x0be61734]=0x4508030c,
            [0x0f578594]=0x564e8bcc,
            [0x1e2dfe08]=0x9b47948d,
            [0x1ff1c46a]=0x91c08b37,
            [0x201edb75]=0xe411e02e,
            [0x292c4f7f]=0x9b115563,
            [0x36f081c0]=0xf452db4a,
            [0x3e0c625f]=0x8329f875,
            [0x47405e14]=0x38f24831,
            [0x4c1fe16d]=0xc1466369,
            [0x4e884507]=0x9b115563,
            [0x57177953]=0x1fba9b23,
            [0x5f2485fd]=0xf69f42da,
            [0x6d151e1b]=0x9b115563,
            [0x6f662c60]=0xacb975d0,
            [0x721e0952]=0x73bc7ae4,
            [0x82219dbd]=0xb9b5a67f,
            [0x837d120d]=0x58d886fb,
            [0x879c1a75]=0x5a4bbaa2,
            [0x87a058bf]=0x9b115563,
            [0x900f945b]=0x4014953a,
            [0x92117bdc]=0x139899e4,
            [0x929bdf01]=0xb0368f97,
            [0xa3d491d1]=0x9b115563,
            [0xbbaa3755]=0x58d886fb,
            [0xbbd1a69d]=0xe64ac2fe,
            [0xc581670e]=0xe38c6308,
            [0xc79200d4]=0x1901e4fb,
            [0xcab4db4c]=0x01172b31,
            [0xd90601f5]=0x42831670,
            [0xe3da2507]=0x9b115563,
            [0xe7414eac]=0x9b115563,
            [0xeab0621d]=0xce7e106a,
            [0xf6c42514]=0x58d886fb,
            [0xf6ca3127]=0x9b115563,
        }},
    ['\176\100\198\152\255\205\127\026']={name="Charger",nodes=127,bodies=15,finish_disabled=false,main={
        0x9b115563,0x58d886fb,0x5a4bbaa2,0x1fba9b23,0xacb975d0,0xe411e02e,0x8329f875,0x4014953a,0xc1466369,0xf69f42da,0x73bc7ae4,0xce7e106a,0x38f24831,0xf452db4a,0x9b47948d},
        disabled_main={},actors={
            [0x0be61734]=0x4508030c,
            [0x0f578594]=0x564e8bcc,
            [0x1e2dfe08]=0x9b47948d,
            [0x1ff1c46a]=0x91c08b37,
            [0x201edb75]=0xe411e02e,
            [0x292c4f7f]=0x9b115563,
            [0x36f081c0]=0xf452db4a,
            [0x3e0c625f]=0x8329f875,
            [0x47405e14]=0x38f24831,
            [0x4c1fe16d]=0xc1466369,
            [0x4e884507]=0x9b115563,
            [0x57177953]=0x1fba9b23,
            [0x5f2485fd]=0xf69f42da,
            [0x6d151e1b]=0x9b115563,
            [0x6f662c60]=0xacb975d0,
            [0x721e0952]=0x73bc7ae4,
            [0x82219dbd]=0xb9b5a67f,
            [0x837d120d]=0x58d886fb,
            [0x879c1a75]=0x5a4bbaa2,
            [0x87a058bf]=0x9b115563,
            [0x900f945b]=0x4014953a,
            [0x92117bdc]=0x139899e4,
            [0x929bdf01]=0xb0368f97,
            [0xa3d491d1]=0x9b115563,
            [0xbbaa3755]=0x58d886fb,
            [0xbbd1a69d]=0xe64ac2fe,
            [0xc581670e]=0xe38c6308,
            [0xc79200d4]=0x1901e4fb,
            [0xcab4db4c]=0x01172b31,
            [0xd90601f5]=0x42831670,
            [0xe3da2507]=0x9b115563,
            [0xe7414eac]=0x9b115563,
            [0xeab0621d]=0xce7e106a,
            [0xf6c42514]=0x58d886fb,
            [0xf6ca3127]=0x9b115563,
        }},
    ['\076\172\179\103\236\209\091\160']={name="Charger tier 2",nodes=127,bodies=15,finish_disabled=false,main={
        0x9b115563,0x58d886fb,0x5a4bbaa2,0x1fba9b23,0xacb975d0,0xe411e02e,0x8329f875,0x4014953a,0xc1466369,0xf69f42da,0x73bc7ae4,0xce7e106a,0x38f24831,0xf452db4a,0x9b47948d},
        disabled_main={},actors={
            [0x0be61734]=0x4508030c,
            [0x0f578594]=0x564e8bcc,
            [0x1e2dfe08]=0x9b47948d,
            [0x1ff1c46a]=0x91c08b37,
            [0x201edb75]=0xe411e02e,
            [0x292c4f7f]=0x9b115563,
            [0x36f081c0]=0xf452db4a,
            [0x3e0c625f]=0x8329f875,
            [0x47405e14]=0x38f24831,
            [0x4c1fe16d]=0xc1466369,
            [0x4e884507]=0x9b115563,
            [0x57177953]=0x1fba9b23,
            [0x5f2485fd]=0xf69f42da,
            [0x6d151e1b]=0x9b115563,
            [0x6f662c60]=0xacb975d0,
            [0x721e0952]=0x73bc7ae4,
            [0x82219dbd]=0xb9b5a67f,
            [0x837d120d]=0x58d886fb,
            [0x879c1a75]=0x5a4bbaa2,
            [0x87a058bf]=0x9b115563,
            [0x900f945b]=0x4014953a,
            [0x92117bdc]=0x139899e4,
            [0x929bdf01]=0xb0368f97,
            [0xa3d491d1]=0x9b115563,
            [0xbbaa3755]=0x58d886fb,
            [0xbbd1a69d]=0xe64ac2fe,
            [0xc581670e]=0xe38c6308,
            [0xc79200d4]=0x1901e4fb,
            [0xcab4db4c]=0x01172b31,
            [0xd90601f5]=0x42831670,
            [0xe3da2507]=0x9b115563,
            [0xe7414eac]=0x9b115563,
            [0xeab0621d]=0xce7e106a,
            [0xf6c42514]=0x58d886fb,
            [0xf6ca3127]=0x9b115563,
        }},
}
for _,p in pairs(profiles) do
    p.main_names={};for _,name in ipairs(p.main) do p.main_names[name]=true end
end
-- END GENERATED PROFILES
local claws = {[0x92d0871f]=true,[0x6635646b]=true,[0x50b19c0a]=true}

local ffi,bit=require('ffi'),require('bit')
local M={profiles=profiles,interval=1/30,max_entities=128,max_units=4,budget_seconds=.001}
M.completion_grace=1
local ZERO8=string.rep('\0',8)
local words={uint32_t=ffi.new('uint32_t[1]'),float=ffi.new('float[1]')}
local matrix_words=ffi.new('float[16]')
local function scalar(bytes,offset,kind)
    assert(offset>=0 and offset+4<=#bytes,'Scalar outside copied data')
    local value=words[kind]
    ffi.copy(value,ffi.cast('const uint8_t *',bytes)+offset,4)
    return tonumber(value[0])
end
-- Little-endian decode from the copied bytes. Unlike an FFI cast, this makes
-- no cdata object when the interpreter, not a compiled trace, runs it.
local function u32(b,o)
    o=o or 0
    assert(o>=0 and o+4<=#b,'Scalar outside copied data')
    local b1,b2,b3,b4=string.byte(b,o+1,o+4)
    return b1+b2*256+b3*65536+b4*16777216
end
local function f32(b,o) return scalar(b,o,'float') end
local function floats(b,o,n)
    assert(o>=0 and n<=16 and o+n*4<=#b,'Matrix outside copied data')
    -- Finish the bounded copy before allocating the result table. No borrowed
    -- pointer into a Lua string needs to survive allocations or a GC step.
    ffi.copy(matrix_words,ffi.cast('const uint8_t *',b)+o,n*4)
    local out={};for i=1,n do out[i]=tonumber(matrix_words[i-1]) end;return out
end
local function phase(api,name)
    if api.profiler then return api.profiler.phase(name) end
end
local function detail(api,name)
    if api.profiler then api.profiler.detail(name) end
end
local function finite(n) return type(n)=='number' and n==n and math.abs(n)<100000 end

-- Havok body translations and unit matrices use the same world-space node
-- origin. Shape-local geometry remains in the existing shape. Remove skeletal
-- scale from the orientation; do not resize or replace a collision shape.
local RIGID_FIELDS={1,2,3,5,6,7,9,10,11,13,14,15}
local function unit3(a,b,c)
    local n=math.sqrt(a*a+b*b+c*c);if not finite(n) or n<0.001 then return nil end
    return a/n,b/n,c/n
end
-- Numeric core of M.rigid: position XYZ then quaternion XYZW, or nil. It builds
-- no tables, so poses that turn out aligned cost no garbage. Same arithmetic,
-- in the same order, as the table form it replaced.
local function rigid_values(matrix)
    for i=1,12 do if not finite(matrix[RIGID_FIELDS[i]]) then return nil end end
    local x1,x2,x3=unit3(matrix[1],matrix[2],matrix[3]);if not x1 then return nil end
    local y1,y2,y3=unit3(matrix[5],matrix[6],matrix[7]);if not y1 then return nil end
    local z1,z2,z3=unit3(matrix[9],matrix[10],matrix[11]);if not z1 then return nil end
    if math.abs(x1*y1+x2*y2+x3*y3)>.025 or math.abs(x1*z1+x2*z2+x3*z3)>.025
        or math.abs(y1*z1+y2*z2+y3*z3)>.025 then return nil end
    local c1,c2,c3=x2*y3-x3*y2,x3*y1-x1*y3,x1*y2-x2*y1
    if c1*z1+c2*z2+c3*z3<.99 then return nil end
    -- Column-major matrix to XYZW quaternion.
    local trace=x1+y2+z3
    local s,a,b,c,d
    if trace>0 then
        s=math.sqrt(trace+1)*2;a,b,c,d=(y3-z2)/s,(z1-x3)/s,(x2-y1)/s,s/4
    elseif x1>y2 and x1>z3 then
        s=math.sqrt(1+x1-y2-z3)*2;a,b,c,d=s/4,(y1+x2)/s,(z1+x3)/s,(y3-z2)/s
    elseif y2>z3 then
        s=math.sqrt(1+y2-x1-z3)*2;a,b,c,d=(y1+x2)/s,s/4,(z2+y3)/s,(z1-x3)/s
    else
        s=math.sqrt(1+z3-x1-y2)*2;a,b,c,d=(z1+x3)/s,(z2+y3)/s,s/4,(x2-y1)/s
    end
    local length=math.sqrt(a^2+b^2+c^2+d^2)
    if not finite(length) or length<.001 then return nil end
    return matrix[13],matrix[14],matrix[15],a/length,b/length,c/length,d/length
end

function M.rigid(matrix)
    if type(matrix)~='table' or #matrix~=16 then return nil end
    local px,py,pz,qx,qy,qz,qw=rigid_values(matrix)
    if not px then return nil end
    return {px,py,pz},{qx,qy,qz,qw}
end

local function settled(unit)
    local profile=profiles[unit.resource]
    return profile and unit.settled and unit.main_enabled~=nil
        and unit.main_enabled+(unit.main_disabled or 0)==profile.bodies
        and unit.main_static==unit.main_enabled
end

local function command_guards(actor)
    -- Most inspected auxiliaries already align and never receive a command.
    -- Keep their copied guard bytes compact until a real action needs the
    -- usual fresh identity/motion checks. This never rereads stale addresses.
    local b=actor.guard_source
    if not actor.guards and b then
        -- b[6] is the whole 160-byte body copied this poll; slice its motion
        -- and identity words exactly as they were read.
        actor.guards={{address=b[1],bytes=b[2]},{address=b[3],bytes=b[4]},
            {address=b[5]+64,bytes=b[6]:sub(65,68)},{address=b[5]+144,bytes=b[6]:sub(145,152)}}
    end
end

function M.plan(unit)
    local profile=profiles[unit.resource]
    -- Recorded assault-walker Corpses retain a dynamic torso and rocket pods.
    -- They must not block auxiliary repair on the fixed base. This exception
    -- is Corpse-only; it never relaxes RagdollSync stopping/completion gates.
    local mixed=profile and profile.corpse_dynamic_main and unit.corpse and unit.settled
        and unit.main_enabled~=nil and unit.main_enabled+(unit.main_disabled or 0)==profile.bodies
        and unit.main_static>0 and unit.main_static+(unit.main_dynamic_allowed or 0)==unit.main_enabled
    if not settled(unit) and not mixed then return {} end
    local actions={}
    for _,a in ipairs(unit.actors) do
        if a.enabled and a.stable and not a.registered and profile.actors[a.name]==a.node_hash then
            if profile.name=='Impaler' and claws[a.name] then
                command_guards(a)
                actions[#actions+1]={kind='disable',actor=a}
            elseif a.motion==0 and a.pose~=a.node_pose then
                local px,py,pz,qx,qy,qz,qw=rigid_values(a.node_pose)
                local ox,oy,oz,rx,ry,rz,rw=rigid_values(a.pose)
                if px and ox then
                    local distance=math.sqrt((px-ox)^2+(py-oy)^2+(pz-oz)^2)
                    local rotation=math.abs(qx*rx+qy*ry+qz*rz+qw*rw)
                    -- 2.5 cm / half a degree avoid rewriting an already aligned
                    -- stationary corpse. There is no upper gap cutoff: the
                    -- recorded 27 m failure must remain repairable.
                    if distance>.025 or rotation<.9999904807207345 then
                        command_guards(a)
                        actions[#actions+1]={kind='pose',actor=a,position={px,py,pz},rotation={qx,qy,qz,qw},
                            gap=distance,degrees=math.deg(2*math.acos(math.min(1,rotation)))}
                    end
                end
            end
        end
    end
    return actions
end

local byte=string.byte
-- Compares expected bytes with a copied block at offset without creating a
-- substring. Copied game data is unique per poll, so every :sub() allocated.
local function ranges_equal(a,a_offset,b,b_offset,n)
    if a_offset<0 or b_offset<0 or a_offset+n>#a or b_offset+n>#b then return false end
    for i=1,n do if byte(a,a_offset+i)~=byte(b,b_offset+i) then return false end end
    return true
end
local function matches(block,offset,expected) return ranges_equal(block,offset,expected,0,#expected) end
M.matches=matches
-- The same comparison against a scratch view of `size` copied bytes.
local function view_matches(view,size,offset,expected)
    local n=#expected
    if offset<0 or offset+n>size then return false end
    for i=1,n do if view[offset+i-1]~=byte(expected,i) then return false end end
    return true
end
-- One guard against fresh game bytes: through the view when the adapter has
-- one (no Lua string), otherwise through an ordinary read.
local function viewable(api) return api.view~=nil and api.view_read==api.read end
local function unchanged(api,g)
    local n=#g.bytes
    if viewable(api) then
        local view=api.view(g.address,n)
        return view~=nil and view_matches(view,n,0,g.bytes)
    end
    return api.read(g.address,n)==g.bytes
end

-- Grouping plan for one guard list, kept as parallel number arrays rather than
-- a table per guard. The list's entries and their address/bytes are recorded,
-- so any change to the list forces a fresh plan exactly as before.
local function compile(api,guards)
    local n=#guards
    local c={count=n,entries={},addresses={},bytes={},numbers={},order={},first={},last={},start={},size={}}
    local numbers,order=c.numbers,c.order
    for i=1,n do
        local g=guards[i]
        c.entries[i]=g;c.addresses[i]=g.address;c.bytes[i]=g.bytes
        numbers[i]=api.address(g.address);order[i]=i
    end
    table.sort(order,function(a,b) return numbers[a]<numbers[b] end)
    local groups=0
    for k=1,n do
        local i=order[k]
        local number,length=numbers[i],#guards[i].bytes
        if groups==0 or number>c.start[groups]+c.size[groups]+128 or number+length-c.start[groups]>4096 then
            groups=groups+1;c.first[groups]=k;c.start[groups]=number;c.size[groups]=length
        else c.size[groups]=math.max(c.size[groups],number+length-c.start[groups]) end
        c.last[groups]=k
    end
    c.groups=groups
    return c
end

local function current(compiled,guards)
    if not compiled or compiled.count~=#guards then return false end
    for i=1,compiled.count do
        local g=guards[i]
        if g~=compiled.entries[i] or g.address~=compiled.addresses[i] or g.bytes~=compiled.bytes[i] then return false end
    end
    return true
end

local function same(api,guards)
    local previous=phase(api,'validation')
    local result=true
    if not api.address or #guards<2 then
        for _,g in ipairs(guards) do if not unchanged(api,g) then result=false;break end end
        phase(api,previous);return result
    end
    local compiled=guards.compiled
    if not current(compiled,guards) then compiled=compile(api,guards);guards.compiled=compiled end
    local order,numbers=compiled.order,compiled.numbers
    for group=1,compiled.groups do
        local start,size=compiled.start[group],compiled.size[group]
        local address=guards[order[compiled.first[group]]].address
        local view=viewable(api) and api.view(address,size) or nil
        local block=not view and api.read(address,size)
        local whole=view~=nil or (block and #block==size)
        for k=compiled.first[group],compiled.last[group] do
            local check=guards[order[k]]
            local ok
            if view then ok=view_matches(view,size,numbers[order[k]]-start,check.bytes)
            elseif whole then ok=matches(block,numbers[order[k]]-start,check.bytes)
            else ok=unchanged(api,check) end
            if not ok then result=false;break end
        end
        if not result then break end
    end
    phase(api,previous);return result
end
M.same=same

local function separation(p,q,old,oldq)
    local distance=math.sqrt((p[1]-old[1])^2+(p[2]-old[2])^2+(p[3]-old[3])^2)
    local cosine=math.min(1,math.abs(q[1]*oldq[1]+q[2]*oldq[2]+q[3]*oldq[3]+q[4]*oldq[4]))
    return distance,math.deg(2*math.acos(cosine))
end

local function relative(p,q,r,rq)
    -- Inverse root rotation applied to the displacement, and conjugate(root)
    -- multiplied by body rotation. A coherent whole-corpse turn is not flapping.
    local x,y,z,w=-rq[1],-rq[2],-rq[3],rq[4]
    local dx,dy,dz=p[1]-r[1],p[2]-r[2],p[3]-r[3]
    local tx,ty,tz=2*(y*dz-z*dy),2*(z*dx-x*dz),2*(x*dy-y*dx)
    return {dx+w*tx+y*tz-z*ty,dy+w*ty+z*tx-x*tz,dz+w*tz+x*ty-y*tx},
        {w*q[1]+x*q[4]+y*q[3]-z*q[2],w*q[2]-x*q[3]+y*q[4]+z*q[1],
         w*q[3]+x*q[2]-y*q[1]+z*q[4],w*q[4]-x*q[1]-y*q[2]-z*q[3]}
end

-- Client-side containment of motion restarting after a fixed corpse has had
-- time to settle. History contains numeric identities and copied poses only.
-- A fixed flag alone is insufficient: the recording includes normal final
-- corrections after that transition, before the root becomes stationary.
function M.fling_action(unit,state,now)
    state.fling_history=state.fling_history or {}
    local history=state.fling_history
    local key=unit.unit
    local root=unit.root_body
    local profile=profiles[unit.resource]
    if not settled(unit) or unit.corpse or unit.owner~=false
        or unit.active~=true or unit.update_enabled~=true then
        if key then history[key]=nil end
        return nil
    end
    -- Tripod settings intentionally disable every main actor on landing.
    -- Once this completed fixed state persists, finish through the same native
    -- stop/owner route. Never read disabled Havok bodies or resurrect collision.
    if profile.finish_disabled and unit.main_enabled==0 then
        local previous=history[key]
        if not previous or not previous.disabled or previous.entity~=unit.id
            or previous.resource~=unit.resource or previous.members~=unit.main_signature
            or now<=previous.last or now-previous.last>1 then
            history[key]={disabled=true,entity=unit.id,resource=unit.resource,
                members=unit.main_signature,since=now,last=now,samples=1}
        else
            previous.last=now;previous.samples=previous.samples+1
            if previous.samples>=3 and now-previous.since>=1 then
                return {distance=0,degrees=0,actor=unit.root_id,cause='landed_disabled'}
            end
        end
        return nil
    end
    if not root then history[key]=nil;return nil end
    local p,q=M.rigid(root.pose)
    if not p then history[key]=nil;return nil end
    if not unit.main_bodies or #unit.main_bodies~=unit.main_enabled then history[key]=nil;return nil end
    local limbs={}
    for _,body in ipairs(unit.main_bodies) do
        local bp,bq=M.rigid(body.pose)
        if not bp or limbs[body.id] then history[key]=nil;return nil end
        local rp,rq=relative(bp,bq,p,q)
        limbs[body.id]={position=rp,rotation=rq}
    end
    if not limbs[root.id] then history[key]=nil;return nil end
    local previous=history[key]
    if not previous or previous.entity~=unit.id or previous.resource~=unit.resource
        or previous.actor~=root.id or previous.members~=unit.main_signature or previous.enabled~=unit.main_enabled
        or now<=previous.last or now-previous.last>1 then
        history[key]={entity=unit.id,resource=unit.resource,actor=root.id,members=unit.main_signature,
            enabled=unit.main_enabled,position=p,rotation=q,limbs=limbs,since=now,last=now,samples=1,armed=false}
        return nil
    end
    previous.last=now;previous.samples=previous.samples+1
    local distance,degrees=separation(p,q,previous.position,previous.rotation)
    if previous.armed then
        -- Experimental containment thresholds, not engine-defined limits.
        if distance>.75 or degrees>20 then
            return {distance=distance,degrees=degrees,actor=root.id,
                cause=distance>.75 and 'translation' or 'rotation'}
        end
        previous.excursions=previous.excursions or {}
        for _,body in ipairs(unit.main_bodies) do
            local current,old=limbs[body.id],previous.limbs[body.id]
            if not old then history[key]=nil;return nil end
            local ld,la=separation(current.position,current.rotation,old.position,old.rotation)
            if body.id~=root.id and (ld>.5 or la>15) then
                local started=previous.excursions[body.id]
                if started and now-started>=.1 then
                    return {distance=distance,degrees=degrees,actor=body.id,
                        limb_distance=ld,limb_degrees=la,
                        cause=ld>.5 and 'limb_translation' or 'limb_rotation'}
                end
                previous.excursions[body.id]=started or now
            else previous.excursions[body.id]=nil end
        end
    elseif distance>.25 or degrees>10 then
        previous.position=p;previous.rotation=q;previous.limbs=limbs
        previous.since=now;previous.samples=1
    elseif previous.samples>=3 and now-previous.since>=1 then
        previous.armed=true;state.fling_armed=(state.fling_armed or 0)+1
    end
    return nil
end

local function checked_world(api,exe,index,read,state)
    local reference=read(exe+0x27ba8a8+176*index,8)
    if reference==ZERO8 then return nil end
    local world=assert(api.pointer(reference),'Physics world unavailable')
    local vt=assert(api.pointer(read(world,8)),'Physics vtable unavailable')
    local getter=assert(api.pointer(read(vt+136,8)),'Physics getter unavailable')
    local offset=api.distance(getter,exe)
    if offset~=0xd0cfa0 then
        state.getter_failures=(state.getter_failures or 0)+1
        state.last_getter_failure=string.format(
            'Body getter changed: world_index=%d world=%.0f vtable=%.0f actual=%.0f expected=%.0f offset=%.0f',
            index,api.address(world),api.address(vt),api.address(getter),api.address(exe+0xd0cfa0),offset)
        error(state.last_getter_failure)
    end
    state.getter_checks=(state.getter_checks or 0)+1
    return world
end

function M.snapshot(api,game,exe,state,consume,budget)
    phase(api,'discovery')
    local cache,worlds,body_arrays,pools,used,calls={},{},{},{},0,0
    local function read(address,size)
        assert(size>0 and size<=32768,'Read size outside bounds')
        used=used+size;calls=calls+1
        assert(used<=4*1024*1024 and calls<=18000,'Snapshot budget exceeded')
        local b=assert(api.read(address,size),'Data unavailable');assert(#b==size,'Short read');return b
    end
    local function cached(address,size,optional)
        local key=api.address(address)
        local sizes=cache[key]
        if not sizes then sizes={};cache[key]=sizes end
        if sizes[size]==nil then
            if optional then
                local ok,bytes=pcall(read,address,size);sizes[size]=ok and bytes or false
            else sizes[size]=read(address,size) end
        end
        return sizes[size] or nil
    end
    local function pointer(b,o) return assert(api.pointer(b,o),'Pointer unavailable') end
    -- These decoded values share the existing copied-byte cache's lifetime:
    -- one snapshot/poll only. Actor/body identities and mutation guards remain
    -- fresh. No resolved address is retained in state or across polls.
    local function world_for(index)
        local world=worlds[index]
        if world~=nil then
            if world then state.getter_checks=(state.getter_checks or 0)+1 end
            return world or nil
        end
        world=checked_world(api,exe,index,cached,state)
        worlds[index]=world or false
        state.world_metadata_decodes=(state.world_metadata_decodes or 0)+1
        return world
    end
    local function pool_for(index)
        local pool=pools[index]
        if not pool then
            local b=cached(exe+0x2369b00+64*index,56)
            local layout=u32(b,28)
            pool={base=pointer(b),count=u32(b,36),mask=u32(b,40),generation=u32(b,52),
                stride=bit.band(layout,65535),identity_offset=bit.band(bit.rshift(layout,16),255),data_offset=bit.rshift(layout,24)}
            pools[index]=pool
            state.pool_metadata_decodes=(state.pool_metadata_decodes or 0)+1
        end
        return pool
    end
    local function ptr(address) return pointer(read(address,8)) end
    local function guard(list,address,size)
        local b=read(address,size);list[#list+1]={address=address,bytes=b};return b
    end
    -- This read-only preflight also runs on the ship. It uses the exact getter
    -- path used by the corpse reader, so validation need not wait for a death.
    -- World 2 hosts the captured enemy actors; absence during loading is normal.
    state.preflight_getter='checking'
    local world=world_for(2)
    state.preflight_getter=world and 'verified' or 'waiting_for_world'
    local mode_reference=api.read(game+0x33266a0,8)
    local mode=api.pointer(mode_reference)
    state.mission_flag=0;state.mode_field_40=0
    if not mode then return {},'waiting_for_mission' end
    local mode_bytes=read(mode,0x44)
    state.mission_flag=u32(mode_bytes,8);state.mode_field_40=u32(mode_bytes,0x40)
    -- The recorded client mission had +8=1 and +0x40=2. Back on the ship,
    -- +8 became zero while +0x40 stayed 2. Do not use that second field as
    -- a mission selector; entity/profile/lifecycle guards remain mandatory.
    if state.mission_flag==0 then return {},'waiting_for_mission' end
    local result={}
    state.cursors=state.cursors or {}
    -- Alternate first ownership of the shared budget so neither manager can
    -- starve the other. Cursors are indices only; pointers are always reread.
    state.manager_turn=not state.manager_turn
    local order=state.manager_turn and {false,true} or {true,false}
    for _,corpse in ipairs(order) do
        phase(api,'discovery')
        local manager_name=corpse and 'corpse' or 'ragdoll'
        local globals,selected={},{}
        local manager=pointer(guard(globals,game+(corpse and 0x3326920 or 0x3326948),8))
        local h=guard(globals,manager,88)
        local capacity,count,active=u32(h,corpse and 16 or 4),u32(h,corpse and 24 or 12),u32(h,corpse and 28 or 16)
        state[manager_name..'_count']=count
        assert(active<=count and count<=capacity and capacity<=8192 and count<=(corpse and 512 or 2048),'Manager bounds changed')
        if not corpse then assert(u32(h,20)<=active,'Owner partition changed') end
        if count>0 then
            local entities,runtime,sync=pointer(h,corpse and 64 or 56),pointer(h,72),pointer(h,80)
            local pointers=read(entities,count*8)
            local start=(state.cursors[manager_name] or 0)%count
            for step=0,count-1 do
                if budget and (budget.scanned>=M.max_entities or budget.inspected>=M.max_units
                    or (budget.scanned>0 and api.clock and api.clock()>=budget.deadline)) then
                    budget.yielded=true;break
                end
                local index=(start+step)%count
                state.cursors[manager_name]=(index+1)%count
                if budget then budget.scanned=budget.scanned+1 end
                local entity=api.pointer(pointers,index*8)
                local e=entity and api.read(entity,24)
                local profile=e and profiles[e:sub(1,8)]
                if profile then
                    -- Lifecycle rejection is cheap; inspect it before counting
                    -- against the expensive-unit limit or reading any skeleton.
                    local r=not corpse and runtime+index*11192
                    local quick=r and api.read(sync+index*432,4)
                    local eligible=corpse or (quick and #quick==4 and u32(quick)==profile.bodies)
                    if eligible then
                    if budget then budget.inspected=budget.inspected+1 end
                    phase(api,'snapshot')
                    detail(api,'metadata')
                    local profile_start=api.profiler and api.clock()
                    local profile_reads=api.profiler and api.profiler.reads
                    local ok,unit=pcall(function()
                        local u={resource=e:sub(1,8),id=u32(e,8),unit=u32(e,12),corpse=corpse,
                            owner=bit.band(u32(e,20),1)~=0,active=index<active,manager=manager,index=index,
                            guards={},main={},main_bodies={},main_pose_guards={},registered={},actors={},
                            main_enabled=0,main_static=0,main_disabled=0,main_dynamic_allowed=0}
                        u.guards[#u.guards+1]={address=entity,bytes=e}
                        u.guards[#u.guards+1]={address=game+0x33266a0,bytes=mode_reference}
                        u.guards[#u.guards+1]={address=mode+8,bytes=mode_bytes:sub(9,12)}
                        u.guards[#u.guards+1]={address=entities+index*8,bytes=pointers:sub(index*8+1,index*8+8)}
                        if not corpse then
                            local r=runtime+index*11192
                            local meta=guard(u.guards,r+11160,32)
                            if u32(meta,0)~=profile.bodies or meta:byte(13)>1 or meta:byte(14)~=0 or meta:sub(17,24)~=ZERO8 then return nil end
                            u.update_enabled=meta:byte(13)==1;u.update_address=r+11172
                            local s=sync+index*432
                            local pc,rc,flag=guard(u.guards,s,4),guard(u.guards,s+184,4),guard(u.guards,s+428,1)
                            if u32(pc)~=profile.bodies or u32(rc)~=profile.bodies or flag:byte()~=0 then return nil end
                            local b=read(r,profile.bodies*712)
                            local members={}
                            for i=0,profile.bodies-1 do
                                local id=u32(b,i*712)
                                assert(id~=0xffffffff and not u.main[id],'Invalid main actor membership')
                                u.main[id]=profile.main[i+1];u.registered[id]=true
                                members[#members+1]=tostring(id);if i==0 then u.root_id=id end
                                u.guards[#u.guards+1]={address=r+i*712,bytes=b:sub(i*712+1,i*712+8)}
                                local n=u32(b,i*712+12);assert(n<=9,'Sub-actor bounds changed')
                                for j=0,n-1 do u.registered[u32(b,i*712+28+j*76)]=true end
                            end
                            u.main_signature=table.concat(members,':')
                        end
                        u.settled=true
                        detail(api,'skeleton')
                        local registry=pointer(guard(u.guards,exe+0x1a100f0,8))
                        local uh=cached(registry,0xa8);local slot_index=u.unit%0x400000
                        assert(slot_index<u32(uh,0x98),'Unit index changed')
                        local gen_address=pointer(uh,0xa0)+slot_index
                        assert(guard(u.guards,gen_address,1)==string.char(math.floor(u.unit/0x400000)),'Unit generation changed')
                        local slot=pointer(uh,0x88)+slot_index*8
                        local object=pointer(guard(u.guards,slot,8))
                        assert(u32(guard(u.guards,object+8,4))==u.unit,'Unit identity changed')
                        local node_count=u32(guard(u.guards,object+0x70,4))
                        assert(node_count==profile.nodes,'Skeleton changed')
                        local node_pointer=pointer(guard(u.guards,object+0x88,8))
                        local nodes=read(node_pointer,node_count*64)
                        local node_matrices={}
                        detail(api,'actors')
                        local list=pointer(guard(u.guards,exe+0x27c5b40,8))+slot_index*24
                        local ah=guard(u.guards,list,24);local flags=u32(ah,4)
                        assert(bit.band(flags,0x40000000)~=0 and bit.band(u32(ah),0x3fffffff)==u.unit,'Actor list identity changed')
                        local n=bit.band(flags,127)
                        if n==0 then return nil end
                        local actor_pointer=bit.band(flags,0x80000000)~=0 and list+8 or pointer(ah,8)
                        local handles=guard(u.guards,actor_pointer,n*4)
                        local main_names={}
                        for i=0,n-1 do
                            detail(api,'actors')
                            local id=u32(handles,i*4)
                            if id~=0xffffffff then
                                local pool=pool_for(bit.band(bit.rshift(id,28),3)+10*bit.rshift(id,30))
                                local ai=bit.band(id,pool.mask)
                                assert(ai<pool.count and bit.band(id,pool.generation)~=0,'Expired actor')
                                local stride=pool.stride
                                local entry=pool.base+ai*stride
                                local identity_offset,data_offset=pool.identity_offset,pool.data_offset
                                local identity_address,address=entry+identity_offset,entry+data_offset
                                local identity,ar
                                if stride<=256 and identity_offset+4<=stride and data_offset+40<=stride then
                                    local first=ai-ai%16
                                    local size=math.min(16,pool.count-first)*stride
                                    -- Actor rows may be copied together. Havok bodies must
                                    -- remain individual: disabled body slots are off-limits.
                                    local rows=cached(pool.base+first*stride,size,true)
                                    if rows then
                                        local base=(ai-first)*stride
                                        identity=rows:sub(base+identity_offset+1,base+identity_offset+4)
                                        ar=rows:sub(base+data_offset+1,base+data_offset+40)
                                    end
                                end
                                if not ar then identity=read(identity_address,4);ar=read(address,40) end
                                assert(u32(identity)==id,'Actor generation changed')
                                assert(u32(ar,12)==u.unit,'Actor owner changed')
                                local name,node=u32(ar,24),u32(ar,28)
                                local enabled=bit.band(u32(ar,16),1)~=0
                                local is_main=corpse and profile.main_names[name] or u.main[id]
                                if is_main then
                                    assert((corpse or name==u.main[id]) and not main_names[name], 'Main actor names changed')
                                    main_names[name]=true
                                    u.guards[#u.guards+1]={address=address,bytes=ar}
                                    u.guards[#u.guards+1]={address=identity_address,bytes=identity}
                                    if not enabled and profile.disabled_main[name] then u.main_disabled=u.main_disabled+1 end
                                end
                                -- Disabled tentacles can retain differently tagged body IDs.
                                -- They are never repair targets. Skip their bodies entirely;
                                -- Undeclared disabled primaries still block settlement.
                                if enabled then
                                    detail(api,'bodies')
                                    local world_index=bit.rshift(id,30)
                                    local world=assert(world_for(world_index),'Physics world unavailable')
                                    local bi=bit.band(u32(ar,20),0xffffff);assert(bi<262144,'Body index changed')
                                    local base=body_arrays[world_index]
                                    if not base then base=pointer(cached(world+24,8));body_arrays[world_index]=base end
                                    local body_address=base+160*bi
                                    local body=read(body_address,160);local motion=u32(body,64)
                                    assert(u32(body,144)==id and u32(body,148)==u.unit,'Physics body identity changed')
                                    local filter=bit.band(u32(body,108),127)
                                    if is_main then
                                        u.main_enabled=u.main_enabled+1
                                        u.main_static=u.main_static+(motion==0 and 1 or 0)
                                        if corpse and motion~=0 and profile.corpse_dynamic_main and profile.corpse_dynamic_main[name] then
                                            u.main_dynamic_allowed=u.main_dynamic_allowed+1
                                        end
                                        u.guards[#u.guards+1]={address=body_address+64,bytes=body:sub(65,68)}
                                        u.guards[#u.guards+1]={address=body_address+144,bytes=body:sub(145,152)}
                                        local pose_guard={address=body_address,bytes=body:sub(1,64)}
                                        u.main_pose_guards[#u.main_pose_guards+1]=pose_guard
                                        -- Corpse-phase planning uses primary identity/motion,
                                        -- not decoded primary transforms. Keep every guard.
                                        local main_body={id=id,pose=not corpse and floats(body,0,16) or nil,guards={pose_guard}}
                                        u.main_bodies[#u.main_bodies+1]=main_body
                                        if id==u.root_id then u.root_body=main_body end
                                    end
                                    local registered=u.registered[id] or is_main or filter==52 or filter==48 or filter==83
                                    local node_hash=u32(ar,32)
                                    local claw=profile.name=='Impaler' and claws[name]
                                    -- Build a record only for an actor M.plan could act on:
                                    -- the same authored-mapping, registration, claw and
                                    -- static-body tests it applies. A static body whose bytes
                                    -- equal its node is already aligned (M.plan compares the
                                    -- identical table and skips it), so it needs no record.
                                    if profile.actors[name] and node<node_count and not registered
                                        and profile.actors[name]==node_hash
                                        and (claw or (motion==0 and not ranges_equal(nodes,node*64,body,0,64))) then
                                        local node_pose=node_matrices[node]
                                        if not node_pose then
                                            node_pose=floats(nodes,node*64,16);node_matrices[node]=node_pose
                                        end
                                        -- Copied matrices are immutable during the poll.
                                        -- Exact byte equality proves no pose repair is due;
                                        -- all nonidentical matrices retain the rigid checks.
                                        local pose=ranges_equal(nodes,node*64,body,0,64) and node_pose or floats(body,0,16)
                                        -- The copied body block is kept whole; command_guards
                                        -- slices the same bytes only if a command needs them.
                                        local a={id=id,name=name,node=node,node_hash=node_hash,enabled=enabled,motion=motion,
                                            registered=registered,pose=pose,node_pose=node_pose,
                                            guard_source={identity_address,identity,address,ar,body_address,body}}
                                        -- Validate fresh identity/motion again at command
                                        -- dispatch. Aligned actors need no extra read pass.
                                        a.stable=true;u.actors[#u.actors+1]=a
                                    end
                                end
                            end
                        end
                        if not same(api,u.guards) then return nil end
                        return u
                    end)
                    if ok and unit then
                        if consume then
                            if same(api,globals) then
                                for _,g in ipairs(globals) do unit.guards[#unit.guards+1]=g end
                                consume(unit)
                            else
                                if state.fling_history then state.fling_history[unit.unit]=nil end
                                state.skipped=(state.skipped or 0)+1
                            end
                        else selected[#selected+1]=unit end
                    elseif not ok then state.skipped=(state.skipped or 0)+1;state.last_skip=tostring(unit) end
                    if (not ok or not unit) and state.fling_history then state.fling_history[u32(e,12)]=nil end
                    if api.profiler then api.profiler.unit(profile.name,profile_start,profile_reads,ok and unit or nil) end
                    else
                        if state.fling_history then state.fling_history[u32(e,12)]=nil end
                    end
                    phase(api,'discovery')
                    if #selected>=32 then break end
                end
            end
        end
        if consume then
            -- Each streamed unit was checked against these globals immediately
            -- before its commands. No pointers or unfinished writes are retained.
        elseif same(api,globals) then
            for _,u in ipairs(selected) do
                for _,g in ipairs(globals) do u.guards[#u.guards+1]=g end
                result[#result+1]=u
            end
        else
            state.skipped=(state.skipped or 0)+1
            for _,u in ipairs(selected) do if state.fling_history then state.fling_history[u.unit]=nil end end
        end
    end
    state.read_bytes=used;state.read_calls=calls
    return result,'ready'
end

-- A settled remote ragdoll still receiving network corrections nudges its
-- skeleton a few centimetres every tenth of a second, and each nudge
-- requalified the same auxiliary actor: one recorded Acid Charger received 389
-- realignments in 4.3 s. The first correction stays immediate. A small repeat
-- on the same actor, unit and entity waits out the rest of the cooldown; a
-- large repeat still applies at once.
M.repose_cooldown=1
M.repose_bypass_m=.1
M.repose_bypass_degrees=5
local function defer_repeats(state,u,actions,now)
    local recent,kept=state.reposed,nil
    for i,action in ipairs(actions) do
        local last=action.kind=='pose' and recent[action.actor.id]
        local hold=last and last.unit==u.unit and last.entity==u.id and now>=last.at
            and now-last.at<M.repose_cooldown and action.gap<=M.repose_bypass_m
            and (action.degrees or 0)<=M.repose_bypass_degrees
        if hold then
            state.reposes_deferred=(state.reposes_deferred or 0)+1
            if not kept then kept={};for j=1,i-1 do kept[j]=actions[j] end end
        elseif kept then kept[#kept+1]=action end
    end
    return kept or actions
end

function M.apply(api,game,exe,state)
    phase(api,'maintenance')
    local now=api.time and api.time() or 0
    state.reposed=state.reposed or {}
    for id,entry in pairs(state.reposed) do
        if now<entry.at or now-entry.at>=M.repose_cooldown then state.reposed[id]=nil end
    end
    state.fling_history=state.fling_history or {}
    state.fling_stopped=state.fling_stopped or {}
    state.fling_scan=(state.fling_scan or 0)+1
    for key,entry in pairs(state.fling_history) do
        if now<entry.last or now-entry.last>1 then
            state.max_revisit_seconds=math.max(state.max_revisit_seconds or 0,now-entry.last)
            state.history_expirations=(state.history_expirations or 0)+1
            state.fling_history[key]=nil
        end
    end
    for key,entry in pairs(state.fling_stopped) do
        -- Count successful scans rather than wall time: a paused application
        -- must not forget a stop immediately before an ownership handoff.
        if state.fling_scan-entry.last_scan>256 then state.fling_stopped[key]=nil end
    end
    state.observed=0
    local function consume(u)
        state.observed=state.observed+1
        state.accepted_units=(state.accepted_units or 0)+1
        phase(api,'planning')
        local actions=M.plan(u)
        if api.profiler then
            u.profile_lifecycle=u.corpse and (#actions>0 and 'corpse_repair' or settled(u) and 'corpse_aligned' or 'corpse_other')
                or (u.update_enabled==false and 'ragdoll_stopped' or settled(u) and 'ragdoll_settled' or 'ragdoll_dynamic')
        end
        actions=defer_repeats(state,u,actions,now)
        local stopped=state.fling_stopped[u.unit]
        if #actions==0 and not stopped and u.corpse then return end
        if stopped and stopped.requested and u.corpse and u.active
            and stopped.resource==u.resource and same(api,u.guards) then
            -- Conversion creates a new entity while retaining the unit handle.
            -- Observe the phase; a submitted request alone is not success.
            state.completion_corpse_observed=(state.completion_corpse_observed or 0)+1
            state.fling_stopped[u.unit]=nil;stopped=nil
        end
        if stopped and (stopped.entity~=u.id or stopped.resource~=u.resource
            or stopped.members~=u.main_signature or u.corpse or u.update_enabled) then
            state.fling_stopped[u.unit]=nil;stopped=nil
        end
        -- No actions means this outer identity pass is redundant. Motion samples
        -- still need identity AND pose validation below: they can arm a later
        -- stop even when this poll issues no command.
        local planned=#actions>0 or stopped~=nil
        if not planned then state.guard_passes_skipped=(state.guard_passes_skipped or 0)+1 end
        if not planned or same(api,u.guards) then
            for _,action in ipairs(actions) do
                if same(api,u.guards) and same(api,action.actor.guards) then
                    if action.kind=='disable' then
                        phase(api,'native');state.native.disable(action.actor.id)
                        state.claws_disabled=(state.claws_disabled or 0)+1
                    else
                        phase(api,'native');state.native.pose(action.actor.id,action.position,action.rotation)
                        state.realignments=(state.realignments or 0)+1
                        local entry=state.reposed[action.actor.id]
                        if entry then entry.unit,entry.entity,entry.at=u.unit,u.id,now
                        else state.reposed[action.actor.id]={unit=u.unit,entity=u.id,at=now} end
                        if u.corpse and u.main_static<u.main_enabled then
                            state.mixed_corpse_realignments=(state.mixed_corpse_realignments or 0)+1
                        end
                        state.max_gap=math.max(state.max_gap or 0,action.gap)
                        state.last_unit=u.unit;state.last_actor=action.actor.id
                    end
                else state.skipped=(state.skipped or 0)+1 end
            end
            local stop,finish_handoff,request_completion
            local validate_motion=planned or (not u.corpse and u.owner==false and u.active==true
                and u.update_enabled==true and settled(u))
            if not validate_motion or (same(api,u.guards) and same(api,u.main_pose_guards or {})
                and (not u.root_body or same(api,u.root_body.guards or {}))) then
                if stopped then
                    stopped.last_scan=state.fling_scan
                    finish_handoff=u.owner and u.active and settled(u)
                    request_completion=u.owner==false and u.active and settled(u) and not stopped.requested
                        and stopped.stopped_at and now-stopped.stopped_at>=M.completion_grace
                end
                phase(api,'motion')
                stop=M.fling_action(u,state,now)
            else state.fling_history[u.unit]=nil end
            if finish_handoff and same(api,u.guards) then
                -- The component's runtime is copied unchanged when ownership
                -- moves (native 0x7a4b30). Finish ONLY a stop we previously
                -- made, through the routine's normal owned-Corpse branch.
                -- It may transition the entity, so do not read old storage.
                phase(api,'native');state.native.stop_sync(u.manager,u.index)
                state.fling_handoffs=(state.fling_handoffs or 0)+1
                state.fling_stopped[u.unit]=nil
            elseif request_completion and same(api,u.guards) then
                -- A remote stop never requests Corpse conversion. Ask its
                -- owner through the existing engine path once, after a grace
                -- period. No ownership, timer, or replication storage edits.
                stopped.requested=true
                state.completion_requests=(state.completion_requests or 0)+1
                state.last_completion_unit=u.unit;state.last_completion_entity=u.id
                state.last_completion_uptime=now
                phase(api,'native');state.native.request_completion(u.id)
                -- Native completion may invalidate entity storage. Read none
                -- of this snapshot again after the request.
            elseif stop and same(api,u.guards) and same(api,u.main_pose_guards or {}) then
                -- Run last: this routine changes update_enabled, invalidating
                -- this snapshot's guards. The remote-only gate avoids its
                -- locally-owned force-Corpse branch. No pose is rewound.
                phase(api,'native');state.native.stop_sync(u.manager,u.index)
                state.fling_stops=(state.fling_stops or 0)+1
                state.last_fling_unit=u.unit;state.last_fling_entity=u.id
                state.last_fling_type=profiles[u.resource].name;state.last_fling_reason=stop.cause
                state.last_fling_uptime=now
                state.last_fling_distance=stop.distance;state.last_fling_degrees=stop.degrees
                state.last_fling_actor=stop.actor
                state.last_fling_limb_distance=stop.limb_distance or 0
                state.last_fling_limb_degrees=stop.limb_degrees or 0
                if stop.limb_distance then state.fling_limb_stops=(state.fling_limb_stops or 0)+1 end
                if stop.cause=='landed_disabled' then state.landed_disabled_stops=(state.landed_disabled_stops or 0)+1 end
                state.max_fling_distance=math.max(state.max_fling_distance or 0,stop.distance)
                if api.read(u.update_address,1)=='\0' then
                    state.fling_stops_verified=(state.fling_stops_verified or 0)+1
                    state.fling_history[u.unit]=nil
                    state.fling_stopped[u.unit]={entity=u.id,resource=u.resource,members=u.main_signature,
                        last_scan=state.fling_scan,stopped_at=now}
                end
            elseif stop then
                -- A race at dispatch breaks the observation interval too.
                state.fling_history[u.unit]=nil
            end
        else
            state.fling_history[u.unit]=nil
        end
    end
    local budget={scanned=0,inspected=0,deadline=api.clock and api.clock()+M.budget_seconds}
    local units,reason=M.snapshot(api,game,exe,state,consume,budget)
    -- Snapshot substitutes used by policy tests may return complete units.
    if state.observed==0 then for _,u in ipairs(units) do consume(u) end end
    phase(api,'maintenance')
    state.scan_entities=(state.scan_entities or 0)+budget.scanned
    state.deep_inspections=(state.deep_inspections or 0)+budget.inspected
    if budget.yielded then state.budget_yields=(state.budget_yields or 0)+1 end
    if reason~='ready' then state.fling_history={};state.fling_stopped={};state.cursors={};state.reposed={} end
    state.completion_pending=0
    for _,entry in pairs(state.fling_stopped) do
        if entry.requested then state.completion_pending=state.completion_pending+1 end
    end
    return true,reason,reason=='ready'
end
return M
