"""Clickable Scrollbars' addon entry: every other src/*.lua file as a function of its own, ahead of
src/clickable_scrollbars.lua, as one plaintext Lua resource with the loader's discovery declaration first.
Standard library only and no side effects on import, so scripts/build.py and the Vanilla Plus Megapack build
produce the same bytes. Run directly, it writes the entry the Lua suites load:

    python scripts/entry.py [path]    (default build/clickable_scrollbars.lua)
"""
import re
import sys
from pathlib import Path

NAME = 'mods/cowboybingus/clickable_scrollbars'
MAIN = 'src/clickable_scrollbars.lua'
# The main file runs each other source file once, on a line of its own: cs_files.<name>(module, cs).
RUN = re.compile(r'^(?:[\w.]+ = )?cs_files\.(\w+)\(module, cs\)', re.MULTILINE)
# Source files the tests load but the entry does not ship.
TEST_ONLY = ('detector.lua',)


def read_lua(path):
    """A source file's text without its final newline: plain UTF-8 without a BOM or NUL bytes, LF line endings."""
    raw = Path(path).read_bytes()
    if raw.startswith(b'\xef\xbb\xbf') or b'\0' in raw:
        raise ValueError(f'{Path(path).name} must be plain UTF-8 without a BOM or NUL bytes')
    if b'\r' in raw:
        raise ValueError(f'{Path(path).name} must use LF line endings')
    return raw.decode('utf-8').rstrip('\n')


def source_files(root):
    """Every other src/*.lua file the entry ships, by name."""
    return sorted(p for p in (Path(root) / 'src').glob('*.lua') if p.name != Path(MAIN).name and p.name not in TEST_ONLY)


def entry_text(root):
    """The entry: the main file's declaration line, then each other source file as a function of its own (with
    its own limit of 200 locals) in the one local cs_files, in the order the main file runs them, then the rest
    of the main file, which runs each of them once."""
    root = Path(root)
    header, _, main = read_lua(root / MAIN).partition('\n')
    if header != '-- HD2-Addon: ' + NAME:
        raise ValueError(f'{MAIN} must start with its discovery declaration')
    runs = RUN.findall(main)
    files = [path.stem for path in source_files(root)]
    if sorted(runs) != files or len(set(runs)) != len(runs):
        raise ValueError(f'{MAIN} must run each other src/*.lua file once: runs {runs}, files {files}')
    lines = [header,
             '-- Generated by scripts/entry.py from ' + ', '.join(f'src/{name}.lua' for name in runs)
             + ' and ' + MAIN + '; edit those instead.',
             'local cs_files = {}']
    for name in runs:
        lines += [f'cs_files.{name} = function(...)', read_lua(root / 'src' / (name + '.lua')), 'end']
    lines.append(main)
    return ('\n'.join(lines) + '\n').encode('utf-8')


if __name__ == '__main__':
    ROOT = Path(__file__).resolve().parents[1]
    target = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / 'build' / 'clickable_scrollbars.lua'
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_bytes(entry_text(ROOT))
    print(target)
