"""Generate src/corpse_profiles.lua, the embedded allowlist, from the reviewed, checked-in asset catalog."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / 'src/corpse_profiles.lua'
# Variants of one skeleton share its lists, so R14 sees repeated token runs that
# start on these lines. They are regenerated from the single catalog, never
# edited by hand, so no copy can miss a fix.
DUPLICATES_OK = ' -- lint-ok: R14 generated from profiles/catalog.json'


def generate(catalog):
    lines = ['-- Generated by scripts/generate_profiles.py from profiles/catalog.json. Do not edit.',
             '-- Exact resource, skeleton, main-body and auxiliary actor allowlists.', 'local profiles = {']
    for p in catalog['profiles']:
        key = ''.join('\\%03d' % n for n in int(p['resource'], 16).to_bytes(8, 'little'))
        lines.append("    ['" + key + "']={name=" + json.dumps(p['name'])
                     + ',nodes=' + str(p['nodes']) + ',bodies=' + str(len(p['main']))
                     + ',finish_disabled=' + str(p['finish_disabled']).lower() + ',main={' + DUPLICATES_OK)
        lines.append('        ' + ','.join('0x%08x' % int(n, 16) for n in p['main']) + '},')
        if p.get('corpse_dynamic_main'):
            lines.append('        corpse_dynamic_main={' + ','.join('[%s]=true' % n for n in p['corpse_dynamic_main']) + '},')
        lines.append('        disabled_main={' + ','.join('[0x%08x]=true' % int(n, 16) for n in p['disabled_main']) + '},actors={')
        for actor, node in p['actors'].items():
            lines.append('            [' + actor + ']=' + node + ',')
        lines.append('        }},')
    lines += ['}', 'return profiles']
    return '\n'.join(lines) + '\n'


def main():
    catalog = json.loads((ROOT/'profiles/catalog.json').read_text())
    TARGET.write_text(generate(catalog), encoding='utf-8', newline='\n')


if __name__ == '__main__':
    main()
