"""Arc Thrower Revamped's addon entry: src/bingus_runtime.lua (Bingus Shared Runtime's core, the
update guard, vendored byte-identical) and src/arc_thrower_auto.lua assembled into the one plaintext
Lua resource the loader runs. Standard library only, no side effects on import.

    python -B scripts/entry.py <output.lua>
"""
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
MARKER = '-- HD2-Addon: mods/cowboybingus/arc_thrower_auto'


def read_lua(path):
    code = Path(path).read_bytes().decode('utf-8')
    if '\r' in code:
        raise ValueError(f'{Path(path).name} must use LF line endings')
    return code.rstrip('\n')


def entry_text(root=ROOT):
    """The entry: the marker line, the runtime core, then the addon in a function of its own, so the
    addon's jit.off(true, true) covers the addon's functions only."""
    body = read_lua(Path(root) / 'src' / 'arc_thrower_auto.lua')
    lines = [MARKER,
             '-- Generated by scripts/entry.py from src/bingus_runtime.lua and src/arc_thrower_auto.lua; '
             'edit those instead.',
             'local runtime = (function()', read_lua(Path(root) / 'src' / 'bingus_runtime.lua'), 'end)()',
             ';(function(runtime)', body, 'end)(runtime)']
    return ('\n'.join(lines) + '\n').encode('utf-8')


if __name__ == '__main__':
    Path(sys.argv[1]).write_bytes(entry_text())
